### ISSUE TITLE
create a workflow to build docker image on release

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtecharchive/tfgrid_dashboard#102]

**Comment by khaledyoussef24** [comment]
verified
![Screenshot from 2022-08-22 15-50-52](https://user-images.githubusercontent.com/110984055/186044941-4d394b24-6d37-4e1b-bf00-0d3e5d16abc0.png)
![Screenshot from 2022-08-22 15-50-59](https://user-images.githubusercontent.com/110984055/186044949-f2613516-c7e2-4ef4-8809-a78756254bb1.png)
