### ISSUE TITLE
Make tables' values aligned to the center of the header

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtecharchive/tfgrid_dashboard#104]
This needs to be aligned to the center of the header
![image](https://user-images.githubusercontent.com/41957921/178743276-282fca51-eb95-4f2e-b836-1e28b69cc340.png)

like this one 
![image](https://user-images.githubusercontent.com/41957921/178743294-1b0c70ec-e991-46ad-aa07-506c5c8d7367.png)

**Comment by mohamedamer453** [comment]
Verified.

The values are now aligned to the center of the header.

![image](https://user-images.githubusercontent.com/101194226/183288188-77c9825d-8571-4962-8f8d-31565663aacf.png)
