### ISSUE TITLE
Dedicated nodes are not appearing on QAnet

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#106]
### Description.

The dedicated nodes table on QAnet shows that there are no dedicated nodes available.

![image](https://user-images.githubusercontent.com/101194226/180214570-2a6c5d0c-ded5-42e8-b106-da78e5d80610.png)

with the following error in the console when you open the nodes page.

![image](https://user-images.githubusercontent.com/101194226/180214731-9edfae5b-f1d8-4ea4-aa29-abf6bd2017e0.png)

```
nodes.ts:181 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'discount')
    at za (nodes.ts:181:77)
    at async nodes.ts:227:22
```

And by checking the explorer and grid proxy you can see that nodes(4,5) are online and they are labeled as dedicated nodes in the grid proxy `https://gridproxy.qa.grid.tf/nodes?status=up`

![image](https://user-images.githubusercontent.com/101194226/180214469-91065cac-60e7-4cb8-92c4-0a2a402f1d99.png)

**Comment by khaledyoussef24** [comment]
checked
