### ISSUE TITLE
Require multiple confirmations for removing public config

### ISSUE THREAD

**Issue by scottyeager** [threefoldtecharchive/tfgrid_dashboard#107]
The UI for removing or changing a node's public config should include an extra "are you sure" confirmation, along with a warning about how this could disrupt any workloads utilizing the public config. See motivation [here](https://github.com/threefoldtech/zos/issues/1767#issuecomment-1193821973).

**Comment by mohamedamer453** [comment]
Currently blocked on verifying this issue due to #125

**Comment by mohamedamer453** [comment]
No confirmation messages were added and when you click on `Remove Config` It opens the Polkadot transaction immediately without any confirmations before.

![Untitled_ Jul 31, 2022 3_29 PM (1)](https://user-images.githubusercontent.com/101194226/182028874-01b954bf-21cf-49e5-a57d-e54d030d4af0.gif)


There's only a confiramtion message when you add/edit the config but it's not very clear.

![image](https://user-images.githubusercontent.com/101194226/182028959-7605b7e0-d5a0-4b07-a5fd-187e780ac4b4.png)

**Comment by mohamedamer453** [comment]
Verified.

Additional confirmation was added before removing the public config.

![TF DASHBOARD (7)](https://user-images.githubusercontent.com/101194226/182034099-e905c571-3c93-4f04-9eff-2525575f850c.gif)
