### ISSUE TITLE
Account-Dao page

### ISSUE THREAD

**Issue by coesensbert** [threefoldtecharchive/tfgrid_dashboard#109]
1. Load proposals when the users navigates to the page

2. Reload proposals when a vote is cast

3. When voting for a proposal all the buttons start spinning:

![image](https://user-images.githubusercontent.com/88312671/181007922-0ddc5e07-7f8c-4db8-99b5-7490fe00b19e.png)

**Comment by amiraabouhadid** [comment]
@coesensbert Hey so all the buttons start spinning to avoid making multiple transactions at the same time so not sure why you want that to be different. I would appreciate it if you can clarify.

**Comment by DylanVerstraete** [comment]
Personally for me it looks weird that all buttons are spinning. I would let 1 button spin and disable the others while the transaction is in progress? :)

**Comment by coesensbert** [comment]
I want nothing, just suggestions :) But agree that it's confusing if all the buttons start spinning, rather have the one that is clicked giving me a sign (spinning, hourglass, ..) that it's waiting for the confirmation of my action.

**Comment by amiraabouhadid** [comment]
alrighty, thanks for the feedback, will implement

**Comment by mohamedamer453** [comment]
Verified.

- The proposals are loaded when the user clicks on DAO from the sidebar

  
   ![TF DASHBOARD](https://user-images.githubusercontent.com/101194226/181515069-77a1b029-ab48-4a46-bf2e-1dc720532faa.gif)

-  Only the submit button spins now

   ![image](https://user-images.githubusercontent.com/101194226/181512493-d54156d1-b4dc-4e84-812b-31a16b361c56.png)

- The Proposals are reloaded when a vote is cast but it's not reflected immediately and you have to reload the page for it to appear.

   ![TF DASHBOARD (1)](https://user-images.githubusercontent.com/101194226/181515431-de2831d7-624d-40a1-aa6e-242bb73da407.gif)

**Comment by mohamedamer453** [comment]
Verified.

The new votes now appear immediately when the proposals are reloaded after voting.

![TF DASHBOARD (9)](https://user-images.githubusercontent.com/101194226/182109406-c737a45d-d3ad-449a-bb67-5329407f5b39.gif)
