### ISSUE TITLE
Account-Farms page

### ISSUE THREAD

**Issue by coesensbert** [threefoldtecharchive/tfgrid_dashboard#110]
1. In the nodes table the Node ID show is the wrong field, this is an auto generated ID by Graphql. We need to see the real Node ID from the chain. 'nodeID' is the field which needs to be shown.

2. Some error occurs while fetching a node that make all the nodes seem down

![image](https://user-images.githubusercontent.com/88312671/181008498-5f8c819b-8d4a-4708-959b-585284123851.png)

**Comment by mohamedamer453** [comment]
Verified.

The Node ID is displayed correctly also the status of the node and node of these errors are appearing in the console anymore.

![image](https://user-images.githubusercontent.com/101194226/181511762-cda6d174-d24f-463c-b635-b70db5ede7b0.png)
