### ISSUE TITLE
Wallet selection / navigation is confusing

### ISSUE THREAD

**Issue by coesensbert** [threefoldtecharchive/tfgrid_dashboard#111]
On first visiting the dasboard you get a list of your wallets in the Polka extension.
![image](https://user-images.githubusercontent.com/88312671/181016544-99d93f3f-406b-4ff3-ae7b-3a780c3ce1dc.png)

After selecting a wallet I'm not able to navigate further unless i select the same wallet again on the left side.
It takes 4 clicks to get to another page: open left side, click portal, click wallet, click new page
![image](https://user-images.githubusercontent.com/88312671/181017404-098853a9-a39c-4fc6-aeb6-805bd87ccd46.png)

Suggestion:
Keep the first page where you select the wallet, use the left side to provide all the links for the selected wallet.
Switching to another wallet will not happen a lot. In the portal this could be done by clicking on the logo (top left) and selecting a new wallet.

**Comment by khaledyoussef24** [comment]
##verified on devnet
steps made to verify this

1. open the dashboard
2. choose an account
3. the drawer will open automatically for the selected choice
![Screenshot from 2022-08-24 09-39-18](https://user-images.githubusercontent.com/110984055/186360009-481c3c53-1eed-4faa-b0d7-7be6df6616f3.png)
![Screenshot from 2022-08-24 09-39-27](https://user-images.githubusercontent.com/110984055/186360020-53f3796a-7fe1-454a-9f42-cf89f21bfb5e.png)
