### ISSUE TITLE
Explorer farms filters by names doesn't work with Lower case letters

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#112]
### Description

When filtering by farm name in Explorer, the search must be done in case sensitive mode else it will not display.
The issue exists on all main, dev, test, and qa nets.

### Steps to reproduce

1. Navigate to Explorer
2. Choose Farms on the left side menu.
3. check Name filter.
![image](https://user-images.githubusercontent.com/109473873/180743593-b435ce04-f4fc-4a8e-9bf5-1bc0c8ec5a08.png)

5. Type a name from list in FILTER BY FARM NAME input but in insensitive case.
![image](https://user-images.githubusercontent.com/109473873/180744096-f9bf4c69-cf35-4eb5-a7e3-5d6976d298de.png)

7. Apply filters.
![image](https://user-images.githubusercontent.com/109473873/180744163-314368cc-8798-41b0-9089-ab745d4be045.png)

### Logs/Alerts

filtering works only in case sensitive.
![image](https://user-images.githubusercontent.com/109473873/180744848-e84b7698-3d4a-4efe-a7a5-4a1009fa1097.png)

https://user-images.githubusercontent.com/109473873/180749677-8eb18b9b-58d6-49c6-bb34-51c7787e4ec1.mp4

**Comment by zaelgohary** [comment]
Grid Proxy & Graphql do not support case-insensitive queries.

**Comment by AhmedHanafy725** [comment]
@zaelgohary please open an issue in gridproxy to check if it can be supported

**Comment by zaelgohary** [comment]
Done. https://github.com/threefoldtech/tfgridclient_proxy/issues/181

**Comment by khaledyoussef24** [comment]
verified on devnet
![Screenshot from 2022-08-23 10-49-34](https://user-images.githubusercontent.com/110984055/186115375-b04e3bc0-961d-492d-b271-e478906880df.png)


it doesn't work on testnet and qa

it only show results for couple of seconds
and then results vanish
![Screenshot from 2022-08-23 10-51-43](https://user-images.githubusercontent.com/110984055/186115836-584dc4a2-1bda-44d6-a4cb-d0d78e306dd3.png)
![Screenshot from 2022-08-23 10-52-19](https://user-images.githubusercontent.com/110984055/186115846-46e4fd59-538e-4ade-a18c-30f6de99c223.png)
