### ISSUE TITLE
Some small suggestions regarding text

### ISSUE THREAD

**Issue by coesensbert** [threefoldtecharchive/tfgrid_dashboard#113]
- On the left side every link has 'Account' in it. All these could be gone while you still know what the link is for

- Account-Twin: the page congratulates me on creating a twin, while these have been created months ago
![image](https://user-images.githubusercontent.com/88312671/181019681-3e4db380-0500-4e88-a64e-5d49070aea07.png)

- Account-Swap: "We use bridges for transfer to and from the following" is not a very clear description for new users. The link "why do we use bridges" does not explain why we do.
![image](https://user-images.githubusercontent.com/88312671/181020039-61996a66-1c53-4a78-b1ab-93ec4dd9b2a6.png)

- Account-Transfer: the page greets me with Howdy, which is fine but the Accounts-Farms page greets me with "Greetings". The Account-Dao & Account-Nodes page also uses Howdy. With current navigation is never the page that is visited first, so maybe best to not greet the user there?
![image](https://user-images.githubusercontent.com/88312671/181021074-9c84219b-5da7-4941-817b-1ac3c393883e.png)
![image](https://user-images.githubusercontent.com/88312671/181021116-e17bd399-85ad-4b3a-be44-5b3a221d75d2.png)
![image](https://user-images.githubusercontent.com/88312671/181021306-38f50e43-04cb-4852-8e35-fed259839769.png)

**Comment by mohamedamer453** [comment]
Verified.

- The `Account -` prefix was removed from all items

   ![image](https://user-images.githubusercontent.com/101194226/181268499-89bc0569-1337-4c8b-9fe0-52d9c8cdbb3f.png)

-  The congratulations message was removed and replaced with `Twin Details`

   ![image](https://user-images.githubusercontent.com/101194226/181268679-c3e379ab-6e9c-4c29-a20d-5f3828873fad.png)

- The description was changed to `How is it done?` and now it redirects to the correct link in the [manual](https://library.threefold.me/info/manual/#/manual__grid3_stellar_tfchain_bridge) 

   ![image](https://user-images.githubusercontent.com/101194226/181269432-9dd1cad6-b852-4517-9838-433fb012b57d.png)

-  The greeting messages were removed from the Transfer and Farms Pages and were replaced with the appropriate titles.

   ![image](https://user-images.githubusercontent.com/101194226/181270234-e0c637c2-d7cb-4e4c-91ef-bba208acfab2.png)

   ![image](https://user-images.githubusercontent.com/101194226/181270387-1e9d664d-a9f7-4bf2-a4b2-2b3216baec84.png)

**Comment by mohamedamer453** [comment]
but in the dao page it still needs to be changed.

![image](https://user-images.githubusercontent.com/101194226/181270738-680e7309-5fa3-4496-91e4-9363b9cddf8e.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The dao page message was changed.

![image](https://user-images.githubusercontent.com/101194226/187252814-ccd33294-1d73-44b6-bf46-2e6b7712798c.png)
