### ISSUE TITLE
'More Details' of DAO proposal systematically gives spinning screens

### ISSUE THREAD

**Issue by gmachtel** [threefoldtecharchive/tfgrid_dashboard#122]
I click on 'More Details' in a DAO proposal, I get a screen with permanent spinning wheel (both qa and testnet, and for all proposals made). 

<img width="1512" alt="Screenshot 2022-07-28 at 16 29 32" src="https://user-images.githubusercontent.com/30384423/181556861-28b54a3d-501a-4464-9cdc-485e8fe56ca4.png">

**Comment by rawdaGastan** [comment]
@gmachtel the proposal's link itself is not in the correct format. It is a creation proposal issue.
