### ISSUE TITLE
Rework dedicated nodes

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtecharchive/tfgrid_dashboard#126]
Currently dedicated nodes work as following:

- Either a farm is dedicated, then every node in that farm can be rented
- When a node has no contracts (0 active contracts) it can also be rented

We need to show a list where this is combined.

**Comment by mohamedamer453** [comment]
Verified on devnet.

The dedicated nodes table now shows `dedicated` & [`rented`](https://gridproxy.dev.grid.tf/nodes?rented=true) & [`rentable`](https://gridproxy.dev.grid.tf/nodes?rentable=true&status=up) nodes 

![image](https://user-images.githubusercontent.com/101194226/187250163-ae7a71fd-99ba-40e9-848b-7e28f3dcda30.png)

**Comment by despiegk** [comment]
@mohamedamer453 where does it say dedicated & [rented](https://gridproxy.dev.grid.tf/nodes?rented=true) & [rentable](https://gridproxy.dev.grid.tf/nodes?rentable=true&status=up)?

**Comment by xmonader** [comment]
> @mohamedamer453 where does it say dedicated & [rented](https://gridproxy.dev.grid.tf/nodes?rented=true) & [rentable](https://gridproxy.dev.grid.tf/nodes?rentable=true&status=up)?

he meant the table shows the data coming from rentable and rented endpoints of the proxy (not in the table, the table shows  all of available nodes taken/free) , from the other issue here https://github.com/threefoldtech/tfgridclient_proxy/issues/183

![image](https://user-images.githubusercontent.com/64129/188256693-68ceaaf8-40a9-4d4c-8279-9ee1da4701f2.png)
