### ISSUE TITLE
UI: Sterllar Payout Address spaces

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#129]
Add a space between the Address and the edit button.

![image](https://user-images.githubusercontent.com/101194226/182022432-350afd80-c45a-4695-9aaa-854d0b99a0f7.png)

**Comment by rawdaGastan** [comment]
I think it is solved now 
![Screenshot from 2022-08-04 17-15-28](https://user-images.githubusercontent.com/47260239/182883657-feae40a4-b06d-46f2-a0df-94b1f88e50b1.png)

**Comment by mohamedamer453** [comment]
This issue only appeared at certain width, for example when the window was taking half of the screen or minimized it appeared as mentioned in the comment (The edit button is placed under the address). but when the window was taking the whole screen it appeared as mentioned originally in the issue (The edit button is right next to the address without any spaces)

![TF DASHBOARD (11)](https://user-images.githubusercontent.com/101194226/183283157-6977a9dd-a81f-4c4a-afe6-e538f0e2dcf9.gif)

**Comment by mohamedamer453** [comment]
Verified.

The space between the address and the edit button was added.

![image](https://user-images.githubusercontent.com/101194226/183288773-08b2b0f4-fc6b-47e3-ae1d-8b02c4ca1a05.png)
