### ISSUE TITLE
Withdraw TFT balance check is not working correctly 

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#133]
The balance check in the `Amount` field for `Withdraw TFT` is not working correctly.

As seen in the gif below i have approx. `34.7` TFTs in my account and when i enter values from 4 -> 9 it says that the amount cannot exceed the balance and it works normally for any other value. and  when i entered `35` which is greater than my actual balance it worked as intended.

![TF DASHBOARD (4)](https://user-images.githubusercontent.com/101194226/182024882-6ac26a61-6d59-4a47-841f-e03b6ccec0d3.gif)

**Comment by rawdaGastan** [comment]
This is solved now here:
- https://github.com/threefoldtech/tfgrid_dashboard/pull/136

**Comment by mohamedamer453** [comment]
Verified.

All the values that previously failed the check (4 -> 9) are working now and now all the values are accepted except for the values that actually exceed the balance. 

![TF DASHBOARD (10)](https://user-images.githubusercontent.com/101194226/182141508-ab233c75-148a-4662-ae9e-94ecf7dac7ad.gif)
