### ISSUE TITLE
UI: Dao Proposals Progress bar

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#137]
The progress bar shows too many numbers after the `.` and it's also showing a grey part at the end.

![image](https://user-images.githubusercontent.com/101194226/182029468-52b865b2-0760-4448-b567-3481c4f03fb8.png)

**Comment by rawdaGastan** [comment]
This is solved here 
- https://github.com/threefoldtech/tfgrid_dashboard/issues/139

**Comment by mohamedamer453** [comment]
Fixed and Verified in #139
