### ISSUE TITLE
number in votes doesn't all appear

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtecharchive/tfgrid_dashboard#139]
- The voting numbers don't all appear in Dao tab 
- We can round the number to avoid this issue

![Screenshot from 2022-07-31 16-55-30](https://user-images.githubusercontent.com/47260239/182032384-75e300f5-8ffa-4f25-9cf3-790f59f83d25.png)

**Comment by mohamedamer453** [comment]
Verified.

The numbers were rounded.

![image](https://user-images.githubusercontent.com/101194226/182108470-156d8ae7-3bbe-4aba-a2f8-469ce46575d2.png)

but there's still a grey part in the progress bar that doesn't correspond to any of the answers.

![image](https://user-images.githubusercontent.com/101194226/182108908-84b58169-520c-42f2-871d-4ec01e75f532.png)

**Comment by mohamedamer453** [comment]
Verified.

The grey part was removed 

![image](https://user-images.githubusercontent.com/101194226/182139790-ef1b29d7-17a8-41a1-840e-e3a33df07e23.png)
