### ISSUE TITLE
Adjust colors and fonts to be like grid_weblets

### ISSUE THREAD

**Issue by ehab-hassan** [threefoldtecharchive/tfgrid_dashboard#14]
Blue/hover #1982b1
dark blue for nav #064663
Body #f4f4f4
Sidebar black #333
Font: Lato

**Comment by ehab-hassan** [comment]
@xmonader please check at development_ui branch 
note: we add dark and light mode

**Comment by despiegk** [comment]
@ehab-hassan please i wanna see screenshot of the updated homepage of dashboard

**Comment by ehab-hassan** [comment]
@despiegk it is already what we have at production now tfgrid and portal have same theme
https://play.dev.grid.tf/#/vm
https://portal.grid.tf/

![image](https://user-images.githubusercontent.com/10484295/188168027-cc18bfc1-3eb3-44a6-a07f-fda347fa65ef.png)
