### ISSUE TITLE
remove public configs msgs

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtecharchive/tfgrid_dashboard#140]
### Description

 - remove public configs has the same msgs as adding them in success and failure
 `Adding Node public config failed`
`Node public config added!`

**Comment by mohamedamer453** [comment]
Verified.

### Adding Config

![image](https://user-images.githubusercontent.com/101194226/182132491-19ff0f28-7aa0-47a4-a864-5fd0f6464202.png)

![image](https://user-images.githubusercontent.com/101194226/182139475-068a740a-2e6f-4896-9f27-edb2dc2f47e7.png)

### Removing Config

![image](https://user-images.githubusercontent.com/101194226/182132412-80985704-7276-4955-8ce3-49369c677c65.png)

![image](https://user-images.githubusercontent.com/101194226/182139569-3811dbf8-57ab-44e2-8159-1c6dda0d76f0.png)
