### ISSUE TITLE
Mainnet: wrong public config input validation

### ISSUE THREAD

**Issue by coesensbert** [threefoldtecharchive/tfgrid_dashboard#148]
On the Farms page, when trying to input a ipv4 address it should include the subnet. Without a subnet defined a public config can not work.

When entering the ipv4 in the correct way, the UI states it's not correctly formatted:
![image](https://user-images.githubusercontent.com/88312671/182345688-003b74a8-4527-4e60-aa30-3f5a73b43af8.png)

When we input only the ip, it does accept it. But configuring only the ip will not work.
![image](https://user-images.githubusercontent.com/88312671/182345841-961de317-c6ce-452b-8d49-c854297b88a6.png)

For ipv6 the UI does accept the subnet.

**Comment by coesensbert** [comment]
Same for adding ip's to a farm

![image](https://user-images.githubusercontent.com/88312671/182347014-7410a225-ab62-4291-87f8-3f4bc8dc65c0.png)

![image](https://user-images.githubusercontent.com/88312671/182347066-ecd9a220-a8c9-4596-8d77-92609db20b50.png)

**Comment by ramezsaeed** [comment]
it fixed but not deployed on mainnet yet
