### ISSUE TITLE
Dedicated Nodes price is NaN

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtecharchive/tfgrid_dashboard#150]
- Price in Dedicated Nodes table is Nan

![Screenshot from 2022-08-02 13-21-29](https://user-images.githubusercontent.com/47260239/182364992-737f75a3-34df-494f-9043-83670da5c0be.png)

**Comment by mohamedamer453** [comment]
Verified.

The node prices are displayed correctly.

![image](https://user-images.githubusercontent.com/101194226/183283506-eefba98e-2068-4498-bf12-cde14d3bc514.png)
