### ISSUE TITLE
some fields don't appear in account farms

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtecharchive/tfgrid_dashboard#151]
- pricing policy
- linked twin 

![Screenshot from 2022-08-02 18-00-33](https://user-images.githubusercontent.com/47260239/182420025-a91162b8-965b-4b5c-85da-bdd0d4cf4bbc.png)

**Comment by khaledyoussef24** [comment]
##verified on devnet 
info is now available 

pricing policy
linked twin

![Screenshot from 2022-08-24 09-45-52](https://user-images.githubusercontent.com/110984055/186361268-a1ecbb2a-7614-4823-8574-458f2f2039ab.png)
