### ISSUE TITLE
Statistics page doesnt show nodes in Vietnam, while there are 17 online

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtecharchive/tfgrid_dashboard#152]
Farm ID: 33

**Comment by sabrinasadik** [comment]
And pls change the name to Vietnam, right now it says Viet Nam.

**Comment by AhmedHanafy725** [comment]
seems an issue on the map component itself as there are 18 nodes there returned from the api https://gridproxy.grid.tf/stats?status=up

**Comment by sabrinasadik** [comment]
Is this only an issue for Vietnam? Or are there more nodes that don't reflect on the map?

**Comment by MohamedElmdary** [comment]
Found the issue in tf-map and created a new relase [v0.0.4](https://cdn.jsdelivr.net/gh/threefoldtech/tf-map@0.0.4/dist/tf-map.js)

![image](https://user-images.githubusercontent.com/31689104/185171720-74ee5307-e9fb-4164-a32c-4f3fa93bfd1d.png)

**Comment by sabrinasadik** [comment]
When will this reflect on the map?

**Comment by mohamedamer453** [comment]
Verified on devnet.

The name was fixed and will re-verify the number of nodes once it's released on mainnet.
![image](https://user-images.githubusercontent.com/101194226/186372088-ab7b35c7-25a4-4824-a7f2-154e1ec4296f.png)
