### ISSUE TITLE
Inactive proposals

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtecharchive/tfgrid_dashboard#155]
- Inactive proposals don't appear if there are no active proposals

**Comment by mohamedamer453** [comment]
Verified.

There are currently no active proposals and you can see the inactive/expired ones in the `Executable` tab

![TF DASHBOARD (15)](https://user-images.githubusercontent.com/101194226/183289187-9af3bcb4-25ee-44fd-b587-7fe37be37649.gif)
