### ISSUE TITLE
Calculation of a decimal number TFT transaction is incorrect.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#164]
Transfer TFTs on the TFChain's decimal number TFT calculation is inaccurate; although calculations for the first and second decimal places are accurate, calculations beginning with the third are incorrect.

![test 11](https://user-images.githubusercontent.com/109473873/183610936-0bce0739-c14c-4e93-8398-b9c086f9efa0.png)

Result of subtracting 0.009 from 11.9899 should be equal 11.9809 
![test 12](https://user-images.githubusercontent.com/109473873/183610978-3dac180b-229f-487c-a3e1-7c05e76a2a2e.png)

**Comment by rawdaGastan** [comment]
Hello, This is because transactions fees :D @A-Harby

**Comment by mohamedamer453** [comment]
Verified on devnet.

by calculating the difference between the 2 value it resulted in `0.0010145` which is the transaction fees as mentioned above.

however there should be an indication for the user about the deducted fees and it will be followed in #210
