### ISSUE TITLE
Farm public IPs listing 

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtecharchive/tfgrid_dashboard#167]
- Farm public IPs listing doesn't work

![Screenshot from 2022-08-10 16-50-38](https://user-images.githubusercontent.com/47260239/183939490-8be7ea0f-59b9-4246-9fcc-675df08a7e24.png)

**Comment by DylanVerstraete** [comment]
Some bad query is being executed:

https://github.com/threefoldtech/tfchain_graphql/issues/50

**Comment by khaledyoussef24** [comment]
##verified on devnet
steps made to verify this case

1. go to the dashboard
2. choose your account from portal
3. choose Farm tab
4. create your own farm
5. click on the drop down arrow next to farm number
6. choose add ip
7. insert ip range and gateway
![Screenshot from 2022-08-23 15-24-06](https://user-images.githubusercontent.com/110984055/186171334-02e69f6e-366a-4911-a153-2322f4d0c946.png)
![Screenshot from 2022-08-23 15-24-12](https://user-images.githubusercontent.com/110984055/186171347-b117214a-b9eb-49da-90ba-1c8c8fb42bd7.png)
![Screenshot from 2022-08-23 15-24-19](https://user-images.githubusercontent.com/110984055/186171355-7fde02cf-6312-4edc-9ba8-a93edf107ae4.png)
![Screenshot from 2022-08-23 15-24-22](https://user-images.githubusercontent.com/110984055/186171373-702386e9-ea94-4f23-ad08-acbeccb06e44.png)
![Screenshot from 2022-08-23 15-34-11](https://user-images.githubusercontent.com/110984055/186171863-2ae64f25-beb1-4af3-b07b-2e05b64e45a4.png)
