### ISSUE TITLE
delete buttons all spinning

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtecharchive/tfgrid_dashboard#168]
- all delete buttons are spinning while deleting publicIP 
![Screenshot from 2022-08-10 16-50-25](https://user-images.githubusercontent.com/47260239/183939924-df03a982-1031-4ef2-86aa-892d8740afbe.png)

**Comment by A-Harby** [comment]
Verified on Devnet.
Only the IP that has been deleted is spinning.

![image](https://user-images.githubusercontent.com/109473873/193539899-b7363c96-9010-4c38-8e5b-728cd67e8f5f.png)

Test steps: [TC1187 - Delete IP](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3725643)
