### ISSUE TITLE
Add solution provider ID on creating rent contract

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtecharchive/tfgrid_dashboard#171]
a new field is added to the contract creation (solution_provider_id: number)

see JS client lib: https://github.com/threefoldtech/tfchain_client_js/releases/tag/1.16.0

**Comment by mohamedamer453** [comment]
Verified on devnet.

The solutionProviderId was added to the rent contract and i was able to reserve and unreserve a node.

![image](https://user-images.githubusercontent.com/101194226/187247336-10b76dae-01a0-4f8d-8725-c7ffc6acee30.png)

![image](https://user-images.githubusercontent.com/101194226/187247484-84169f0a-1ac1-463c-ab47-0a11cda49f26.png)

And the new dedicated nodes logic was applied and now the `rentable` and `rented` nodes appear in the dedicated nodes table

![image](https://user-images.githubusercontent.com/101194226/187247083-b4819ccd-840b-4126-8e3d-5d651084a467.png)
