### ISSUE TITLE
Add live support chat button

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tfgrid_dashboard#172]
```
<script type="text/javascript"> window.$crisp = []; window.CRISP_WEBSITE_ID = "1a5a5241-91cb-4a41-8323-5ba5ec574da0"; (function () { d = document; s = d.createElement("script"); s.src = "https://client.crisp.chat/l.js"; s.async = 1; d.getElementsByTagName("head")[0].appendChild(s); })(); </script>
```

**Comment by khaledyoussef24** [comment]
##verified on devnet dashboard
![Screenshot from 2022-08-23 13-02-21](https://user-images.githubusercontent.com/110984055/186142396-c25056fe-f85b-41b3-9115-a3986ee68879.png)
![Screenshot from 2022-08-23 13-02-33](https://user-images.githubusercontent.com/110984055/186142407-72ea44ab-516f-41e3-8420-a550ac569ce4.png)
![Screenshot from 2022-08-23 13-02-47](https://user-images.githubusercontent.com/110984055/186142410-518e1f34-4f84-4c3b-816f-2cbbd0ebd8cc.png)
