### ISSUE TITLE
the created farms doesn't appear in the farms table

### ISSUE THREAD

**Issue by doaasaber** [threefoldtecharchive/tfgrid_dashboard#173]
it displayed farm created and nothing in the farm's table but it show all the farms on explorer => farms

note this issue is on dashboard.qa.grid.tf but it works on dashboard.test.grid.tf
![Farm](https://user-images.githubusercontent.com/54359761/184493180-bbd7424f-f297-400a-a52e-604131e26ab9.png)
![farm2png](https://user-images.githubusercontent.com/54359761/184493188-226d32a8-48a2-4de6-8a84-d13970cdedfe.png)
![farm3](https://user-images.githubusercontent.com/54359761/184493206-68ced96b-1cdf-463f-969c-21869052a51c.png)
![NewFarm](https://user-images.githubusercontent.com/54359761/184493281-046d3483-bf42-4896-b3b4-00e1faf51034.png)

**Comment by rawdaGastan** [comment]
It will take a time to handle all types of errors coming from the chain, also this should be done after cleanup issue assigned to amira

**Comment by mohamedamer453** [comment]
Verified on devnet.

newly created farms appear in the farms table after creation.

![TF DASHBOARD (17)](https://user-images.githubusercontent.com/101194226/187172471-a2e2afd5-cf81-479e-9f4e-62cf08f28670.gif)
