### ISSUE TITLE
add pricing calculator in the dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tfgrid_dashboard#179]
part of https://github.com/threefoldtech/home/issues/1286

**Comment by khaledyoussef24** [comment]
### verified

you can now open the calculator from the side menu in the dashboard

![Screenshot from 2022-10-30 14-22-09](https://user-images.githubusercontent.com/110984055/198878213-23d8f322-8411-4d65-bfe8-d7e0d16d9789.png)


![Screenshot from 2022-10-30 14-22-19](https://user-images.githubusercontent.com/110984055/198878211-a7875694-1d9b-4c93-ae0e-d15c1f33d74c.png)

**Comment by xmonader** [comment]
Great job @zaelgohary, I love what you did with the colors of the packages! I've some comments still

- Let's make we have some default values instead of zeros. I suggest `1 Core, 25GB SDD, 100HDD, 1GB RAM`
- Let's have the units capitalized in case of cores, should be Cores
- Add tooltip on each input to clarify its role
- Add TFT price with the dollar price for shared and dedicated nodes
- Add a wiki link to explain the pricing and the packages

**Comment by zaelgohary** [comment]
@xmonader all requested changes are done except for the TFT price as I have no access to its endpoint.

![image](https://user-images.githubusercontent.com/40770501/200160703-733fbe64-4175-425f-82f3-cbdd65e5de07.png)

**Comment by AhmedHanafy725** [comment]
The balance required from the user to enter should be in USD for the current implementation, it needs to be converted to TFT in the equations, or change the units (in the balance box) to be in USD

**Comment by xmonader** [comment]
@zaelgohary I created a ticket to enable CORS on the service.
https://github.com/threefoldtech/tf_operations/issues/1249

**Comment by xmonader** [comment]
As the service of tftprice is deprecated, we can directly call on stellar DEX https://github.com/threefoldtech/tfchain/blob/feaaf28200e4ed820263287ae59984ef72068a76/substrate-node/pallets/pallet-tft-price/src/lib.rs#L273

**Comment by mohamedamer453** [comment]
Verified on devnet.

> * Let's make we have some default values instead of zeros. I suggest `1 Core, 25GB SDD, 100HDD, 1GB RAM`
> * Let's have the units capitalized in case of cores, should be Cores
> * Add tooltip on each input to clarify its role
> * Add TFT price with the dollar price for shared and dedicated nodes
> * Add a wiki link to explain the pricing and the packages

all of the comments mentioned above were added to the pricing calculator.

- Default values were added with the mentioned values.

   ![image](https://user-images.githubusercontent.com/101194226/201111639-afb08fde-9fd3-4477-8079-8afc777e11d3.png)

- The units were Modified and Capitalized

   ![image](https://user-images.githubusercontent.com/101194226/201111988-2d90bf2e-9418-4a94-8783-b5f72d69b352.png)

- a tooltip was added for each resource

   ![image](https://user-images.githubusercontent.com/101194226/201112324-4825a7b5-7e13-44c4-8dea-16e23eba982d.png)

   ![image](https://user-images.githubusercontent.com/101194226/201112454-571d4f67-d237-4016-8155-b9a582d03d45.png)

   ![image](https://user-images.githubusercontent.com/101194226/201112243-f3a2de60-2523-4140-a98f-324dfe914f0e.png)

   ![image](https://user-images.githubusercontent.com/101194226/201112525-8406b2e9-33f4-4505-883f-e44fbba129bb.png)

- The price is now available in USD & TFT /month

   ![image](https://user-images.githubusercontent.com/101194226/201112878-fb4cf9e6-5b1a-411c-af0a-3f276a193efa.png)

- wiki link that redirects to https://library.threefold.me/info/threefold/#/tfgrid/pricing/threefold__pricing was added.

   ![image](https://user-images.githubusercontent.com/101194226/201113065-4921484d-420a-4fe2-9710-84a965471355.png)
