### ISSUE TITLE
add developer guide to this repo

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tfgrid_dashboard#180]
explain the architecture and conventions used in this project, should be located in `docs` directory in this repo

**Comment by mohamedamer453** [comment]
Verified.

A [developer get started guide](https://github.com/threefoldtech/tfgrid_dashboard/blob/development/docs/Get_Started_Guide.md) was added in the `docs` directory this guide contains two main section: 

- Running the project

   This section includes steps on how to clone the repo and install it locally and also adjusting it to the needed environment.


- Architecture 

   This section includes detailed explanation of the architecture of each directory and how to start developing new components for the dashboard.
