### ISSUE TITLE
incorrect sorting at Dedicated Nodes in MRU

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#185]
At Dedicated Nodes in MRU, sorting in ascending and descending order differs.

![test 24](https://user-images.githubusercontent.com/109473873/184664793-0f0da7a6-b9ff-496a-bec6-fe542ddb2cb4.png)
![test 23](https://user-images.githubusercontent.com/109473873/184664817-496c7b26-9b03-4537-8aee-e2e130fa448d.png)

**Comment by zaelgohary** [comment]
Sorting works fine here. There is a minor difference in the value of the MRU for all dedicated nodes which is not visually seen due to rounding the value. The actual values for the MRU are 188.879455566, 188.874923706, 188.875076294 & 188.875076294.

**Comment by A-Harby** [comment]
Verified on Devnet.
With values having bigger difference sorting logic seems to be working fine.
![image](https://user-images.githubusercontent.com/109473873/193562342-eb549728-609e-428f-b040-6b5f88d6f1f0.png)
![image](https://user-images.githubusercontent.com/109473873/193562391-ec33c68b-a8ad-451f-8ce6-6242c5b451c1.png)

Test steps: [TC811 - Dedicated Nodes Table Sorting](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3631440)
