### ISSUE TITLE
No consistent in data rendered between Dedicated Nodes and Node in Explorer

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#186]
The rendered data for each node in the Dedicated Nodes table does not match the presented data for that node in the Explorer.

Same Node ID (201) with different resource in each.

In `Explorer`
![test 22](https://user-images.githubusercontent.com/109473873/184665916-f344ff6a-365d-4d5c-8edb-ff99d8e93b09.png)
In `Dedicated Nodes`
![test 21](https://user-images.githubusercontent.com/109473873/184665923-4b74356e-6d5a-497e-beca-b6a5ffb979b4.png)

**Comment by ramezsaeed** [comment]
https://github.com/threefoldtech/tfgrid_dashboard/issues/182

**Comment by zaelgohary** [comment]
Tested statistics of node 22 in dedicated nodes & node resources and both are returning the same numbers as shown below.
![image](https://user-images.githubusercontent.com/40770501/186704506-bd0d4e95-54c7-4937-b408-dfe2c97d0ded.png)

![image](https://user-images.githubusercontent.com/40770501/186704596-182a5c19-e8ac-4434-a014-cb638ae89855.png)

**Comment by A-Harby** [comment]
Gb to Tb conversion is correct but shouldn't be there consistency in showing data?
should be 8.1875 TB in both. 
![image](https://user-images.githubusercontent.com/109473873/187066364-4e685ffa-4a15-488f-91fe-a6f0e8f102ed.png)
![image](https://user-images.githubusercontent.com/109473873/187066384-ab8ccec1-184a-4195-9323-367941c43fe5.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The HDD value is now displayed in `TB` in the dedicated nodes table for the sake of consistency.

![image](https://user-images.githubusercontent.com/101194226/187237644-7a80cdb6-ace4-465f-8d80-23c1218f27b2.png)
