### ISSUE TITLE
delete the line for grid versions in both "Farm Details" and "Twin Details" in the explorer

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtecharchive/tfgrid_dashboard#188]
as per discussion with Dylan, this grid version field is something internal and no need to show it to the users.

![Screenshot from 2022-08-16 12-49-08](https://user-images.githubusercontent.com/16083592/184863211-3c139742-6a1b-4e25-8041-a0874e6a0ac8.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

 the `Grid Version` was removed from both the `Farm Details` & `Twin Details`

![image](https://user-images.githubusercontent.com/101194226/187177874-c13e0763-4d87-4c39-9eb4-40a1e863aa81.png)
