### ISSUE TITLE
Nodes show up in wrong country 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtecharchive/tfgrid_dashboard#189]
Node ID 1484 and node ID 855. 

Are both located in the Netherlands, but show up on the dashboard in Sweden. 
Also showing multiple times - see image
![photo_2022-08-17 14 50 36](https://user-images.githubusercontent.com/31733464/185135062-ba3f2169-9ea3-463a-ba8c-5348376e4905.jpeg)

**Comment by MohamedElmdary** [comment]
From graphql these two nodes are located in Sweden not Netherlands
![image](https://user-images.githubusercontent.com/31689104/185156097-705c1f2d-dda8-4119-9b67-8cac9bff85f3.png)

Couldn't reproduce the second issue
![image](https://user-images.githubusercontent.com/31689104/185156047-4772a71f-2ad1-4142-8f52-90fa1f4d5142.png)

**Comment by sabrinasadik** [comment]
User lives in the Netherlands and his nodes are with him..

**Comment by scottyeager** [comment]
I deployed a VM to node 1418 and downloaded the contents of geoip.grid.tf:
```
{"address":"81.172.160.108","country_code":"SE","country_name":"Sweden","subdivision":"Unknown","continent":"Europe","city_name":"Unknown","latitude":59.3247,"longitude":18.056,"source":"maxmind geolite2"}
```

This data is coming from the Maxmind geolite2 database. So I downloaded the latest copy of this database and queried the farmer's IP:

```
>>> with maxminddb.open_database('GeoLite2-Country.mmdb') as reader:
...     reader.get('81.172.160.108')
... 
{'continent': {'code': 'EU', 'geoname_id': 6255148, 'names': {'de': 'Europa', 'en': 'Europe', 'es': 'Europa', 'fr': 'Europe', 'ja': 'ヨーロッパ', 'pt-BR': 'Europa', 'ru': 'Европа', 'zh-CN': '欧洲'}}, 'country': {'geoname_id': 2750405, 'is_in_european_union': True, 'iso_code': 'NL', 'names': {'de': 'Niederlande', 'en': 'Netherlands', 'es': 'Holanda', 'fr': 'Pays-Bas', 'ja': 'オランダ王国', 'pt-BR': 'Holanda', 'ru': 'Нидерланды', 'zh-CN': '荷兰'}}, 'registered_country': {'geoname_id': 2750405, 'is_in_european_union': True, 'iso_code': 'NL', 'names': {'de': 'Niederlande', 'en': 'Netherlands', 'es': 'Holanda', 'fr': 'Pays-Bas', 'ja': 'オランダ王国', 'pt-BR': 'Holanda', 'ru': 'Нидерланды', 'zh-CN': '荷兰'}}}
```

It looks like geoip.grid.tf might be using an outdated version of the geolite2 database.

**Comment by scottyeager** [comment]
Just had a chat with @maxux who owns the geoip repo. He'll update the database, which I expect will resolve this issue.

**Comment by maxux** [comment]
Is it fixed ? Dabase is up to date

**Comment by scottyeager** [comment]
Looks good now.
