### ISSUE TITLE
Rework public config struct

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtecharchive/tfgrid_dashboard#191]
Chain type on devnet changed from:

```js
publicConfig {
   "ipv4": "string",
   "gw4": "string",
   "ipv6": "string",
   "gw6": "string",
   "domain": "string",
}
```

```js
publicConfig {
   "ip4": {
      "ip":"string",
      "gw": "string",
    }
   "ip6": Optional{
      "ip":"string",
      "gw": "string",
    }
   "domain": "OptionalString",
}
```

in the new struct, IP6 and Domain are optional values, they can be set the Undefined (please don't set empty strings for them if the user is not passing those)

Graphql data is still the same

**Comment by mohamedamer453** [comment]
On devnet i tried to add a public config to `node 38` and it was added successfully however when i checked the [grid_proxy](https://gridproxy.dev.grid.tf/nodes/38) after it was added i found out that the domain was the only thing added and the other fields were empty.

![image](https://user-images.githubusercontent.com/101194226/186696241-8dc3291e-0c2a-428b-abf1-58fe88703047.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

i updated the config of `node 38` with the following config 

![image](https://user-images.githubusercontent.com/101194226/187173700-99231bd6-3ae3-40fe-8bd7-6755f5972f52.png)

and after i saved this config it was reflected correctly in the [grid_proxy ](https://gridproxy.dev.grid.tf/nodes/38) with all of the fields set correctly.

![image](https://user-images.githubusercontent.com/101194226/187174010-c28be1ca-9051-468b-a65b-602b3a6cf8af.png)

**Comment by DylanVerstraete** [comment]
@mohamedamer453 does the remove config work as well?

**Comment by mohamedamer453** [comment]
@DylanVerstraete yes it's working, i tried removing multiple configs and it's working fine.

i also now removed the config i added in the comment above and it was removed successfully.



![image](https://user-images.githubusercontent.com/101194226/187175856-f529be3d-f529-49b8-85ae-e75929759bab.png)
