### ISSUE TITLE
Fix uptime and TFT display in minting calendar and receipts

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtecharchive/tfgrid_dashboard#194]
need to update the nodes' summary with the uptime percentage and include the TFTs minted in the minting calendar popup

**Comment by sasha-astiadi** [comment]
@amiraabouhadid screenshot please. and also for now on, if issue regarding improvements on interface / something displayable, please try our best to close iwith screenshot, for product documentation

**Comment by xmonader** [comment]
@sasha-astiadi check the docs here https://github.com/threefoldfoundation/info_manual3/blob/development/wiki/dashboard/portal/dashboard_portal_ui_farming.md
