### ISSUE TITLE
include hub.grid.tf in the dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tfgrid_dashboard#197]
let's see if it works with an iframe

https://github.com/threefoldtech/home/issues/1291

**Comment by A-Harby** [comment]
Couldn't verify as Hub icon of hub.grid.tf directs me to a new tab.
  
![image](https://user-images.githubusercontent.com/109473873/197380348-c9df1bad-e357-4256-9edd-be05dd10963b.png)

**Comment by AhmedHanafy725** [comment]
yes exactly, it didn't work in an iframe (the login didn't work), so it was replaced with a hyperlink to the hub
