### ISSUE TITLE
include bootstrap.grid.tf in the dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tfgrid_dashboard#198]
let's see if works with an iframe

https://github.com/threefoldtech/home/issues/1291

**Comment by mohamedamer453** [comment]
Verified on devnet.

`bootstrap.grid.tf` was added in the dashboard.

![image](https://user-images.githubusercontent.com/101194226/187700173-7130549f-9f9a-4e76-a74f-98e8208d80f3.png)
