### ISSUE TITLE
can't filter the farms from the first time : grid explorer 

### ISSUE THREAD

**Issue by doaasaber** [threefoldtecharchive/tfgrid_dashboard#202]
sometimes when i search it load all the farms first then filter by what i select

[Screencast from 23 أغس, 2022 EET 11:19:32 ص.webm](https://user-images.githubusercontent.com/54359761/186124007-b512bcd6-060d-4306-8e4d-f2795cdbb977.webm)

**Comment by zaelgohary** [comment]
duplicate issue for: https://github.com/threefoldtech/tfgrid_dashboard/issues/28
