### ISSUE TITLE
Panel Staking

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tfgrid_dashboard#203]
parent story: https://github.com/threefoldtech/home/issues/1276
based on the specs https://github.com/threefoldfoundation/tft-stellar/tree/master/specs/l2validatorapplication

It requires:
- supporting threefold login on the dashboard so we can keep track of the username
- new module `L2 Validators`
  - can list validators (by listing balances that can be claimed by `GATFL2VALIDATORAPPLICATIONAAAAAAAAAAAAAAAAAAAAAAAAAAA4TT`
  - can stake tokens by creating a claimable balance when registering application / modifying their application
   

for more detailed expectation in the user experience, please check https://github.com/threefoldfoundation/tft-stellar/tree/master/specs/l2validatorapplication#user-experience

**Comment by amiraabouhadid** [comment]
Blocked, please refer to parent issue: https://github.com/threefoldtech/home/issues/1276
