### ISSUE TITLE
Add a loading spinner on dashboard DAO page

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtecharchive/tfgrid_dashboard#205]
Proposals take time to load, the first few seconds I see nothing

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/tfgrid_dashboard/pull/206

**Comment by mohamedamer453** [comment]
Verified on devnet.

A loading spinner was added to the DAO page.


![TF DASHBOARD (19)](https://user-images.githubusercontent.com/101194226/187414230-f1c6e4a1-aa67-4ffa-9d52-ba0dc9860f55.gif)
