### ISSUE TITLE
Invalid IP is added to Farm 

### ISSUE THREAD

**Issue by doaasaber** [threefoldtecharchive/tfgrid_dashboard#208]
invalid format is added to farm(without /port) the Save button was enabled and I already create it successfully below 
![image](https://user-images.githubusercontent.com/54359761/186692904-9b52a730-8bbe-4a85-a482-9a5d84e65cd0.png)

**Comment by AhmedHanafy725** [comment]
should be verified once deployed on devnet

**Comment by mohamedamer453** [comment]
the issue is still available on devnet 

![image](https://user-images.githubusercontent.com/101194226/187174630-1b3d5292-7267-46d8-a747-1f11be189771.png)

the save button is not disabled when there's an incorrect IP format entered

**Comment by mohamedamer453** [comment]
Verified on devnet.

The `Save` button is now disabled when an invalid IP is entered.

![image](https://user-images.githubusercontent.com/101194226/187248018-5757ea95-5ca3-4c6a-abd7-8ead20c36f3b.png)
