### ISSUE TITLE
Show minting receipts only on mainnet

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtecharchive/tfgrid_dashboard#220]
currently, the minting receipts are only available for mainnet nodes, so we shouldn't show them on the rest nets.

**Comment by mohamedamer453** [comment]
Verified on devnet.

The minting receipts are no longer visible on devnet nodes.

![image](https://user-images.githubusercontent.com/101194226/187431271-4c6c20d7-9949-4c89-9f98-20bebd45169a.png)
