### ISSUE TITLE
Change Get TFT Button on top-right of dashboard when signed in

### ISSUE THREAD

**Issue by samtaggart** [threefoldtecharchive/tfgrid_dashboard#225]
Right now it's just a + sign but it's rather ambiguous.

Please change to Get TFT

Right now it links directly to the TF Connect Sign In Page, also a bad experience

Please link to https://gettft.com/gettft/

**Comment by A-Harby** [comment]
Verified on testnet localhost
Button changed from `+` to `Get TFT`, and directs to [Get TFT](https://gettft.com/gettft/)

![image](https://user-images.githubusercontent.com/109473873/197475302-735a0cb2-0485-4488-977c-de7460a65353.png)

Test steps: [TC853 - Add Balance (Get TFT)](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3632389)
