### ISSUE TITLE
remove account name name

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tfgrid_dashboard#230]
![image](https://user-images.githubusercontent.com/64129/187893732-ed6bad94-43f2-49ab-a8db-f82cae6b67cb.png)

> 
> Kristof De Spiegeleer, [9/1/22 12:30 PM]
> very confusing and not std
> 
> Kristof De Spiegeleer, [9/1/22 12:30 PM]
> there is no point doing a dropdown with always 1 entry whcih can only be 1 entry
> 
> Kristof De Spiegeleer, [9/1/22 12:30 PM]
> if there is a status needs to be on the top
> 
> Kristof De Spiegeleer, [9/1/22 12:30 PM]
> next to how much TFT we have
> 
> Kristof De Spiegeleer, [9/1/22 12:30 PM]
> just portal and then show underneith whats relevant

**Comment by mohamedamer453** [comment]
All of the portal options are now included inside the portal dropdown menu and the extra dropdown with the account name was removed. and the account name was moved to the upper right corner along with a signout button to return to the accounts page.

![image](https://user-images.githubusercontent.com/101194226/187951115-6a1dea41-3889-4f0a-afff-31932a2c22f3.png)

but there are 2 issue the first one is when you close the sidebar while the portal dropdown is expanded, invisible icons appear in the sidebar for the portal options.

and the second one is when you click on the `signout` icon you are returned to the accounts page but the portal options are still visible in the sidebar and when you click on any of them you will be redirected to the page that corresponds to the selected option for the twin that you just signed out from 

[TF DASHBOARD (1).webm](https://user-images.githubusercontent.com/101194226/187952324-a40a100f-4d73-4390-b5ea-f4fabaab638a.webm)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The 2 issues mentioned above were fixed as seen in the video below.

[TF DASHBOARD (2).webm](https://user-images.githubusercontent.com/101194226/187968012-0eef4921-7691-456c-b842-60948e180199.webm)
