### ISSUE TITLE
UI: Theme & Connection icons are hidden under the balance at certain window sizes

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#239]
The Theme and Polkadot connection icons are hidden under the balance at certain window sizes after the name was added to the header.

[TF DASHBOARD (3).webm](https://user-images.githubusercontent.com/101194226/188306530-71d8210d-3b18-496d-9c59-078cef2b606d.webm)

**Comment by A-Harby** [comment]
Additionally, a long name either misses up with the UI or hides buttons.

![image](https://user-images.githubusercontent.com/109473873/188421377-b6ba061f-9b94-440d-8a13-33316909e9dd.png)

![image](https://user-images.githubusercontent.com/109473873/188422421-4e008b03-b50e-449d-8b80-f64f2df8cb7c.png)

**Comment by khaledyoussef24** [comment]
the same problem still exist in qanet and devnet

![Screenshot from 2022-09-18 17-55-53](https://user-images.githubusercontent.com/110984055/190916277-84f10afc-9165-43b3-9681-43db92839487.png)

**Comment by A-Harby** [comment]
Verified on Devnet.

![image](https://user-images.githubusercontent.com/109473873/193463776-ae081267-86e6-4f2e-ab8a-970a2123b1fa.png)

Test steps: [TC792 - Verify Account Visibility (Upper Left)](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3631416)
