### ISSUE TITLE
Verify that farm name is valid

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtecharchive/tfgrid_dashboard#242]
A valid farm name consists of:

- Max 40 asci characters
- No spaces
- Only `-`, `_` are allowed as special character

**Comment by mohamedamer453** [comment]
Verified on devnet.

- Min length

![image](https://user-images.githubusercontent.com/101194226/188917710-6e6d3a27-ca13-47e6-8d93-3e1000f6acfd.png)

- Max length

![image](https://user-images.githubusercontent.com/101194226/188916263-4101ec05-0ada-4c67-9245-78398b59db10.png)
 
- No spaces

![image](https://user-images.githubusercontent.com/101194226/188916708-7261c343-1cdb-447e-b2ae-f5acb0b96e4c.png)

- Only `-`,`_` are allowed

![image](https://user-images.githubusercontent.com/101194226/188916898-cd24b29f-a654-4c1a-bde1-4a48a842c8d3.png)

![image](https://user-images.githubusercontent.com/101194226/188917497-9fd9b0e9-4cc9-4b8d-9e1a-6f8b195994fe.png)

![image](https://user-images.githubusercontent.com/101194226/188917641-ad174257-d590-403c-9007-3edddfd13ef3.png)

**Comment by A-Harby** [comment]
[TC821 - Farms Input validation](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3631461)
