### ISSUE TITLE
When creating or editing IP twins, validation is incorrect.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#243]
Planetary using Yggdrasil IPV6 is the format to use for creating or editing IP, however input allows these values, 
But twin creation/update fails after submission.

![image](https://user-images.githubusercontent.com/109473873/188429850-f88aebc1-d0bb-4eb3-9306-201c066949d8.png)

![image](https://user-images.githubusercontent.com/109473873/188430163-cb71db8e-2fd7-4b8b-b13f-a7858dc541b1.png)

**Comment by A-Harby** [comment]
Validation isn't updated in creating twin IP 
![image](https://user-images.githubusercontent.com/109473873/194023291-2b35a5cc-b6b5-4a90-8f87-afcf66dfe880.png)

And in edit twin IP, last group accepts 5 digits
![image](https://user-images.githubusercontent.com/109473873/194025669-f34e2203-6114-4d96-bf64-75078ddc53a5.png)

**Comment by maayarosama** [comment]
I'm trying to come up with a regex that doesn't accept all invalid format for the twin IP, @zaelgohary will be helping me with this issue.

**Comment by maayarosama** [comment]
Known issues:
current regex validates most forms of IPV6, however, it accepts some invalid formats as well such as:
- ::12345
- ::123456

regex will be accepted for now until finding a better solution.

**Comment by A-Harby** [comment]
All other cases are fixed expect for ::12345.

But should IPV6 accept subnet @maayarosama ?
![image](https://user-images.githubusercontent.com/109473873/196386933-2b64e7b3-bc82-43d9-9ade-1ee6e2ae6a04.png)

**Comment by A-Harby** [comment]
Subnet is an invalid IPV6 format.
 
![image](https://user-images.githubusercontent.com/109473873/196936260-2e36ab71-3842-4c69-ae49-f5f639dd06ca.png)

Test step: [TC797 - Create a Twin](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3631421) - [TC798 - Edit Twin](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3631423)
