### ISSUE TITLE
Decimals validation in Withdraw TFT and Transfer TFT

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#244]
Withdraw TFT and Transfer TFT alerts for more than three decimal places, but allow decimals values in E format in `Amount (TFT)` input.

When submit, button keeps loading. 
![image](https://user-images.githubusercontent.com/109473873/188466948-0bd6c52b-ab23-4275-9456-a5326a8a844f.png)

in transfer TFT.
![image](https://user-images.githubusercontent.com/109473873/188469052-6c208e5d-ddde-4e2b-aac2-c7b230ddd440.png)

**Comment by zaelgohary** [comment]
The amount input accepts numbers only in both cases and doesn't enable the user to enter values in E format.

**Comment by A-Harby** [comment]
True, it just accepts only numbers, but it is doable through copy and paste.

**Comment by khaledyoussef24** [comment]
verified now it only accepts up to 3 decimals only.
![Screenshot from 2022-09-19 06-39-33](https://user-images.githubusercontent.com/110984055/190950914-751713f8-cd51-4b13-896c-14d985ccc665.png)

**Comment by A-Harby** [comment]
[TC819 - Swap TFT Input validation](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3631459)
