### ISSUE TITLE
Name validation in create farm 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#245]
There isn't any alerts on having wrong farm name format but when trying to create farm in most cases, it keeps fail without telling the reason.

![image](https://user-images.githubusercontent.com/109473873/188470742-692702ca-9cc4-4fe0-b2b5-78dac6cc962d.png)

![image](https://user-images.githubusercontent.com/109473873/188471747-4015ea19-e46a-456a-ad5b-2520e1508952.png)

**Comment by ramezsaeed** [comment]
please also update the docs with all in for about how the name should be

**Comment by ramezsaeed** [comment]
follow up here: 
https://github.com/threefoldtech/tfgrid_dashboard/issues/242
