### ISSUE TITLE
Validation in Add a public config to your node

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#247]
Validation isn't working.

![image](https://user-images.githubusercontent.com/109473873/188487975-1ab4b1bb-a02b-4e9c-a8f6-46e7bcfc96bf.png)

**Comment by ramezsaeed** [comment]
@A-Harby 
did u tried to add it with size less than max ?

**Comment by A-Harby** [comment]
Qanet, V 3.7.0

Yes, and it works, but not in most cases.
![image](https://user-images.githubusercontent.com/109473873/188597589-62156830-cf8b-42ab-a1bf-1da1deb0004e.png)

**Comment by zaelgohary** [comment]
@A-Harby How to recreate this issue? I don't have any nodes displayed in the dashboard.

**Comment by amiraabouhadid** [comment]
@A-Harby domain is not a required field so I am not sure what the validation issue is?

**Comment by A-Harby** [comment]
Still accept wrong input (ex. ::12345/64)
![image](https://user-images.githubusercontent.com/109473873/193465679-4551efc3-37ea-42c5-92ed-0727d0557e9a.png)

**Comment by maayarosama** [comment]
fixed with some known issues:
current regex validates most forms of IPV6, however, it accepts some invalid formats as well such as:
- ::123456
- ::12345

regex will be accepted for now until finding a better solution.

**Comment by A-Harby** [comment]
Verified.
IPV6 validation works fine except for ::12345 

![image](https://user-images.githubusercontent.com/109473873/197384276-6b773327-1cc1-4dc3-b2e5-d2a165b559ef.png)

Test steps: [TC862 - Public Config Input Validation.](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3651071)
