### ISSUE TITLE
Hide Node Uptime Percentage on Dev and Qa net

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtecharchive/tfgrid_dashboard#250]
since the farm node uptime percentage relies on the uptime collected from the minting receipts on mainnet divided by the uptime fetched from gridproxy/ graphql, the uptime percentage needs to be hidden on networks other than mainnet

**Comment by mohamedamer453** [comment]
Verified on devnet.

The node uptime is not visible anymore.

![image](https://user-images.githubusercontent.com/101194226/188914565-882ca5da-e87c-45bb-bcd6-41b4b567efef.png)
