### ISSUE TITLE
Nodes table: status sorting is not working

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#257]
### Description 

The status column in the nodes table is not working.

### Steps to Reproduce

- Navigate to https://dashboard.qa.grid.tf/
- Click on you account and navigate to the farms page.
- In the nodes table try to sort the `Status` column 

![sort](https://user-images.githubusercontent.com/41957921/189140067-4a04a781-20a9-4da8-bef8-a7af824e7fed.gif)

**Comment by khaledyoussef24** [comment]
### verified 
**steps made to verify**

1. Navigate to https://dashboard.qa.grid.tf/
2. Click on you account and navigate to the farms page.
3. In the nodes table try to sort the Status column
4. tables are sorted correctly ascending descending and back to normal
[Screencast from 10-30-2022 03:57:17 PM.webm](https://user-images.githubusercontent.com/110984055/198883044-5fbf74f9-1cc1-4f18-ab1d-c9c94b7e59e2.webm)

**Comment by A-Harby** [comment]
Verified on Devnet.

`Status` sorting is now working.
![image](https://user-images.githubusercontent.com/109473873/200836867-c02b98df-fc12-4d09-ba1b-74bce5141e6b.png)
![image](https://user-images.githubusercontent.com/109473873/200836949-6bcfafc6-8c07-4316-a6e9-82488bd4fe0c.png)

Test steps: [TC865 - Farm Nodes Table Sorting](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3651076)
