### ISSUE TITLE
UI: Add a loading bar for the dedicated nodes table

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#258]
### Description 

Add a loading bar for the dedicated nodes table instead of showing `No Data Available` for a second before the data loads.

![TF DASHBOARD (23)](https://user-images.githubusercontent.com/101194226/189531682-fc53ea34-d21c-492e-b5d1-7fa14240647e.gif)

**Comment by A-Harby** [comment]
Verified on Devnet.
A loading bar has been added until the data has been loaded.

![image](https://user-images.githubusercontent.com/109473873/193465837-1eb9473e-6906-441d-b46c-fbbe85998642.png)

Test steps: [TC809 - List Dedicated Nodes](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3631437)
