### ISSUE TITLE
UI: Adjust the loading spinner of the Add IP button

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#259]
### Description

The size of the loading spinner of the `Add IP` button needs to be adjusted since it's bigger than the button as seen in the video below. and also the same loading spinner doesn't disappear when the transaction is cancelled. there also should be a message mentioning that the transaction was cancelled/failed like the rest of the dashboard functions.

[Untitled_ Sep 11, 2022 4_20 PM.webm](https://user-images.githubusercontent.com/101194226/189532803-2f1094a2-effe-43ed-82ca-c75fc992b321.webm)

**Comment by A-Harby** [comment]
Verified on Devnet.
Loading icon size now is smaller than button size.

![Screenshot from 2022-10-02 20-34-32](https://user-images.githubusercontent.com/109473873/193470349-59364120-c6cb-423c-8e04-b289e2f1e9a2.png)

Test steps: [TC805 - Add IP to Farm](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3631433)
