### ISSUE TITLE
UI: Add public ip range validation is activated before typing anything

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#260]
### Description

The input validation of the `To IP` field in the `Add IP Range` tab is activated by default even before the user enters anything in the field.

![TF DASHBOARD (24)](https://user-images.githubusercontent.com/101194226/189533520-b05ad444-9431-495f-8f34-0c83b193a2af.gif)

**Comment by A-Harby** [comment]
The input validation of the `To IP` field in the Add IP Range tab is not activated until user start typing
![image](https://user-images.githubusercontent.com/109473873/196401912-c68ad687-0e85-44ed-8415-d14e08441d19.png)

Test steps: [TC1151 - Add Multiple IPs to a Farm](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3714618)
