### ISSUE TITLE
explorer is too slow

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tfgrid_dashboard#261]
listing nodes, filtering on mainnet dashboard.grid.tf

**Comment by A-Harby** [comment]
Listing was faster than berfore, but found a few issue regrading filtering and listing the nodes.

https://github.com/threefoldtech/tfgrid_dashboard/issues/304
https://github.com/threefoldtech/tfgrid_dashboard/issues/303
https://github.com/threefoldtech/tfgrid_dashboard/issues/302

**Comment by Omarabdul3ziz** [comment]
please check the comments on each issue.

**Comment by A-Harby** [comment]
Verified on Devnet.

listing nodes are noticeable faster than before and better. 
Filter issue are fixed except(https://github.com/threefoldtech/tfgrid_dashboard/issues/304) and being fixed.

Test steps:: [TC824 - Explorer should show Nodes](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348399#case_3631891)
