### ISSUE TITLE
Validate that Stellar addresses are active and have trustline

### ISSUE THREAD

**Issue by scottyeager** [threefoldtecharchive/tfgrid_dashboard#263]
Whenever there's a Stellar address input field, there should be validation that the address is active and has a trustline established to TFT. This was [present](https://github.com/threefoldtech/tfchain_portal/blob/b6eea83ff79ef67a783fb5cfdd16f0b92f3a4679/src/components/farms/createV2Address.vue#L84) in the portal when adding Stellar payout addresses to farms. The interface to swap (bridge) TFT should also have this functionality.

**Comment by DylanVerstraete** [comment]
Yes please, because this can cause issues with the bridge code itself

**Comment by khaledyoussef24** [comment]
verified on devnet
steps made
1. open dashboard
2. choose the user
3. go to swap
4. go to withdraw
5. try to put an invalid address it won't work even if it is the same length of the address
 
![Screenshot from 2022-09-19 06-18-13](https://user-images.githubusercontent.com/110984055/190949823-4c0ec89d-b401-432c-b970-3fd65dac092a.png)

6. try to put a validated address from TF connect it will work fine
![image](https://user-images.githubusercontent.com/110984055/191052911-25af225b-2541-4607-adfe-1af81a112cd3.png)

**Comment by A-Harby** [comment]
[TC819 - Swap TFT Input validation](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3631459)
