### ISSUE TITLE
Sorting errors on the `Nodes` page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#267]
Nodes listed only display 7 nodes on the first page, with duplicate nodes appearing on following pages.

## Steps to reproduce:
- Navigate to dashboard 
- Open a twin and navigate through its pages
- Navigate to Nodes
- Sort using ID

![image](https://user-images.githubusercontent.com/109473873/189943117-215dfdf0-5747-4f93-8ee5-250ce9ed5fd6.png)
![image](https://user-images.githubusercontent.com/109473873/189943250-b553fcce-c4b3-4a69-b64c-6f67c8fcac8f.png)

**Comment by A-Harby** [comment]
[TF DASHBOARD.webm](https://user-images.githubusercontent.com/109473873/196033914-8eb3770b-36a9-4f4b-aee3-2f42a6c89b02.webm)

**Comment by zaelgohary** [comment]
Tried to reproduce the issue but sorting seems to be working well.

[dashboard.webm](https://user-images.githubusercontent.com/40770501/196793022-b9d83fc3-211d-4e7b-b920-d1511a3e31b3.webm)

**Comment by A-Harby** [comment]
Steps to reproduce:
1. Navigate to dashboard
2. Open a twin 
3. navigate to Nodes
4. Navigate back to any twin page
5. Navigate to Nodes again
6. Sort using ID

Always waiting for the issue https://github.com/threefoldtech/tfgrid_dashboard/issues/261 to be done, to see if it is still reproducible.

**Comment by zaelgohary** [comment]
@A-Harby I think the PR for https://github.com/threefoldtech/tfgrid_dashboard/issues/261 is ready for review.

**Comment by A-Harby** [comment]
Discovered a few issues with PR, included an issue with sorting the nodes, so I was unable to reproduce current issue.

**Comment by AhmedHanafy725** [comment]
sorting is removed from this table
