### ISSUE TITLE
Invalid input for amount (TFT) without warning 

### ISSUE THREAD

**Issue by doaasaber** [threefoldtecharchive/tfgrid_dashboard#268]
I entered an invalid amount TFT(0.046--), the system didn't display the warning, and the submit button was enabled.
 I tried to click on the submit button and it was about to complete the process.
![image](https://user-images.githubusercontent.com/54359761/190008114-3158fd03-e88a-4c17-875e-276162ac1dd8.png)

**Comment by zaelgohary** [comment]
fixed [here](https://github.com/threefoldtech/tfgrid_dashboard/issues/244).

**Comment by A-Harby** [comment]
[TC819 - Swap TFT Input validation](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3631459)
