### ISSUE TITLE
Removing Node Public Config fails

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#269]
### Description 

When i try to remove the public config of a node it fails with no specific reason and the config is removed from the UI but when i close the modal box and reopen it, the config appears again.

[TF DASHBOARD (4).webm](https://user-images.githubusercontent.com/101194226/190136608-47859d33-7907-4199-be81-01ccbe3614b6.webm)

**Comment by rawdaGastan** [comment]
It won't fail anymore but there is still an issue syncing with graphql (not related to the dashboard)

**Comment by A-Harby** [comment]
Still same issue can't verify, can't update IPV4, gateway values or even adding IPV6, gateway values.

> It won't fail anymore but there is still an issue syncing with graphql (not related to the dashboard)

**Comment by A-Harby** [comment]
Adding and removing public config is working fine now.

Test steps: [TC863 - Add Public Config](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3651073) - [TC864 - Remove Public Config](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3651074)
