### ISSUE TITLE
Nodes show down in portal until page refresh

### ISSUE THREAD

**Issue by scottyeager** [threefoldtecharchive/tfgrid_dashboard#277]
Farmers report that sometimes their nodes appear down in the portal section of the dashboard until the page is refreshed. The same node will appear up in the explorer section and did not in fact go offline. See report here: https://forum.threefold.io/t/farm-down-in-dashboard/3347/2

**Comment by rkhamis** [comment]
This could be an issue of timing. The explorer updates the node status' every 2 hours while the portal updates every 3 hours. i't's possibly just bad timing to be between updates.

**Comment by xmonader** [comment]
I believe the best course of action is to request an invalidation of the grid proxy's cache.

If, for example, the node details page indicates that it is online but the listing indicates that it is offline (as a result of caching results), I would immediately send a request to the grid proxy to invalidate the cache, such as `/node/:id/invaldiate-cache`, so that all future requests would reflect the node's semi-realtime status.

**Comment by xmonader** [comment]
As it seems there's no caching happening anymore on the grid_proxy, the core problem is the node uptime is calculated hourly on the chain indicating the node status online/offline.

What I suggest as a last resort, is for a user they get the nodes (the node might be offline based on the last uptime report) when the user click on the details they find the real status (online/offline), the explorer, should at this point maintain a local cache of the conflicting nodes' status and patch them in the upcoming `/nodes` requests


another option maybe if we just show 10 nodes per page we can compose a check_online call and update immediately the returned data

**Comment by AhmedHanafy725** [comment]
as per the discussion with the team, we will get the real-time status from the node itself on the gridproxy https://github.com/threefoldtech/tfgridclient_proxy/issues/202
and for the dashboard, it should show the status coming from the gridproxy without any computations.

**Comment by maayarosama** [comment]
The nodes' data are adjusted now to come from the grid proxy but I'm still waiting for the Serial Number field to be added to it.

**Comment by Omarabdul3ziz** [comment]
gridproxy issue https://github.com/threefoldtech/tfgridclient_proxy/issues/208

**Comment by A-Harby** [comment]
Verified on Devnet.

In portal, node uptime are now being fetched from the grid proxy.
![image](https://user-images.githubusercontent.com/109473873/200880922-d644664e-ee1c-447e-8829-3814adae7830.png)
And in explorer, Node uptime are being fetched from the grid proxy if u expanded the node.
![image](https://user-images.githubusercontent.com/109473873/200881478-a560dac2-64aa-42da-a4c0-2f9b715cad7f.png)

And message clearly states to expand node for real time updates.
![image](https://user-images.githubusercontent.com/109473873/200881698-4cf7b988-fefd-40b3-b067-954dea3b9a59.png)

Test steps: [TC860 - Verify Node Stats](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3651069) - [TC824 - Explorer should show Nodes](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348399#case_3631891)
