### ISSUE TITLE
Adding version env var

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtecharchive/tfgrid_dashboard#284]
Adding version to each release to differentiate the released net

**Comment by A-Harby** [comment]
The version isn't displayed on the loaclhost,
Should it not be visible on the localhost @zaelgohary ?

![image](https://user-images.githubusercontent.com/109473873/196403974-0507ab28-31cd-4f44-8068-fa90b97b1013.png)

**Comment by zaelgohary** [comment]
@A-Harby It would work on localhost only if you exported the VERSION yourself or you can test it by installing the helm chart. I added "no version provided" in case no version was returned.

**Comment by A-Harby** [comment]
Verified on Devnet.

Versions are the same
![image](https://user-images.githubusercontent.com/109473873/199681138-ec15a539-cc90-4b4b-9188-aa8cf3804556.png)
![image](https://user-images.githubusercontent.com/109473873/199681522-362bf36f-8605-44fa-99d1-2929b25d05ec.png)
