### ISSUE TITLE
Explorer: `HRU` filter is not working correctly

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#285]
### Description

The `HRU` filter in the nodes page is not working correctly. for example when the minimum is set to `6TB` it shows nodes that have `5TB` hru 

![image](https://user-images.githubusercontent.com/101194226/192146797-4fb3a097-f793-45bc-9954-b7e5d7490054.png)

and when it's set to `9TB` it shows nodes with `8TB`

![image](https://user-images.githubusercontent.com/101194226/192146925-16017843-5133-461e-8aec-ecadb9d7f35a.png)

and when it's set to `16TB` it shows nodes with `15TB`

![image](https://user-images.githubusercontent.com/101194226/192146962-f6273ac9-a60d-45db-a731-268ed73c6b2e.png)

**Comment by A-Harby** [comment]
https://github.com/threefoldtech/tfgrid_dashboard/issues/304
Also can't verify as slide bar is removed.

**Comment by AhmedHanafy725** [comment]
closing as the sorting is removed from the nodes' tables
