### ISSUE TITLE
Filtering farms by certification type fails

### ISSUE THREAD

**Issue by scottyeager** [threefoldtecharchive/tfgrid_dashboard#293]
I've tried to list only gold certified farms by using the farms section of the explorer, but all farms remain visible:

![image](https://user-images.githubusercontent.com/17682591/195710566-6751a3d3-c7e6-4aa9-bb5f-0420260c5222.png)

**Comment by A-Harby** [comment]
Verified on localhots version, using mainnet.
![image](https://user-images.githubusercontent.com/109473873/197379697-4882b527-df5c-405d-a075-abbc9928a406.png)

Test steps: [TC845 - Filter Farms by Certification Type](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348399#case_3632201)
