### ISSUE TITLE
certification status isn't shown up in the explorer

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tfgrid_dashboard#294]
A few certified nodes dont show the certification status on explorer

![photo_2022-10-11_17-29-01](https://user-images.githubusercontent.com/91247662/195099867-a288910e-92c3-4c71-b5a5-1eee288a59c0.jpg)

**Comment by A-Harby** [comment]
Verified on mainnet.
Certification type now displays either Certified or DIY.

![image](https://user-images.githubusercontent.com/109473873/197380610-2c4c7d6d-3459-46f0-9c8b-46a171345823.png)
![image](https://user-images.githubusercontent.com/109473873/197380914-c82014cf-a99f-4348-8784-bf34a6f34cde.png)
![image](https://user-images.githubusercontent.com/109473873/197381160-6ae36fa4-7942-414e-bb17-e81acf8ed8af.png)

Test steps: [TC832 - Show Node Infromation](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348399#case_3631924)
