### ISSUE TITLE
Format in IPV6 in add a public config to your node

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#301]
When I try to add IPV6 using the format specified, `IPV6 address in CIDR format x:x:x:x`, it keeps failing unless I add a subnet to it.
![image](https://user-images.githubusercontent.com/109473873/196416394-0f81c767-e89f-4062-9f67-647fa5b77b11.png)

**Comment by A-Harby** [comment]
Verified on Devnet.

Message hint still incorrect, IPV6 should have a subnet to be added.
![image](https://user-images.githubusercontent.com/109473873/200837797-18876227-a2d9-4437-8258-b988d144922b.png)
![image](https://user-images.githubusercontent.com/109473873/200839700-c11f26c8-c8dc-4430-84fe-19d983b8adc8.png)
![image](https://user-images.githubusercontent.com/109473873/200839870-d63ac89f-2978-4ac0-b930-f372f3495d67.png)

Test steps: [TC863 - Add Public Config](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3651073)

**Comment by zaelgohary** [comment]
> Verified on Devnet.
> 
> Message hint still incorrect, IPV6 should have a subnet to be added. ![image](https://user-images.githubusercontent.com/109473873/200837797-18876227-a2d9-4437-8258-b988d144922b.png) ![image](https://user-images.githubusercontent.com/109473873/200839700-c11f26c8-c8dc-4430-84fe-19d983b8adc8.png) ![image](https://user-images.githubusercontent.com/109473873/200839870-d63ac89f-2978-4ac0-b930-f372f3495d67.png)
> 
> Test steps: [TC863 - Add Public Config](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3651073)

The test case does not match the mentioned format.

**Comment by A-Harby** [comment]
> The test case does not match the mentioned format.

So either the message or the validation are incorrect.

Because although the message indicates that the format shouldn't have a subnet, the inputs do.
![image](https://user-images.githubusercontent.com/109473873/200856796-5d874fda-8739-487f-bf0e-67111738d3f6.png)

**Comment by zaelgohary** [comment]
It was agreed that the current IP validation is the best solution found and will be used until we find a better one. The hint is used not to confuse the user with other formats.
