### ISSUE TITLE
`No data available` in listing nodes 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#302]
Keep getting `No data available` when trying to list `all` nodes.

![image](https://user-images.githubusercontent.com/109473873/196418295-740f3238-689a-4638-95ed-081dd261fd86.png)

**Comment by Omarabdul3ziz** [comment]
the gridproxy request query for the size is generated with `&size=${rowsPerPage}` so selecting the `all` option will create an invalid query and that is why it gets `No data available`.

a fix for that will be by editing the `footer-props` in the `v-data-table` to not list `All` as an option

**Comment by A-Harby** [comment]
Verified on Devnet.

Now user have choice of showing 5, 10, 15 or 50.
![image](https://user-images.githubusercontent.com/109473873/199777219-47436d2a-001d-4f1f-bbbc-f564527359ad.png)

Test steps: [TC824 - Explorer should show Nodes](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348399#case_3631891)
