### ISSUE TITLE
Sorting isn't working in nodes

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#303]
Can't sort nodes in nodes table using any column. 
Ascending is the same as descending, Nothing changes. 
![image](https://user-images.githubusercontent.com/109473873/196425392-72e9741b-42b5-498a-b106-528e7313e4a5.png)
![image](https://user-images.githubusercontent.com/109473873/196425453-e140132a-047b-40d0-ae1e-3eaa13d39e78.png)
![image](https://user-images.githubusercontent.com/109473873/196425227-4db23005-75c7-4793-bbdf-8f15867626aa.png)

**Comment by Omarabdul3ziz** [comment]
default sorting will not work with `server-items-length`. the prop used to view the length of all nodes count and enable paginations.
so the sort should be implemented in grid proxy.
- https://github.com/threefoldtech/tfgrid-sdk-go/issues/53

node sorting is disabled for now. till it is implemented in grid proxy

**Comment by A-Harby** [comment]
Verified on Devnet.

Sorting is now disabled.
