### ISSUE TITLE
Portal tab get stuck  (after some navigation) and do not display options anymore

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtecharchive/tfgrid_dashboard#315]
https://user-images.githubusercontent.com/31689104/197396815-c1456663-03a1-4410-96df-ec39be53a516.mp4

**Comment by renauter** [comment]
I had exactly the same experience on Brave
Just to reinforce ;)

**Comment by sabrinasadik** [comment]
Dashboard is on v1.4 but still not fixed

**Comment by A-Harby** [comment]
Couldn't reproduce the issue on Devnet, v1.4.0-rc8 however I tried to navigate between portals pages and Explorer pages, But face another issue with navigation links https://github.com/threefoldtech/tfgrid_dashboard/issues/587
