### ISSUE TITLE
UI Polka connect button 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#317]
The Polka connect/disconnect button doesn't seem to be a button that can be pressed; rather, it looks more like a connection status label.

And can button icon be in equal sizes, button position keep changes left and right cause of it.
![image](https://user-images.githubusercontent.com/109473873/197483496-1ade0532-8b94-4afe-b538-ef49c7ad7540.png)
![image](https://user-images.githubusercontent.com/109473873/197483424-c7f51860-2f61-4ab8-84a7-24d8d3da370f.png)

**Comment by zaelgohary** [comment]
@A-Harby Would it be better if the icon is replaced with a connect/disconnect button? (connect in case it's disconnected & vice versa)

**Comment by A-Harby** [comment]
Yes @zaelgohary , that would be much better, but the button must be clearly identifiable as a button (Like having a border or hovering animation or smth similar), Also having it in a switch format would be more clear to the user.

**Comment by khaledyoussef24** [comment]
### verified 
the connect button is now visible and it's more efficient than the icon
 can we add colors too? like green button if connected and red if disconnected so it can be easily visually tracked ?
![Screenshot from 2022-10-31 09-31-58](https://user-images.githubusercontent.com/110984055/198955457-ef7e41f4-0630-45e8-9197-7a4a68c263dc.png)
![Screenshot from 2022-10-31 09-31-53](https://user-images.githubusercontent.com/110984055/198955461-5f5cfd2a-9f69-4cbe-85b9-44ceeba12d0a.png)

**Comment by zaelgohary** [comment]
You mean like this?
![disconnect](https://user-images.githubusercontent.com/40770501/198962831-2543de2f-f22a-42e1-bcad-9eead8fcdf76.png)

![connect](https://user-images.githubusercontent.com/40770501/198962810-17f84b03-a659-4e21-aa85-74a63fbd82af.png)

**Comment by khaledyoussef24** [comment]
Yes, It will be much better and easily visualized

**Comment by A-Harby** [comment]
Verified on Devnet.

buttons are easily recognized as a buttons and have colours.
![image](https://user-images.githubusercontent.com/109473873/200857418-c2a131e1-525c-4d09-98c7-d12a83b8dc5d.png)
![image](https://user-images.githubusercontent.com/109473873/200857354-2683955c-4493-4ebc-8326-89c1b5004a56.png)

Test steps: [TC796 - Disconnect/Reconnect from Polkadot](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3631420)
