### ISSUE TITLE
Add status column to nodes' table

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtecharchive/tfgrid_dashboard#32]
show the node's status in a new column in the nodes' table like the unified explorer

![image](https://user-images.githubusercontent.com/41957921/171616655-1e796d4f-044c-4280-9b29-09422ce7fc18.png)

**Comment by mohamedamer453** [comment]
Verified.

Node status column was added.

![image](https://user-images.githubusercontent.com/101194226/183286017-02817b62-f89b-4c92-87eb-b924a43ecbc4.png)
