### ISSUE TITLE
How much discount the user will get for a dedicated node is not shown

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtecharchive/tfgrid_dashboard#320]
![image](https://user-images.githubusercontent.com/41957921/197536496-e3a45a37-2647-4fcb-93c3-4d4ca3ba69cb.png)

**Comment by khaledyoussef24** [comment]
### verified

steps made to verify 
1-go to dashboard
2-go to portal from side menu
3-choose dedicated node
4-hover over the price
5-check if the How much discount the user will get for a dedicated node is shown
![Screenshot from 2022-10-30 11-50-24](https://user-images.githubusercontent.com/110984055/198872690-2a6f2552-fac3-40c1-8744-305a50991b44.png)
