### ISSUE TITLE
fix circular progress display when there is no quantity

### ISSUE THREAD

**Issue by renauter** [threefoldtecharchive/tfgrid_dashboard#321]
When there is no quantity to measure progress or percentage we now see the following:  

![Screenshot from 2022-10-25 09-15-39](https://user-images.githubusercontent.com/73958772/197799958-a58b6295-4a98-40ae-8696-45c4063d2800.png)

The expected is that it should be all gray.
Also `0/0` could be replaced by something more explicit like `NA` or `N/A` for "not available"

Not an expert but it can be fixed here

https://github.com/threefoldtech/tfgrid_dashboard/blob/db4aead1dc52ecb259359d59d85677c463fd7668/src/portal/components/FarmNodesTable.vue#L230

https://github.com/threefoldtech/tfgrid_dashboard/blob/db4aead1dc52ecb259359d59d85677c463fd7668/src/portal/components/FarmNodesTable.vue#L873

Should be applied for all other `v-progress-circular` objects I guess

**Comment by 0oM4R** [comment]
I just fixed this issue on explorer, I'm stuck on how to access the portal, but by Sunday it will be fixed.
![Screenshot from 2022-10-28 15-54-22](https://user-images.githubusercontent.com/62248851/198626608-8efa5dd6-33d8-42b6-a873-edd17e0b4c1a.png)

**Comment by A-Harby** [comment]
@0oM4R not sure if it's relatable to your PR but check this [issue](https://github.com/threefoldtech/tfgrid_dashboard/issues/346)

**Comment by A-Harby** [comment]
Verified on Devnet.

circular progress display shows gray circle and `NA`. 
![image](https://user-images.githubusercontent.com/109473873/200871871-0c134988-1ce4-4bfc-8b20-1b68520e9b8a.png)
 
Test steps: [TC860 - Verify Node Stats](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3651069)
