### ISSUE TITLE
Update node uptime percentage to use only API fetched values

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtecharchive/tfgrid_dashboard#322]
parent: https://github.com/threefoldtech/tfgrid_dashboard/issues/366
Fix the node uptime percentage formula to use only the uptime since the start of the month fetched from API instead of using gridproxy/ graphql uptime to avoid nonsensical uptime percentages when nodes are rebooted and gridproxy/graphql node uptime is reset to 0.

**Comment by mohamedamer453** [comment]
Parent issue was verified in https://github.com/threefoldtech/tfgrid_dashboard/issues/366#issuecomment-1323878588 on mainnet.
