### ISSUE TITLE
Filter nodes by farm name

### ISSUE THREAD

**Issue by scottyeager** [threefoldtecharchive/tfgrid_dashboard#323]
Currently, filtering by farm can only be done according to farm id in the Explorer > Nodes section. To find all nodes in a farm with a given name, one must first search the farms for farm id, then filter nodes by that farm id.

_Desired feature:_
Filter nodes by farm name directly in the nodes view.

**Comment by khaledyoussef24** [comment]
### verified on devnet

filtering by farm name is now available on devnet

steps made to verify:

1. open the dashboard
2. open the side menu
3. go to explorer
4. go to farms
5. go to filter by farm name
6. insert name
7. click apply

[Screencast from 11-29-2022 05:18:40 PM.webm](https://user-images.githubusercontent.com/110984055/204569007-a352b800-f9ed-4a3a-b0f9-732e3ff37bc8.webm)

**Comment by A-Harby** [comment]
Verified on Devnet, v1.3.0-rc1.
Farm name filter is added, can filter with non sensitive cases successfully.
![image](https://user-images.githubusercontent.com/109473873/204568285-4399060f-c72f-457a-a5a3-1104addd1737.png)

Test steps: [TC1411 - Filter Nodes by Farm Name](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348399#case_3794573)

**Comment by scottyeager** [comment]
Also tested myself, and it works great. Thanks team.
