### ISSUE TITLE
SRU now rounds to whole TB

### ISSUE THREAD

**Issue by scottyeager** [threefoldtecharchive/tfgrid_dashboard#329]
Farmers have noticed since the 3.7 update that the mainnet dashboard shows their SRU figures rounded to the whole TB. For example:

![image](https://user-images.githubusercontent.com/17682591/198142925-1bf3a550-d913-455e-b298-c6697fcbfdcc.png)

This makes it difficult to tell if smaller capacity additions have been picked up by Zos, if it doesn't bump to the next whole number.

Can we have at least one decimal place of accuracy in these figures?

**Comment by A-Harby** [comment]
Verified on Devnet.

Values are shown in a single decimal format if the node stats are in GB.
![image](https://user-images.githubusercontent.com/109473873/200866570-3249df7b-d394-457e-959f-96c2a744e362.png)
![image](https://user-images.githubusercontent.com/109473873/200866626-a34d364d-4376-48cb-8ad4-d78ff4a75b5c.png)

Test steps: [TC810 - Verify Dedicated Nodes Resources](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3631439)
