### ISSUE TITLE
update the status note in the nodes listing

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tfgrid_dashboard#334]
![image](https://user-images.githubusercontent.com/64129/198872446-4fa43873-e0e8-489e-bdca-3c20e675c1c5.png)

Update with: 

`For a realtime status, please click on the row`

**Comment by A-Harby** [comment]
Verified on Devnet.

Status message updated.
![image](https://user-images.githubusercontent.com/109473873/199776144-bd0a8cdb-abc0-477b-b6db-1ecf6f1b1e2b.png)

Test steps: [TC824 - Explorer should show Nodes](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348399#case_3631891)
