### ISSUE TITLE
Wrong node ID in editing the nodes' public config

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtecharchive/tfgrid_dashboard#342]
![image](https://user-images.githubusercontent.com/41957921/199022381-a7cfdd73-fafd-465d-b793-3eead5bf9000.png)

**Comment by A-Harby** [comment]
Verified on Devnet.

Node ID is displayed now.
![image](https://user-images.githubusercontent.com/109473873/200867861-63cba274-055c-40dc-9ecd-f6f2e55ca483.png)

Test steps: [TC863 - Add Public Config](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3651073)
