### ISSUE TITLE
Remove the interface id field from the nodes' details 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtecharchive/tfgrid_dashboard#350]
it's just an id in the DB that doesn't mean anything

![image](https://user-images.githubusercontent.com/41957921/199252271-75eb531d-819a-4d80-891e-6c10bc61b6aa.png)

**Comment by A-Harby** [comment]
Verified on Devnet.

the interface id field is removed.
![image](https://user-images.githubusercontent.com/109473873/200858457-7a44bf62-25a6-4276-b614-ce5ad2d20591.png)

Test steps: [TC832 - Show Node Infromation](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348399#case_3631924)
