### ISSUE TITLE
Can't deploy run locally

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#361]
On development branch, latest commit [468cac7](https://github.com/threefoldtech/tfgrid_dashboard/commit/468cac740978d2e99d144990d9d3297d39c39132). 
After pull and yarn install and serve.

![image](https://user-images.githubusercontent.com/109473873/199716967-47c8bef3-5780-4a8f-bdcb-216d8b04cd6b.png)

![image](https://user-images.githubusercontent.com/109473873/199716894-81eba982-8f3b-4337-8659-28f7388bc1ce.png)

**Comment by xmonader** [comment]
Please include in the report the version/branch you are testing against as well

**Comment by A-Harby** [comment]
Verified on main branch.

Deployed successfully was no errors   
![image](https://user-images.githubusercontent.com/109473873/199732160-f72800ce-485e-4d73-8686-ea1cd4de3b88.png)
