### ISSUE TITLE
Resources Pricing Calculator: `CRU` field

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#368]
### Description

The `CRU` field in the Resource Pricing Calculator accepts decimal values and changes the pricing accordingly, it's normal for `MRU, SRU, HRU` to accept decimal values but for the `CRU` it doesn't look normal and it should only accept positive integers and change the price when it's an integer only.

![image](https://user-images.githubusercontent.com/101194226/200160706-2e2a610e-4de4-40eb-b6d5-f0a8a6b247ff.png)

![image](https://user-images.githubusercontent.com/101194226/200160730-3117d272-0524-41c8-adbb-b046edca2c96.png)

as it can be seen in the screenshots above, the price changes when a decimal value is entered in the `CRU` field when it's not a valid value and should result in a clear error message that decimal values are not accepted in this field.

And the Tag in this field should be changed from `cores` to `vCores` for the sake of consistency.

![image](https://user-images.githubusercontent.com/101194226/200160644-1546c507-1f7d-41a6-b929-f88aee2f0303.png)

### Steps to reproduce

- Navigate to https://dashboard.dev.grid.tf
- From the sidebar expand `Calculators` then click on `Resource Pricing`.
- Enter a decimal value in the `CRU` field.

**Comment by xmonader** [comment]
great findings @mohamedamer453!

**Comment by mohamedamer453** [comment]
Verified on devnet.

The tag was changed from `cores` to `vCores`

![image](https://user-images.githubusercontent.com/101194226/201114241-04ef204b-6dec-4567-957e-0dc0702db6b8.png)


and the cru field now doesn't accept decimal values and the calculator will not display the price if the input is invalid.

![image](https://user-images.githubusercontent.com/101194226/201114588-a54fa0e5-7f02-4c22-a487-00603ef57484.png)
