### ISSUE TITLE
Calculators: Sidebar Icons

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#370]
### Description

The sidebar icons for the `Resource Pricing Calculator` & `Simulator` are not displayed in the sidebar when it's collapsed.

[TF DASHBOARD (8).webm](https://user-images.githubusercontent.com/101194226/200162855-f081882a-88fa-4fc2-ba54-b66f3e4f2c70.webm)

**Comment by khaledyoussef24** [comment]
### verified on devnet

steps made to verify

1. go to the dashboard
2. open the side bar 
3. open the drop menu of the calculator
4. verify that the icons spacing is collapsed  

[Screencast from 11-29-2022 04:34:28 PM.webm](https://user-images.githubusercontent.com/110984055/204557748-61a43eef-8129-43af-810d-05d8668cba99.webm)
