### ISSUE TITLE
Sidebar Icons/Names

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#372]
### Description

Unique Sidebar Icons should be added for Simulator, Bootsrap, Hub, Playground.

![image](https://user-images.githubusercontent.com/101194226/200163968-b4955c00-264a-404e-93e1-2c4aa9975c0b.png)

For `Hub` & `Bootstrap` it should  be renamed to `Zero-Os Hub` & `Zero-Os Bootstrap` for an easier user experience. 

For `Zero-Os hub` & `Playground` there should be any indication that these are external links unlike the rest of the buttons in the sidebar. for example their icons should be replaced with an icon for external links or it should be added next to their names.
![4596321-200](https://user-images.githubusercontent.com/101194226/200164697-4171990f-adf5-468b-a0b8-0b21b48b92dd.png)

**Comment by khaledyoussef24** [comment]
### verified on devnet

steps made to verify

1. open [dashboard](https://dashboard.dev.grid.tf/)
2. open the sidebar
3. make sure that icons renamed
![Screenshot from 2022-11-29 16-22-59](https://user-images.githubusercontent.com/110984055/204555068-0c736da5-8320-40ce-9bcf-0c3322b13667.png)
