### ISSUE TITLE
Potential error in TFT balance amount required in wallet to get discount on dedicated nodes.  Balance requirement too low?

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtecharchive/tfgrid_dashboard#373]
How can a wallet balance of 400 TFT's give you 40% discount on the price of a dedicated node kosting 10 USD a month.  10 USD / 0.03 = 330'ish tokens per month?

40% requires 12 months to be in the wallet so should be around 4000 TFT"s
<img width="954" alt="image" src="https://user-images.githubusercontent.com/13766992/196991398-fd3bb5e8-a8ae-46a8-b6a4-4ad3cf8564ff.png">

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/13766992/196991491-df4590ea-bd84-4263-9f17-c348daee2ea6.png">

**Comment by weynandkuijpers** [comment]
Hi - any update on this?

**Comment by weynandkuijpers** [comment]
Also:
<img width="338" alt="image" src="https://user-images.githubusercontent.com/13766992/199668307-3034c44d-cac2-4a47-a2ee-980d349129a3.png">

The [wiki states 70% discount](https://library.threefold.me/info/manual/#/manual__dashboard_portal_dedicated_nodes?id=billing-amp-pricing) on the retail price is you rent a dedicated node. The percentage is is not displayed in the pop-up

**Comment by ramezsaeed** [comment]
for the percentage in the comment, its fixed but not yet deployed on mainnet.
will verify with the docs ..

**Comment by A-Harby** [comment]
Yes, that would be true, just for more clarification based on the [Discount Levels](https://library.threefold.me/info/threefold/#/tfgrid/grid/pricing?id=discount-levels), And using the resource available on node 7 as an example, it should cost $17.86/month for renting the node with no TFT balance. 
![image](https://user-images.githubusercontent.com/109473873/199696711-f9b6e74a-5924-4f1c-83cd-8dd781562e2d.png)
Therefor for having 40% discount is having a balance enough for renting this node for 12 months which will be having $214.32 (7144 TFT), and having 400 TFT only is not even enough for having the default package. 
![image](https://user-images.githubusercontent.com/109473873/199698643-381ba15e-1126-422e-a478-d225d615fc3e.png)

**Comment by AhmedHanafy725** [comment]
I think the dashboard calculates the discount from the balance as USD not TFT, @Omarabdul3ziz can you check?

**Comment by zaelgohary** [comment]
As @AhmedHanafy725 said, the balance should be entered in USD. This should be fixed on devnet once https://github.com/threefoldtech/tfgrid_dashboard/pull/365 gets merged.

A dedicated node is half the price of the shared one and if the user has more than (shared node price / 2 * 12) USD in his account, he should be eligible to get the silver package.

**Comment by A-Harby** [comment]
Verified on Devnet.

Calculation is now correct.
Using the resource available on node 7 as an example, it should cost $17.86/month for renting the node with no TFT balance.
![image](https://user-images.githubusercontent.com/109473873/201121658-97f95dbd-db4a-4daf-9186-d51d0ed1ca37.png)
For having 20% discount (Defualt package) is having a balance enough for renting this node for 3 months which is having more than 2679 TFT.
![image](https://user-images.githubusercontent.com/109473873/201121863-5cdfdabd-633f-46e5-97f1-3eef6a3067ad.png)
For having max discoiunt 60% (Gold package) is having a balance enough for renting this node for 36 months which will be having more than 32148 TFT.
![image](https://user-images.githubusercontent.com/109473873/201122196-de8c4cfa-6188-4e10-a792-28335524acb8.png)

Test steps: [TC1281 - Verify calculator pricing](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=366896#case_3765664)
