### ISSUE TITLE
Nodes are counted multiple times if you load the nodes page twice

### ISSUE THREAD

**Issue by coesensbert** [threefoldtecharchive/tfgrid_dashboard#378]
### Description

The amount of available nodes are counted twice if you navigate the dashboard in a specific way.

### Steps to reproduce

- Visit dashboard.dev.grid.tf and navigate to Explorer > Nodes
- Then click 'Threefold Chain' at the top left
- Select a wallet
- Go back to Explorer > Nodes

### Logs/Alerts

Here I loaded the nodes page already before, went back to select a wallet and back to the nodes page. You can see the nodes are already there, but it's loading the list again.
![image](https://user-images.githubusercontent.com/88312671/200346144-98b9752d-b61c-4606-9bef-75c1d57e95ce.png)

Which then gives 5643 nodes.
![image](https://user-images.githubusercontent.com/88312671/200346239-2e13995e-cdc3-42ee-80dc-a901f0a12840.png)

**Comment by scottyeager** [comment]
Can confirm. I've also experienced this, but couldn't pin down the steps to reproduce.

**Comment by A-Harby** [comment]
[Duplicate Issue ](https://github.com/threefoldtech/tfgrid_dashboard/issues/267) and It's already being fixed in PR related to [this issue](https://github.com/threefoldtech/tfgrid_dashboard/issues/261).

Closing this issue,  U could follow First issue for further info.
