### ISSUE TITLE
Transfer TFTs: Recipient address validation

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#380]
### Description

The input validation of the `Recipient` field doesn't work when you select an address from the dropdown and then replace it with any invalid input.

[TF DASHBOARD (9).webm](https://user-images.githubusercontent.com/101194226/200549550-6c03c245-9d6a-49d9-9e54-480fcf8b7e34.webm)

Also there is a typo in the placeholder `Receipient`

![image](https://user-images.githubusercontent.com/101194226/200549665-c5f4c295-0985-4b32-ba48-981d643b59b4.png)

### Steps to reproduce

- Navigate to https://dashboard.dev.grid.tf
- Login to your account and select `Transfer` from the sidebar.
- From the Recipient address dropdown choose one of the addresses (You must have more than one account for this step)
- Clear the selected address and add any invalid input.

**Comment by zaelgohary** [comment]
Tried to reproduce the issue but validation seems to work fine as shown below.
[transfer.webm](https://user-images.githubusercontent.com/40770501/201528302-132a2749-40da-4dff-a6c5-ea72b1dd597e.webm)

**Comment by mohamedamer453** [comment]
> Tried to reproduce the issue but validation works seem to work fine as shown below. [transfer.webm](https://user-images.githubusercontent.com/40770501/201528302-132a2749-40da-4dff-a6c5-ea72b1dd597e.webm)

The issue is still available and reproducible from my side as it can be seen here.

[Untitled_ Nov 14, 2022 10_46 AM.webm](https://user-images.githubusercontent.com/101194226/201616045-61260525-e300-4b01-9ae6-c745da975ac8.webm)

what i realized from the added video in the comment above is that when you click outside of the field the validation will be triggered and it'll disable the submit button but if you don't click outside the submit button will not be disabled and you will be able to complete the transaction and the tfts will be transferred from your account to an invalid address.
both of the mentioned cases are shown in the video.

**Comment by khaledyoussef24** [comment]
### ** verified on devnet**

steps made to produce

1. go to dash board
2. choose a profile
3. open the side menu
4. open the transfer tab
5. put 1 tft to transfere
6. open the drop down menu
7. choose an address
8. notice that the submit button is available to click
9. try to insert invalid address it will be disabled 

[Screencast from 11-29-2022 04:56:53 PM.webm](https://user-images.githubusercontent.com/110984055/204564914-fc6593fe-fac2-4057-91ac-0abb17a0a915.webm)
