### ISSUE TITLE
Resource Calculator: Wiki link disappears when an invalid input is entered

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#386]
### Description

The wiki link that was added in the resource pricing calculator disappears once an invalid input is entered.

[TF DASHBOARD (11).webm](https://user-images.githubusercontent.com/101194226/201122968-08fe1a4c-f9fa-4793-9af2-7bfff3fe57be.webm)

### Steps to reproduce

- Navigate to https://dashboard.dev.grid.tf/
- From the sidebar expand `Calculators` then click on `Resource Pricing`.
- Enter any invalid value in any of the fields.

**Comment by xmonader** [comment]
can't we just have it next to the heading?

**Comment by zaelgohary** [comment]
> can't we just have it next to the heading?

like this? 
![image](https://user-images.githubusercontent.com/40770501/201934907-3f8b3e48-c24f-4d4a-a24a-733ed96e2fe9.png)

**Comment by khaledyoussef24** [comment]
### verified on devnet

steps made to verify

1. open the dash board
2. go to calculator
3. check the link you will find it in a better position next to the title
4. ![Screenshot from 2022-11-29 16-40-12](https://user-images.githubusercontent.com/110984055/204559239-0a847f15-0ed6-4ea5-b9e2-6729f04aa744.png)
