### ISSUE TITLE
Explorer: Multiple Errors in the console when you expand any farm

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#394]
### Description

Multiple errors are reported in the console when you open the details of any farm from the explorer.

[Untitled_ Nov 15, 2022 10_50 AM.webm](https://user-images.githubusercontent.com/101194226/201875478-49e972f9-e2af-444c-9563-f57b41e09f9c.webm)

### Logs

![image](https://user-images.githubusercontent.com/101194226/201879277-bdc11cae-02a4-4323-aa19-d17cab1a7b70.png)

```
Access to fetch at 'https://gridproxy.dev.grid.tf/nodes/undefined' from origin 'https://dashboard.dev.grid.tf' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
```
GET https://gridproxy.dev.grid.tf/nodes/undefined net::ERR_FAILED 404
```
### Steps to reproduce

- Navigate to https://dashboard.dev.grid.tf/ then navigate to the farms page in the explorer.
- Click on the details of any farm then check the console.

**Comment by 0oM4R** [comment]
it looks like there is an error while accessing the nodeId on https://github.com/threefoldtech/tfgrid_dashboard/blob/eb248d6c5cdaa5ff5ebe4b22ef6420f4c0e56c4d/src/explorer/components/DetailsV2.vue#L158
 so it calls `'https://gridproxy.dev.grid.tf/nodes/undefined' `
I need to collect more information about the explorer to know what is the correct API should be called

**Comment by A-Harby** [comment]
Verified on Devnet, v1.3.0-rc1.
No error is displayed while expanding any farm details in the console.
![image](https://user-images.githubusercontent.com/109473873/204555147-99425d8d-b465-4075-89a6-e1dfad32d459.png)

Test steps: [TC833 - Show Farm Information](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348399#case_3631926)
