### ISSUE TITLE
Explorer: Remove the online suffix from the statistics page

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#395]
### Description

In the statistics page, the online suffix should be removed as it was removed before from the [grid stats](https://github.com/threefoldtech/tfgrid_stats/issues/27) before for the sake of consistency.

![image](https://user-images.githubusercontent.com/101194226/201882818-cbe4eaa9-a72c-413e-936d-aa8bd7fd2d61.png)

**Comment by A-Harby** [comment]
Verified on Devnet, v1.3.0-rc1.
online suffix is removed from the statistics page.
![image](https://user-images.githubusercontent.com/109473873/204555913-96a46480-7f3c-4b6c-928c-45f57b0b8439.png)

Test steps: [TC822 - Explorer should show Nodes Statistics and Distribution Map](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348399#case_3631466)
