### ISSUE TITLE
Incorrect conversion for the created and updated at timestamps in the `Your Farm Nodes` table

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#396]
### Description

The mentioned node is node `6` in qanet.

The timestamp for the created and updated at is incorrectly converted in the `Your Farm Nodes` table. both dates are displayed as follows: 

![image](https://user-images.githubusercontent.com/101194226/201885769-f1c07af4-72a2-48c9-b002-af1a123baa7d.png)

but if you try to convert the time stamps that are available from the grid proxy it'll display the correct date.

![image](https://user-images.githubusercontent.com/101194226/201888061-924529cf-3c99-43cc-aea6-e535eea16bd9.png)

![image](https://user-images.githubusercontent.com/101194226/201888223-2e31348b-d464-4920-abb8-a1e3095a16ca.png)

![image](https://user-images.githubusercontent.com/101194226/201888344-4cb2af35-1372-4414-a4d2-2cb632cf2715.png)

and it's also converted correctly in the nodes details from the explorer.

![image](https://user-images.githubusercontent.com/101194226/201890371-10aecbd6-ccad-4664-a598-7bca0a3014b0.png)

**Comment by A-Harby** [comment]
Verified on Devnet, v1.3.0-rc1.
Converted different nodes from grid proxy and time was the same as in the dashboard node.

![image](https://user-images.githubusercontent.com/109473873/204560160-b1f4b987-0f8e-4951-a301-21ee66fb742f.png)
![image](https://user-images.githubusercontent.com/109473873/204560539-f9e960b7-b1a8-462a-91be-4fc0b891b36c.png)
![image](https://user-images.githubusercontent.com/109473873/204560570-990b01d8-648e-4556-a6cf-80de966b0c2c.png)

Test steps: [TC860 - Verify Node Stats](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3651069) - [TC832 - Show Node Infromation](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348399#case_3631924)
