### ISSUE TITLE
warning message doesn't disappear  in farms filter 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtecharchive/tfgrid_dashboard#400]
### tested on testnet

**description**

warning message doesn't disappear  in farms filter even after removing the invalid input

**steps made to verify**

1. go to dashboard
2. open the sidebar
3. go to explorer dropdown
4. choose farms
5. choose certification type or pricing policy as a filter
6. try adding an invalid input to the filter
![Screenshot from 2022-11-16 16-19-22](https://user-images.githubusercontent.com/110984055/202206069-82410f9a-4b4d-4447-94db-edaac624483b.png)

7. a warning message will appear
8. remove the invalid input and try to put a valid input
![Screenshot from 2022-11-16 16-19-16](https://user-images.githubusercontent.com/110984055/202206120-2fb701e0-8754-4480-ad10-a8ed4faddc60.png)

9. even though you can apply filter and show the right results the warning message won't disappear

[Screencast from 11-16-2022 04:13:07 PM.webm](https://user-images.githubusercontent.com/110984055/202205965-607670a3-5090-43c2-965d-4e3165a7d9cd.webm)

**Comment by 0oM4R** [comment]
@khaledyoussef24  is this happens only if you clear the input using the clear button?
if you use backspace or delete keys this occurs too?

**Comment by khaledyoussef24** [comment]
verified on devnet
[Screencast from 04-10-2023 02:09:14 PM.webm](https://user-images.githubusercontent.com/110984055/230899038-14fdade9-2754-49fd-af07-5648dd859fe2.webm)

![image](https://user-images.githubusercontent.com/110984055/230899138-c88c17a1-7d1c-4f7b-b695-006c7fb65301.png)works fine now
