### ISSUE TITLE
discounts are on the global level: should work for dedicated or shared nodes

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tfgrid_dashboard#401]
discounts are on the global level: should work for dedicated or shared nodes

**Comment by A-Harby** [comment]
Verified.

You could see discount differences by comparing renting price on same dedicate node between 2 twin with different balance amount, And also by deploying full VM with some resource on same shared node by 2 different twin.
And confirming these prices using pricing calculator.
e.g.
![image](https://user-images.githubusercontent.com/109473873/205059506-a6d8f1ca-eaed-4acd-a7c5-536fadb1b053.png)
![image](https://user-images.githubusercontent.com/109473873/205059589-075ac527-2dff-46e4-b2e0-a9ac1b047734.png)
