### ISSUE TITLE
Rounding on explorer is off 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtecharchive/tfgrid_dashboard#406]
### Description

Explorer is not showing fractional TB, it's rounding down. In some cases 3.9TB is shown as 3TB which confuses users.

**Comment by xmonader** [comment]
caused by https://github.com/threefoldtech/tfgrid_dashboard/blob/development/src/explorer/filters/toTeraOrGigaOrPeta.ts#L17

**Comment by sabrinasadik** [comment]
Just realized we're lacking consistency. Let's make sure GB, TB and PB have the same rounding (2 decimals)

**Comment by A-Harby** [comment]
Verified on Devnet, v1.3.0-rc1.
Resource is now displayed in 2 decimals.
![image](https://user-images.githubusercontent.com/109473873/204561777-3d61d631-400f-4e71-bbe4-18a503f3241a.png)

Test steps: [TC810 - Verify Dedicated Nodes Resources](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3631439)
