### ISSUE TITLE
Dedicated Nodes: The `Longitude` & `Latitude` fields are empty in the node information

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#410]
### Description

The `Longitude` & `Latitude` fields are empty when you expand the node information in the `Dedicated Nodes` tab.

![image](https://user-images.githubusercontent.com/101194226/203333234-c485730e-a183-4ad6-ab0c-c8a6709e3b7d.png)

### Steps to reproduce

- Navigate to https://dashboard.dev.grid.tf/
- Select an account then from the sidebar navigate to the `Dedicated Nodes` tab.
- Expand the information of any node available in that table and check the `Longitude` & `Latitude` fields

**Comment by A-Harby** [comment]
The Longitude & Latitude fields aren't empty anymore, but its shown as unknown while e.g. node 12 in the explorer node have a Longitude & Latitude value.
Same applies to the other nodes.

![image](https://user-images.githubusercontent.com/109473873/208892733-f4b86052-cb75-4390-b92f-24062e86445b.png)
![image](https://user-images.githubusercontent.com/109473873/208892659-21c5ee00-7be8-4745-8b7e-063a2c6f5c3e.png)

**Comment by AhmedHanafy725** [comment]
a fix was done on the gridproxy, it should be the same in both tables

**Comment by A-Harby** [comment]
Verified on Devnet, v1.3.0-rc2.
Node now have a Longitude & Latitude values.
![image](https://user-images.githubusercontent.com/109473873/209963819-65de94be-c5f6-41cc-8f0f-0a13fe86f6be.png)
