### ISSUE TITLE
Can't create a twin on devnet

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#415]
### Description

Devnet, v1.2.1
Can't create twin after creating account using polkadot, constantly getting rejected and failed alerts.

### Logs/Alerts

Steps:
[Untitled_ Nov 24, 2022 3_02 PM.webm](https://user-images.githubusercontent.com/109473873/203791790-5c699931-1694-4857-a3a2-e3d9d316a21a.webm)
Console logs:
![image](https://user-images.githubusercontent.com/109473873/203791752-fa4fd146-c287-4218-93b8-ed5e8f5e2a8f.png)

**Comment by renauter** [comment]
Problem was identified
https://github.com/threefoldtech/tfchain/issues/519
This fix should solve
https://github.com/threefoldtech/tfchain/commit/efeb6dc3e77e4d87937529d19ed95ae2d0846e6f

**Comment by Mahmoud-Emad** [comment]
The problem was in the document hash, the maximum acceptable length of the hash is 50 while we were sending more than 50, so a new package was installed that can generate a short hash and send it to the chain.

**Comment by A-Harby** [comment]
Verified on Devnet, v1.3.0-rc2.

I can created a twin successfully without getting failed alert 'Rejected'.
