### ISSUE TITLE
Balance Summary: The `Locked` tfts are not reflected correctly in the dashboard

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#416]
### Description

The `Reserved (Locked)` TFTs field in the balance summary doesn't reflect the correct amount of actual locked tfts and it displays `0` even though there are locked tfts for this twin when i checked from the weblets.

![image](https://user-images.githubusercontent.com/101194226/204140249-df766650-4e38-475c-a9a7-83a2f9f9c321.png)

![image](https://user-images.githubusercontent.com/101194226/204140287-a9969465-c3bf-4133-8b04-870c02e15a36.png)

![image](https://user-images.githubusercontent.com/101194226/204140297-ea29bfff-1147-45ba-b699-b0750e735abc.png)

### Steps to reproduce

- Navigate to https://dashboard.dev.grid.tf/
- Login to one of your accounts that you know that it has `Locked` tfts.
- Click on your balance and check the `Reserved (Locked)` TFTs field
- Compare the value displayed in this field to the `Locked` tfts field from the weblets for the same twin.

**Comment by maayarosama** [comment]
I think there's something wrong with the Api as it returns The Reservedbalance with 0 value.
I tried to see what's the reserved balance value on polkadot and it also set to zero
![polkadot](https://user-images.githubusercontent.com/66883096/204296211-03aa1e89-e583-4f2e-a3cc-8e0f02fba228.png)

**Comment by maayarosama** [comment]
> I think there's something wrong with the Api as it returns The Reservedbalance with 0 value. I tried to see what's the reserved balance value on polkadot and it also set to zero ![polkadot](https://user-images.githubusercontent.com/66883096/204296211-03aa1e89-e583-4f2e-a3cc-8e0f02fba228.png)

Please discard this comment, As the Locked amount isn't reflected in the reserved variable but in the feeFrozen one.

**Comment by A-Harby** [comment]
Verified on Devnet, v1.3.0-rc2.

Locked TFT value is now reflected on dashboard twin balance as shown below, also tried on different account and the result is the same.

![image](https://user-images.githubusercontent.com/109473873/209175702-638e6d21-38b6-4f36-b5fe-7da78c02326b.png)
![image](https://user-images.githubusercontent.com/109473873/209175793-72ad863c-d268-4391-8954-e1d5c951f057.png)
