### ISSUE TITLE
Locked tft value is not calculated when transferring or withdrawing tfts.

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#418]
### Description

Locked TFTs value is not calculated when transferring or withdrawing tfts.

for example for twin `152` the balance is `27.5117266 TFT` and the locked is `27.5069994` i got both values from the weblets since the locked value is not reflected correctly in the dashboard #416.

when i tried to transfer tfts to another twin the deployment failed with an unclear error message. 

[TF DASHBOARD (12).webm](https://user-images.githubusercontent.com/101194226/204140924-f007a3f3-97d0-44f4-9d00-dc8b1697d801.webm)

and a weird thing happened with the withdraw where i was able to actually withdraw tfts even though my whole balance is supposed to be locked

[TF DASHBOARD (13).webm](https://user-images.githubusercontent.com/101194226/204141598-2a039a01-ead0-451d-af73-a0aa74a4ca7d.webm)

and now the amount of locked tfts for my twin is greater than the balance itself.

![image](https://user-images.githubusercontent.com/101194226/204141447-d4503ee8-25f4-4ae5-a9f2-b97aae2d22df.png)

so a validation should be added where the tft amount in both the transfer and withdraw functions to prevent the user form sending more tfts than the `Locked` ones.

**Comment by AhmedHanafy725** [comment]
@DylanVerstraete can you have a look? I think this should be prevented also on the chain

**Comment by zaelgohary** [comment]
reserved always returns 0, so I just used feeFrozen instead as been done in the weblets.
![image](https://user-images.githubusercontent.com/40770501/204306858-e3ad1c89-b7de-4d2c-a823-a21dd7c73940.png)

**Comment by DylanVerstraete** [comment]
You mean withdrawing on the bridge?

**Comment by DylanVerstraete** [comment]
Correct, I created a followup issue here: https://github.com/threefoldtech/tfchain_tft_bridge/issues/104

**Comment by A-Harby** [comment]
Verified on devnet, v1.3.0-rc2.

Alert message changed from just `transaction failed` to be be more descriptive message `account balance too low`.

![image](https://user-images.githubusercontent.com/109473873/209176579-807a1419-3f44-4f48-8e0b-fa619d3acce5.png)

[Withdraw issue](https://github.com/threefoldtech/tfchain_tft_bridge/issues/104) will be re-verified once stellar address[ validation issue](https://github.com/threefoldtech/tfgrid_dashboard/issues/433) solved.
