### ISSUE TITLE
Pricing calculator - staking discount not applied to shared node price

### ISSUE THREAD

**Issue by scottyeager** [threefoldtecharchive/tfgrid_dashboard#422]
If I increase the `Your Balance` field, only dedicated node price reflects the "staking discount", not the shared node price:

![image](https://user-images.githubusercontent.com/17682591/204372740-82c575d7-39e0-40f1-8426-562123ce3613.png)

**Comment by AhmedHanafy725** [comment]
That's true and fixed here #401

**Comment by scottyeager** [comment]
Thanks @AhmedHanafy725. Didn't find that issue in my search.
