### ISSUE TITLE
Rented dedicate node price isn't changing for any twin balance

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#424]
### Description

Rented dedicate node price is the same no matter if my twin balance is 100 or 10000 TFT, so is it the price calculate for my twin or is it the price calcaluated for the twin renting it? 

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/204583591-d25e6917-8e20-45c9-8e0d-d0efae6de550.png)
![image](https://user-images.githubusercontent.com/109473873/204583674-78c9229c-d0bc-4ae9-91a6-40bc289af5c2.png)

## Suggestion 

If it is the price is was rented by, then it should be changed maybe to `Rented price` or anything which would make it clear to the user that it's not the price he could rented for.

**Comment by ramezsaeed** [comment]
can you test with amount bigger than 10000, maybe 10000 is not enough

**Comment by ramezsaeed** [comment]
https://library.threefold.me/info/threefold/#/tfgrid/pricing/threefold__pricing?id=discount-levels

**Comment by A-Harby** [comment]
> can you test with amount bigger than 10000, maybe 10000 is not enough

41.31 price is the dedicate node value after the discount for the twin with 1000030 TFT balance.
![image](https://user-images.githubusercontent.com/109473873/205490311-7c02d03c-83e7-4108-b327-46ba5a01cc7d.png)
But the twin with only 100 TFTs balance the price should be $103.27.
![image](https://user-images.githubusercontent.com/109473873/205490394-36325eaf-085b-4cf8-a26e-51810ce38949.png)

**Comment by A-Harby** [comment]
Verified on devnet. v1.3.0-rc2
Dedicate node price value is now calculated and changed depending on twin TFT balance amount.

![image](https://user-images.githubusercontent.com/109473873/208887911-d3d51c14-48ac-4e37-b21d-960aec4fc9af.png)
![image](https://user-images.githubusercontent.com/109473873/208887984-4e40a14b-8c89-4b3a-a3ae-b6b6fa371ccc.png)
