### ISSUE TITLE
(Mainnet verification) Time error on dashboard

### ISSUE THREAD

**Issue by Parkers145** [threefoldtecharchive/tfgrid_dashboard#429]
### Description

Report from telegram, when looking at node stats on the dashboard first boot time and time last updated is in accurate 

### Steps to reproduce

List of steps to reproduce the problem if it's a bug

dashboard->farms->nodes

### Logs/Alerts

Logs/Alerts if available

picture included with report on telegram, I’ll attempt to reproduce when I get to my laptop but multiple users reported

![716FEC34-DD41-4DBD-B9AD-38166F87B6D9](https://user-images.githubusercontent.com/44621168/205522281-d5c29cf0-2d38-422d-967c-ae014b8a012d.jpeg)

**Comment by Parkers145** [comment]
![image](https://user-images.githubusercontent.com/44621168/205531915-bafd9e7a-32df-4de3-9ee6-fdbca4e04936.png)
issue on main net 

![image](https://user-images.githubusercontent.com/44621168/205532122-c2e80f09-dcde-46d1-86bb-b2608c7425e0.png)
issue on test net

**Comment by A-Harby** [comment]
Issue was already reported and fixed on devent, [Issue](https://github.com/threefoldtech/tfgrid_dashboard/issues/396).
But it's not released yet neither on testnet nor mainnet.

**Comment by sabrinasadik** [comment]
Please close once deployed on mainnet

**Comment by A-Harby** [comment]
Verified on Mainnet, v1.3.1.
From a node details.
![image](https://user-images.githubusercontent.com/109473873/220916713-9235ffb7-1f1c-48c5-8e37-73aa87400348.png)
From Node explrorer
![image](https://user-images.githubusercontent.com/109473873/220917240-035e99c7-e9c8-4714-8d0f-3047d47655e1.png)

Node in the issue
![image](https://user-images.githubusercontent.com/109473873/220917447-7d4cbd50-d0bd-4e9f-8459-f2802808414d.png)
![image](https://user-images.githubusercontent.com/109473873/220917596-1113413e-8058-4273-864c-d3535612d391.png)
