### ISSUE TITLE
Add a link to the monitoring dashboard 

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tfgrid_dashboard#439]
https://metrics.grid.tf

**Comment by A-Harby** [comment]
Verified on Devnet, v1.3.0-rc4.
![image](https://user-images.githubusercontent.com/109473873/213191279-cd41818c-88fd-4806-8d31-be9f91f7f6fc.png)
![image](https://user-images.githubusercontent.com/109473873/213191157-a8e59471-65f9-40f6-8425-12e4665b7fd9.png)
