### ISSUE TITLE
Public IPs validation isn't working correctly

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#444]
### Description

Keep getting failing to add public config to your node without explain why and without any validation errors.
After testing every input to accept config, IPV4 was the reason.
e.g. 23.24.221.243/30

### Logs/Alerts

[Untitled_ Dec 27 2022 6_57 PM.webm](https://user-images.githubusercontent.com/109473873/209697810-b413f0a3-364d-4790-af09-6d7a1e1a2442.webm)

**Comment by coesensbert** [comment]
Not sure it's the reason but your ipv4 address is not correct if the subnet mask is /30.
The only free ip's in that range are 23.24.221.241 - 23.24.221.242
So the ip needs to be one of the two (not 23.24.221.243), and the gateway (can never be 1.1.1.1) also.
![image](https://user-images.githubusercontent.com/88312671/209698714-b4c8cb8a-6839-4201-83e1-ddf62ecf2c5c.png)

Ipv6 too, ::5/26 can never work online
![image](https://user-images.githubusercontent.com/88312671/209699059-960aa68c-dda1-420f-a55f-88d55cd57fe0.png)

I would guess the on-chain ip check would refuse such config's.

**Comment by A-Harby** [comment]
Faced same issue with `Add Public IP to Farm`, Validation passed but adding IP failed. 
![image](https://user-images.githubusercontent.com/109473873/209814116-6184ecc9-bb84-4545-b606-f1c76d20bc18.png)

So I think public IPV4 and IPV6 needs some kind of public IP checker.

**Comment by DylanVerstraete** [comment]
@A-Harby status?

**Comment by A-Harby** [comment]
> @A-Harby status?

The problem was with dashboard input validation rather than TFChain validation.
The inputs don't check if an IP is public or not, and they allow it then it fails to add the IP from TFChain (and the alarms don't specify what caused the failure).

**Comment by xmonader** [comment]
Validation should be the following if the IP falls in `192.168.0.0/24` ,`172.16.0.0 - 172.31.255.255` and `10.0.0.0/8` also regex logic would be cumbersome, I believe it should be done by creating a network object and checking if the ip falls in that range

**Comment by A-Harby** [comment]
Verified on Devnet, v1.4.0-rc4.

Private IPs are now blocked from being added with alert message 'IP/Gateway is not public' added to clarify.
![image](https://user-images.githubusercontent.com/109473873/223740404-3e2e0086-0468-49a4-ae6a-f1c4b323a8c7.png)
