### ISSUE TITLE
The portal tab should have a hint message when the user clicks on it without selecting an account.

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtecharchive/tfgrid_dashboard#445]
### Description

I worked on the dashboard many times and am still confused about the portal part, this tab won't open if you don't select an account from `Connected Accounts`, I suggest that why not we have a hint message that tells the user `You should select an account to display the portal functionalities`?

**Comment by Mahmoud-Emad** [comment]
Should be improved in https://github.com/threefoldtech/tfgrid_dashboard/pull/448

**Comment by A-Harby** [comment]
Verified on Devnet, v1.3.0-rc4.
![image](https://user-images.githubusercontent.com/109473873/213191695-1b363ac7-9157-45fa-9d17-a640f1e05a5a.png)
