### ISSUE TITLE
Portal children don't have an active class to activate the selected child with backgrounds like explorer and calculator 

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtecharchive/tfgrid_dashboard#446]

**Comment by A-Harby** [comment]
This [issue](https://github.com/threefoldtech/tfgrid_dashboard/issues/464) maybe related to your issue.

**Comment by A-Harby** [comment]
Verified on Devnet, v1.3.0-rc4.
![image](https://user-images.githubusercontent.com/109473873/213449806-0dcedf1e-fb56-41d4-a5be-770eaeaad2a7.png)

> This [issue](https://github.com/threefoldtech/tfgrid_dashboard/issues/464) maybe related to your issue.

issue wasn't related.
