### ISSUE TITLE
Update repo's docs

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtecharchive/tfgrid_dashboard#449]
docs should have

- [x] project intro
- [x] how to use
- [x] how to run tests (already there [selenuim](https://github.com/threefoldtech/grid3_client_ts/tree/development/tests#tests) and [cypress](https://github.com/threefoldtech/tfgrid_dashboard/blob/development/docs/Cypress.md#cypress), but needs to be mentioned)
- [x] where to find the docs
- [x] pipelines
- [x] contribution guide

## checklist 
- have an introduction to the project
- show status of the tests and code coverage
- how to run in production e.g if it was a binary or something the enduser needs to download 
- how to run in development as a developer (it's fine to link to another page)
- should have a link to internal docs for development
  - how to get the code  
  - how to configure the editor/IDE
  - how to run the tests
  - how to write new tests
  - have the workflows documented
  - have the releasing process documented

**Comment by A-Harby** [comment]
Verified.
[Readme](https://github.com/threefoldtech/tfgrid_dashboard/blob/development/README.md) is more clear and readable now and got all needed info.
