### ISSUE TITLE
Add 'new' ZOS node ID to dashboard

### ISSUE THREAD

**Issue by coesensbert** [threefoldtecharchive/tfgrid_dashboard#452]
### Description

We used to work with node ID numbers (Node ID 7 for example), which was easy to work with.
Now we have long generated ID (5Fi3WrrfRcMLbtdfm3nTSEmdr1cFkS6toy93jCuUvMo9HRGg). There is no way for a user to find a specific node based on the old node number. Only the polkadot tool can be used but this is not easy for users.
For example, going to https://metrics.grid.tf/ there is no way to find what ID is your node.

### Implementation

Leave the node ID number as is, just add an extra field per node what's it's longer node ID.

### More

Please do this in:
- Portal -> Farms -> "Your Farm Nodes" -> add for each node in the node details
- Explorer -> Nodes > add for each node in the node details

**Comment by 0oM4R** [comment]
Is the long id reachable by graphql or gridproxy?

**Comment by muhamadazmy** [comment]
The long id is the node public key on the tfchain. You can go from this long id to the node id and the other way around as well. I might provide tools to do this.
I think for now, it's possible (easy) to add the public key to the dashboard as well. It's also possible to build a way to query a node id with that public key on graphql.

**Comment by LeeSmet** [comment]
The node public key is actually the account ID of the twin, this is already shown on the dashboard in the twin details.

**Comment by muhamadazmy** [comment]
Ah idd, it's already shown under the twin section! I didn't see that one. this means we can just close this issue now

**Comment by 0oM4R** [comment]
![image](https://user-images.githubusercontent.com/62248851/211531243-79dfdeec-6e33-493b-8d4c-c81a67e66c90.png)
yes i think it already there so we can close it

**Comment by coesensbert** [comment]
So the twin ID of the node is the same as the long node id?

**Comment by 0oM4R** [comment]
> So the twin ID of the node is the same as the long node id?


Yes, I checked it with @xmonader as well.
