### ISSUE TITLE
can't create a twin on devnet

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtecharchive/tfgrid_dashboard#456]
### twin creation always fails on devnet

steps to produce : 

1. created accounts on polkadot  
2. go to dashboard to activate twin 
3. insert Planetary using Yggdrasil IPV6
4. click on create 
5. always get transaction submitted then creating failed
![Screenshot from 2023-01-12 13-18-58](https://user-images.githubusercontent.com/110984055/212053749-82bc3fdd-7abd-41ad-ae8f-dc1a654521ee.png)
![Screenshot from 2023-01-12 13-15-35](https://user-images.githubusercontent.com/110984055/212053754-31303a18-e942-4ebc-a949-bb03f2d0b5ad.png)
![Screenshot from 2023-01-12 13-14-30](https://user-images.githubusercontent.com/110984055/212053758-2a5c1b7c-048b-4d2f-ac78-64b879b94b82.png)

**Comment by khaledyoussef24** [comment]
### same problem still exists

![Screenshot from 2023-01-16 15-26-52](https://user-images.githubusercontent.com/110984055/212696799-737b3a40-0ec4-437a-99b0-ce72f797c21d.png)

**Comment by DylanVerstraete** [comment]
There is a problem signing terms and conditions as the follow up call to create a twin results in: 

```
tfgridModule.UserDidNotSignTermsAndConditions
```

**Comment by DylanVerstraete** [comment]
Can you provide me the input sent to the accept terms and conditions call?

**Comment by AhmedHanafy725** [comment]
I was trying on the latest code on the development branch and it worked, so let's re-verify after releasing

**Comment by A-Harby** [comment]
Verified on Devnet, v1.3.0-rc4.
After release transaction accepted and twin created sucessfully.
![image](https://user-images.githubusercontent.com/109473873/213186910-0db4713d-75c7-4fda-bb0a-b1a84be28048.png)
