### ISSUE TITLE
[Bug 🐞]: Missing twin ID on dashboard farm page

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtecharchive/tfgrid_dashboard#459]
### What happened?

Look up details of farm 1698:

![image](https://user-images.githubusercontent.com/22023708/212284192-37900584-449c-47ac-85de-b487fb68a357.png)

### What did you expect?

Information about the farm twin is shown, for instance this is how it is shown for freefarm (farm 1):

![image](https://user-images.githubusercontent.com/22023708/212284298-9124599e-1a86-4c83-a77b-a51bf92bab2e.png)

### What browsers are you seeing the problem on?

Firefox

### Dashboard info

dashboard.grid.tf

**Comment by maayarosama** [comment]
A farm can be associated with the owner's twin id, however in some cases the owner's twin id is deleted leaving the twin details empty.

**Comment by A-Harby** [comment]
Since the twin's `delete` button has been disabled, the issue can no longer be reproduced.
![image](https://user-images.githubusercontent.com/109473873/213194372-5156146f-9aea-4724-b7de-b426b7ce5a9c.png)
