### ISSUE TITLE
Going back from the calculator or explorer tab doesn't display all of the twin info.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#464]
### Description

Devnet, Dashboard v1.3.0-rc4.

All twin data isn't displayed (Twin ID, IP, Address, name and balance) when you navigate to explorer or calculator tab  and return back again to the twin.

### Steps to reproduce

1. Navigate to dashboard.
2. Open any twin.
3. navigate to explorer or calculator tab.
4. Go back to the twin from portal tab.

### Logs/Alerts

[Untitled_ Jan 18 2023 4_23 PM.webm](https://user-images.githubusercontent.com/109473873/213196263-810a54cb-864c-4c60-b880-94813b229f9f.webm)

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/tfgrid_dashboard/pull/472

**Comment by zaelgohary** [comment]
Verified.

[transfer_twin_details.webm](https://user-images.githubusercontent.com/40770501/214072722-fe2ba4f0-53be-4fbb-a60f-705f7f2cf9b3.webm)
