### ISSUE TITLE
Country filter in nodes view warns about special characters

### ISSUE THREAD

**Issue by scottyeager** [threefoldtecharchive/tfgrid_dashboard#465]
When I filter by country name in the nodes view of the explorer, I see this warning when typing in a country name that contains a space:

![image](https://user-images.githubusercontent.com/17682591/213329712-13cb6b3b-5bea-4b65-8593-17e7111fa1b4.png)

The full name is accepted and the filter works properly. It's only the warning that shouldn't pop up.

**Comment by A-Harby** [comment]
Verified on Devnet, v1.3.1.
Space character is added to the allowed char in searching input.
![image](https://user-images.githubusercontent.com/109473873/216317484-19242223-d1f1-447a-95cc-8e6b5d8fa219.png)
