### ISSUE TITLE
New created twin doesn't show any data

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#474]
### Description

Branch development, [daadf14](https://github.com/threefoldtech/tfgrid_dashboard/commit/daadf1464241e32a264f50346cb11273b30b2967).
Newly created account don't show twin data [ ID - Address - IP ], and balance are set to 0 TFT.

### Steps to reproduce

1. create an new twin using polka 
2. accept terms
3. create ip.

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/214262647-bbb04adc-bd26-4dfb-811f-349b96bf61cd.png)

**Comment by zaelgohary** [comment]
Couldn't reproduce the issue as I could create two accounts without any problems.

![image](https://user-images.githubusercontent.com/40770501/215316282-e5ea4408-596b-4d32-bd5c-558e7cf8a983.png)

![image](https://user-images.githubusercontent.com/40770501/215316327-37a51a79-128b-4f81-a830-43bcf0b01206.png)

**Comment by A-Harby** [comment]
Verified.
Closing the issue because the dashboard version that was causing it has been replaced with the new version.

**Comment by A-Harby** [comment]
Issue happened to me again on the dashboard after creating new twin.
Devnet version v1.3.0.
![image](https://user-images.githubusercontent.com/109473873/215328859-efe01da7-2c5c-4e60-b409-560d1c266187.png)
![image](https://user-images.githubusercontent.com/109473873/215328902-fd6b0a81-5fb8-491d-8f02-7d74fe43f858.png)

**Comment by A-Harby** [comment]
Verified on devnet, v1.3.1.
Newly created twin data are now displayed.
But balance is not correct and reported to be fixd in this [issue](https://github.com/threefoldtech/tfgrid_dashboard/issues/490)
