### ISSUE TITLE
Misleading discount of 60% with little TFT balance

### ISSUE THREAD

**Issue by s-areal** [threefoldtecharchive/tfgrid_dashboard#475]
I've created a new twin with just 500 TFT. The pricing information for reserving a node is 50% (dedicated) + (for my surprise) 60% for twin balance with only 500TFT. Like I have other twin with significant more TFT, I thought that maybe the new twin could take in consideration the other twin balance when showing pricing. I did not find this very logical as the twins, as far as I understand are individual instances, but have gave it a try and reserved a node.
As far I as understood the 60% discount is not being applied, which is correct (AFAI understand) so, in my opinons, this is just an error displaying pricing when you have multiple twins. I believe this does not happen when you only have one twin with low balance.
I would suggest dev team to take a look. 

![Captura de ecrã 2023-01-18, às 23 09 46](https://user-images.githubusercontent.com/49781569/213315503-7e2c5884-5814-469b-a098-e803e0e97e60.png)

**Comment by xmonader** [comment]
@sabrinasadik @DylanVerstraete can you guys provide a more proper phrasing please

**Comment by DylanVerstraete** [comment]
"discount when keeping TFT in your wallet" ?

**Comment by sabrinasadik** [comment]
'You receive 50% discount if you reserve an entire node (= [dedicated node](https://library.threefold.me/info/threefold#/cloud/threefold__pricing?id=dedicated-servers))'
'You receive up to 60% discount if you keep enough TFT in your wallet to pay for the deployment for an extended amount of time - [see wiki](https://library.threefold.me/info/threefold#/cloud/threefold__pricing?id=discount-levels)'

**Comment by zaelgohary** [comment]
The second message depends on the account balance so sometimes it gives 0% as a discount as shown below.

![image](https://user-images.githubusercontent.com/40770501/214545996-665b6100-75be-4cbc-b138-b964fc0f8170.png)

Suggestion: change the 2nd message to be "You're recieving % discount as per the [discount levels](https://library.threefold.me/info/threefold#/cloud/threefold__pricing?id=discount-levels)"

**Comment by zaelgohary** [comment]
Verified.
![image](https://user-images.githubusercontent.com/40770501/214554979-f28c1d66-05cc-4098-b7dd-2824807ab7a8.png)

**Comment by s-areal** [comment]
Hello. I am not sure if this was well understood. I am not "complaining" about the phrasing. What is wrong is the discount shown on testnet.

On testnet (wrong)
![Captura de ecrã 2023-01-26, às 09 29 06](https://user-images.githubusercontent.com/49781569/214802525-1bd9cdbf-980c-4e3f-b987-5a7f88f35d0b.png)

On mainet (right)

![Captura de ecrã 2023-01-26, às 09 28 27](https://user-images.githubusercontent.com/49781569/214802568-c8e2f65b-eeea-4560-9b85-562a6607dbec.png)

**Comment by s-areal** [comment]
Twin discount should be 0% for twin balance, because none of these twins have sufficient balance to have a twin discount

**Comment by s-areal** [comment]
I suggest this phrasing:
Discount: 
- 50% for the dedicated node.
- xx % for actual twin balance.
* Max discount for twin balance: 60% please see how discount levels work.

Please confirm if pricing shown on the column is net price/final price with current balance, or only 50% discount (dedicated discount)

**Comment by zaelgohary** [comment]
This issue is already fixed on dev net and will be fixed on test net also once released.
