### ISSUE TITLE
deprecated node dependencies

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtecharchive/tfgrid_dashboard#485]
### Description

[-] build: + npm install
[-] build: npm WARN deprecated micro-base@0.9.0: Switch to @scure/base for audited version of the lib & updates
[-] build: npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
[-] build: npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
[-] build: npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
[-] build: npm WARN deprecated cypress-xpath@2.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
[-] build: npm WARN deprecated vuetify-loader@1.8.0: Doesn't work at all, rollback to 1.7.3
[-] build: npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
[-] build: npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
[-] build: npm WARN deprecated core-js@3.23.2: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js

**Comment by 0oM4R** [comment]
I will upgrade the following packages 
- `@vue/cli-service` to "^5.0.8"
- `@polkadot/extension-dapp` to "0.45.1"
 
and remove "@babel/polyfill "

- some dependencies I can't upgrade them or resolve the warning because they are dependent on other packages 
  - querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
      ```
      node-polyfill-webpack-plugin
          └─── URL
             └─── querystring
       
       ```
  -  stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated
      ```
       @vue/cli-service 
          └─── cssnano 
             └───  cssnano-preset-default 
                └─── postcss-svgo 
                   └─── svgo 
                       └─── stable@0.1.8
        ```
  
  and those two related tests,  I discussed with @mohamedamer453  to resolve them 
  - cypress-xpath@2.0.1: Package no longer supported. 
  - w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
    ```
    jest
    └─── @jest/core
       └─── jest-config 
          └─── jest-environment-jsdom
             └─── jsdom 
                 └─── w3c-hr-time@1.0.2
    ```

**Comment by mohamedamer453** [comment]
>   and those two related tests,  I discussed with @mohamedamer453  to resolve them
>   
>   * cypress-xpath@2.0.1: Package no longer supported.
>   * w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
>     ```
>     jest
>     └─── @jest/core
>        └─── jest-config 
>           └─── jest-environment-jsdom
>              └─── jsdom 
>                  └─── w3c-hr-time@1.0.2
>     ```

both dependencies were resolved in #547

**Comment by 0oM4R** [comment]
please note that there is another warning the can't be resolved for now 
check https://github.com/threefoldtech/tfgrid_dashboard/pull/550#issuecomment-1460268716

**Comment by A-Harby** [comment]
Verified deprecated node dependencies is removed.
And cypress will be subtitle with selenium and its dependence will be removed.
