### ISSUE TITLE
Dashboard balance loads old balance on create new user.

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtecharchive/tfgrid_dashboard#490]
### Description

For some reason, the dashboard balance loads the old balance when creating a new user

### Steps to reproduce

- Go to [Dashboard](https://dashboard.dev.grid.tf/)
- Select an account
- logout from the selected account
- create a new account from `Plokadot`
- you'll see the newly created account in the accounts list, select it and accept the terms and conditions
- you'll see the old balance displayed, even if you created a `TF-account`

### Logs/Alerts
![image](https://user-images.githubusercontent.com/57001890/216292688-a759ebe7-d97d-4ba8-8423-dbbead535c62.png)

![image](https://user-images.githubusercontent.com/57001890/216292667-72f15d23-927a-4054-bcdb-63d7e674e105.png)

**Comment by Mahmoud-Emad** [comment]
Should be fixed in #491

**Comment by A-Harby** [comment]
Verified on Devnet, v1.4.0-rc1.
Newly created twin have the normal balance upon created.
![image](https://user-images.githubusercontent.com/109473873/218487651-d406e3cd-03a7-454a-96fc-0f321e8f90db.png)
