### ISSUE TITLE
Can't remove node public config

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#496]
### Description

failing each time I try to remove the node public config.

### Logs/Alerts

Giving success alert 'Node public config is removed' but nothing is changed.
![image](https://user-images.githubusercontent.com/109473873/216816738-0b7a30ff-3a91-4baf-8cca-a03b1456c154.png)

**Comment by A-Harby** [comment]
Now it is failing in both removing and adding the public config.
![image](https://user-images.githubusercontent.com/109473873/219054985-b0444dbd-9e0b-44b8-8c4b-1f0494042827.png)

**Comment by Omarabdul3ziz** [comment]
### Update

- Adding the public config is working fine. tried it multiple times [ add only ipv4, add ipv4 and ipv6, add both with the domain] all works for me.
- There is an issue with editing. for example, if you set all five fields and then edit the two of ipv4 and deleted the ipv6. the executed extrinsic on the chain takes only the edited ones "ipv4" so you will still have the two ipv6 untouched.
- Removing. the code works to set the config in removing to `null` and it looks like the chain only removes the value of the fields in the root level which is the `domain` field, not the nested fields 

Note: updates will not appear on the dashboard until you remount the component by reloading/switching the tabs

**Comment by Omarabdul3ziz** [comment]
After some debugging it looks just an issue in syncing the data between the chain and the database where the data comes from. opened an issue on the [graphql repo](https://github.com/threefoldtech/tfchain_graphql/issues/94)

**Comment by xmonader** [comment]
Can this be closed now given the syncing is done?

**Comment by Omarabdul3ziz** [comment]
Yes. 
The blocking issue https://github.com/threefoldtech/tfchain_graphql/issues/94 verified and closed.

**Comment by A-Harby** [comment]
> Yes. The blocking issue [threefoldtech/tfchain_graphql#94](https://github.com/threefoldtech/tfchain_graphql/issues/94) verified and closed.

But I still facing the same issue when adding or removing node public config, I have to reload the page to see the changes.

**Comment by A-Harby** [comment]
Verified on devnet, v1.4.0-rc8.
Public config is working fine.
![image](https://user-images.githubusercontent.com/109473873/226587737-f6ca18e0-1093-4650-b54e-c0bef97394ee.png)
![image](https://user-images.githubusercontent.com/109473873/226587857-ad547638-0b21-4999-aee8-8ef9c2bf9c89.png)
