### ISSUE TITLE
In Farm Page Explorer, removing filtering does not reset the filter

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#498]
### Description

When you use a filter in the farm page explorer and then remove it, the filter is not reset and no data available is displayed on the table.

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/216817274-f478635c-3bde-44a6-8cf2-d9549ebe47ac.png)

**Comment by khaledyoussef24** [comment]
verified on devnet
[Screencast from 04-04-2023 11:28:43 AM.webm](https://user-images.githubusercontent.com/110984055/229749628-dda53158-84be-4c01-98f5-00b6e22ea88b.webm)

[Screencast from 04-04-2023 11:35:45 AM.webm](https://user-images.githubusercontent.com/110984055/229751337-978f0d63-c6e9-47ed-9fcd-39165dff0f4e.webm)
