### ISSUE TITLE
No error shown when getting TFT failed

### ISSUE THREAD

**Issue by alichaddad** [threefoldtecharchive/tfgrid_dashboard#500]
### Description

When selecting to get TFT in twin page the operation took some time and then it stopped loading. No errors were produced but no TFT were received. The operation worked on a retry so it seems that there is an error with showing the issue.

![image](https://user-images.githubusercontent.com/24762033/217252303-6281f78e-6585-40bd-ab62-9565b0fbc467.png)

### Steps to reproduce

- Go To twins page and select `Get TFT` on top right, if an error occurs nothing would be shown to the user

**Comment by zaelgohary** [comment]
Tried multiple times.

Failed error is shown.

![image](https://user-images.githubusercontent.com/40770501/218430394-05b4b2a3-0aef-4f5e-a1af-573f6285c486.png)

Transaction submitted msg:

![image](https://user-images.githubusercontent.com/40770501/218431927-7ff70f62-5667-4dd2-8c99-37b0f1aa2d8b.png)

Transaction success msg:

![image](https://user-images.githubusercontent.com/40770501/218432000-628256f2-0217-4d98-95bc-b7807cf94b3d.png)

**Comment by A-Harby** [comment]
I tried to reproduce the issue, but the message alert always appears.
The issue is now closed; if it reappears, reopen it.
