### ISSUE TITLE
Rename swap -> bridge

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtecharchive/tfgrid_dashboard#501]
Swapping means swapping token X for token Y. In this situation the user is transfering between chains so bridging seems more appropriate

![image](https://user-images.githubusercontent.com/17138347/217284898-1fd45577-8685-4877-8962-762b00e64b07.png)

**Comment by ramezsaeed** [comment]
when fix please make sure its reflected in the documentation !

**Comment by A-Harby** [comment]
Verified Devnet, v1.4.0-rc2.
![image](https://user-images.githubusercontent.com/109473873/221407245-e54b4924-788e-49b9-9e17-505fe42f56d7.png)
