### ISSUE TITLE
can not create a twin on devnet

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtecharchive/tfgrid_dashboard#502]
### Description

after agreeing on the terms and inserting the Planetary using Yggdrasil IPV6 to get twin it gives error
![image](https://user-images.githubusercontent.com/110984055/217486962-ad95eac9-eb74-4b67-b3b8-78b0db2c39eb.png)
and the twin is not created
 
### Steps to reproduce

1. create a polkadot account
2. go to the [dashboard](https://dashboard.dev.grid.tf/)
3. go to the new user
4. try to create a twin
5. the twin creation will fail

![Screenshot from 2023-02-08 11-14-10](https://user-images.githubusercontent.com/110984055/217487246-2d99ed63-954a-4b58-bf78-328da548847c.png)

**Comment by A-Harby** [comment]
Closing as Issue isn't reproducible on the new release devnet v1.4.0-rc1.
