### ISSUE TITLE
Navigate new twin account to twin details page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#509]
### Description

Devnet, v1.4.0-rc1.

Newly created twin after choosing relay direct you back to the accounts page, It should be navigated to twin details page. 

### Logs/Alerts
At 00:50 seconds. 
[Untitled_ Feb 13 2023 4_44 PM.webm](https://user-images.githubusercontent.com/109473873/218489016-c89f7256-4fd5-4b7e-8174-0e3856b3dda3.webm)

**Comment by Mahmoud-Emad** [comment]
WIP: changed the old way of `saving the user data in the URL as a query params` and saving it in the credentials store instead

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/tfgrid_dashboard/pull/528

**Comment by khaledyoussef24** [comment]
verified on devnet
[Screencast from 02-28-2023 10:27:03 AM.webm](https://user-images.githubusercontent.com/110984055/221796461-ac531b51-9dc4-475d-9841-2da1ea4b88a1.webm)
