### ISSUE TITLE
Farming Calculator Adjustments

### ISSUE THREAD

**Issue by mik-tf** [threefoldtecharchive/tfgrid_dashboard#512]
### Farming Calculator Adjustments

From the Threefold Telegram channel, Threefold members would like some modifications in the resource pricing calculator:

1. [x] There is DYI nodes and Certified nodes. DYI nodes in principe cannot and aren't certified. So that option can be removed. 
2. [x] The Titan is NOT the only certified node, so that should change to Certified Nodes where ALL specs can be filled in, like a massive HPE rackserver for instance.
3. [x] ONLY certified nodes should have the option non-certified, certified and Gold farming (maybe even silver). If possible, it should somehow include the tick boxes to actually make them silver or gold.
4. [x] Currenty the Titan has the option to belong to a Gold Farm, which is simply impossible.

**Comment by xmonader** [comment]
@Mik-TF Thanks for raising the issue, i'll have it part of the upcoming updates for the dashboard.

**Comment by MohamedElmdary** [comment]
@Mik-TF @rkhamis
can you clarify what should be done in points 2 and 3?
What I got:
- For point 2: We should add new custom option in the initial list so user gets the ability to provide his own values
- For point 3: Don't understand what a tick box is(I think you mean checkbox). which marks the farm as silver or gold. if so what should be the affect on the values of calculation?

**Comment by mik-tf** [comment]
Hi!

I'm clearly very late to realize that I should have written: Farming Calculator instead of Resource Pricing. (I edited the main post).

1. DIY shouldn't have the options to be certified.

![farmer_calc_1](https://user-images.githubusercontent.com/77026219/222947378-7ba7255c-e51e-4733-991e-c50dc6ff4975.png)
![farmer_calc_2](https://user-images.githubusercontent.com/77026219/222947379-a665bde9-914f-4f2b-b77d-c53be4aa81aa.png)

2.+3. In the Titan option of the calculator, you currently can't change the parameters.
![farmer_calc_3](https://user-images.githubusercontent.com/77026219/222947404-f0e0c06a-a4b0-4637-86f0-f32717f67721.png)

The point is that now there are other 3nodes that have different specs that are certified. So we should be able to change the parameters. We can either change the name Titan v2.1 for Certified Node, and have changeable parameters, or we could also have 3 options instead of 2: 

* DIY (non-certified 3node only), 
* Titan (with fixed parameters, without gold option) 
* Certified (with changeable parameters, and Gold farming option)

4. Point 4 is that the Titan can be said as Gold certified, but it is not possible to have a Gold certified 3node. So it should be removed.

**Comment by A-Harby** [comment]
Verified on Devnet, v1.4.0-rc7.

- Certified option have been removed from DYI node option. 
![image](https://user-images.githubusercontent.com/109473873/226337884-74cefaab-9497-48b2-a24e-47e346315943.png)

- All specs can be filled in with titan option.
![image](https://user-images.githubusercontent.com/109473873/226338170-a4c69a17-bfe7-43b9-81b2-c9080006fe24.png)

- Gold certified is removed from the Titan.
![image](https://user-images.githubusercontent.com/109473873/226339104-b947d9c2-7362-4d48-8a1f-b7fd9158878e.png)

**Comment by A-Harby** [comment]
> * DIY (non-certified 3node only),
> * Titan (with fixed parameters, without gold option)
> * Certified (with changeable parameters, and Gold farming option)

@Mik-TF All four requested adjustments have been implemented, and the three options listed above have been reduced to two: DIY with a non-certified option and Titan with all changeable parameters but no gold farming option.

So, if anything is missing, please re-open and comment.

**Comment by mik-tf** [comment]
Hi @A-Harby 

Thank you for your time.
The changes are OK but I think it's not optimal by now.

What about this:

We only put 1 calculator.

In this unique calculator, users could tick the boxes:

* non-certified
* certified
* gold certified

And all parameters can be changed.

This might just be simpler for farmers overall.

**Comment by Mik-TF** [comment]
Or really, the easiest way would be to have only 1 farming calculator. instead of DIY and certified.

In this unique calculator, users could tick the boxes:

* non-certified
* certified
* gold certified

This might just be simpler for farmers overall.

**Comment by A-Harby** [comment]
Opening new issue specified for it https://github.com/threefoldtech/tfgrid-sdk-ts/issues/53
