### ISSUE TITLE
Show pop up notification for DAO proposals 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtecharchive/tfgrid_dashboard#514]
### Description

Right now we rely heavily on the community being active on Telegram to see the requests to vote on DAO proposals. If you're not actively clicking on DAO on the dashboard, you won't see it.

I suggest that whenever a DAO proposal is launched, there's a pop up being shown that notifies people that they can vote on a new DAO proposal. 

### Implementation

Ideally:
- This is shown only to people that are logged in and have a farm.
- This is not shown anymore if the user has already voted. 

Please let me know if this is possible.

**Comment by rkhamis** [comment]
We cannot tell who saw what previously. so what we can do is show current active proposals for farmers that yet voted on

**Comment by 0oM4R** [comment]
> This is shown only to people that are logged in and have a farm.

@sabrinasadik @rkhamis 
 and have nodes on the farms? 
 I think the user who has farms with no nodes on them can't vote

**Comment by sabrinasadik** [comment]
I have a node in my farm but unless I go to portal and then dao I dont see that there's a new dao vote available

**Comment by 0oM4R** [comment]
I'm asking if the pop-up should be shown to only users who have nodes on their farms right?

**Comment by mohamedamer453** [comment]
Verified on devnet.

A new pop up notification was added when a new proposal is available.

![image](https://user-images.githubusercontent.com/101194226/230868917-111dd9b0-40f5-4ac0-bfaa-d36dd2fd99ea.png)

Even if the user didn't wait in the twin page these couple of second the pop up will also appear in any other page without any issues.

![image](https://user-images.githubusercontent.com/101194226/230866776-4384121a-39b5-408b-9711-64087b3df99e.png)


[Screencast from 10-04-23 10:45:55.webm](https://user-images.githubusercontent.com/101194226/230868166-e4b005b4-6360-4d6f-a7e9-b3119cd38734.webm)


However as mentioned above in the comments that this message should only appear for users with farms but i tried a couple of my twins that don't have farms and it also appeared as seen below.

[Screencast from 10-04-23 10:47:33.webm](https://user-images.githubusercontent.com/101194226/230868515-9410e23b-2dc1-43d2-b8ee-1241b27fac0c.webm)

**Comment by mohamedamer453** [comment]
Verified on devnet.

Now the notification only appears for twins with farms only.

[Screencast from 10-04-23 15:16:48.webm](https://user-images.githubusercontent.com/101194226/230909075-e1785564-dcde-479a-8ced-99cd9f3dc8b9.webm)
