### ISSUE TITLE
Got an error 404 when I clicked on this link: https://library.threefold.me/info/manual/#/manual__tfchain_portal_polkadot_widget

### ISSUE THREAD

**Issue by shng4you** [threefoldtecharchive/tfgrid_dashboard#515]
I got an error 404 when I clicked on this link: https://library.threefold.me/info/manual/#/manual__tfchain_portal_polkadot_widget

![Link down](https://user-images.githubusercontent.com/95933607/219043992-08b45d77-3d50-47fb-b2ef-6ce59df10d96.jpg)

**Comment by ramezsaeed** [comment]
@shng4you shn please explain more how did you clicked this link from inside dashboard ?

**Comment by shng4you** [comment]
I clicked on the description link, and I got the 404 error. Also, I could not find to click this link from the inside dashboard. Would you please help me how to find the link inside the dashboard?

**Comment by ramezsaeed** [comment]
ok thanks
can you please provide a video where did you got this link !

**Comment by shng4you** [comment]
Hi @ramezsaeed , I can install the Polkadot extension and create an account. Unfortunately, when I click the description link https://library.threefold.me/info/manual/#/manual__tfchain_portal_polkadot_widget does not work, got an error 404 not found.

https://user-images.githubusercontent.com/95933607/224028428-12768047-f141-46ce-ad71-fb4bc56f468e.mp4

**Comment by ramezsaeed** [comment]
ok
great thanks got that.

**Comment by mohamedamer453** [comment]
[TC790](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_3631414) Was updated with the correct docs [link](https://library.threefold.me/info/manual/#/manual__dashboard_portal_polkadot_widget) and i'll go through this testsuite and other suites to check if there are other outdated documentation links. Thanks for reporting this! @shng4you
