### ISSUE TITLE
Nodes that should not be marked as up are marked as up

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtecharchive/tfgrid_dashboard#517]
On devnet dashboard on the node page I see:

![image](https://user-images.githubusercontent.com/17138347/219304441-fd35e9b7-ba91-41d2-a6e2-1f1e76aa7647.png)

All of these nodes have 0 uptime.

When I click on a node, for example: 56, I can see it also has 0 cpu (which is virtually not even possible)
But when I check on graphql for the last updated timestamp:

```
{
  "data": {
    "nodes": [
      {
        "updatedAt": "1662905832"
      }
    ]
  }
}
```

This node was updated at `Sunday 11 September 2022 14:17:12` which is a long time ago and thus this node should not be marked as up.

**Comment by sameh-farouk** [comment]
**Update**: access to the recently deployed grid-proxy machine was requested for further investigation. will pick this up as soon as I able to access it.

**Comment by sameh-farouk** [comment]
**Update:** The nodes table in PostgreSQL DB has mixed timestamp units, in the `updated_at` field, some in milliseconds and others in seconds.
This causes grid-proxy to report incorrect status for only these nodes with milliseconds unit as it should be all in seconds (it treats it like in far feature).
Regarding dashboard reports 0 as uptime for some nodes, these nodes have no uptime in the Postgres DB as well.
I didn't check yet anything behind the grid proxy and the Postgres DB.

![Screenshot from 2023-02-16 15-03-32](https://user-images.githubusercontent.com/42457449/219375946-b57d66b9-17c9-4094-855a-f8bf376170f5.png)

**Comment by sameh-farouk** [comment]
I'm closing this. as stated by bert:
> gridproxy.dev.grid.tf points to k8s cluster again and dashboard seems to work.

> Because gridproxy needed a processor db, I used a snapshot (that we now make daily) of a correct graphql version but before some kind of migration that did happen on the graphql on k8s.
