### ISSUE TITLE
choosing the same relay in edit in the twin details ask for transcations

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtecharchive/tfgrid_dashboard#518]
### Description

after twin creation using relay, trying to choose the same relay from edit asks for transcation
![Screenshot from 2023-02-16 11-43-54](https://user-images.githubusercontent.com/110984055/219328959-b733c1d0-ffbf-4ef3-9c2e-2788029138a2.png)

### Steps to reproduce

1. create a polkadot account
2. go to the dashboard
3. choose the new account
4. select the relay and create the twin
5. from the twin details choose edit and choose submit 
6. it will ask for transaction while it should not

[Screencast from 02-16-2023 11:44:51 AM.webm](https://user-images.githubusercontent.com/110984055/219328921-05484bf5-cbdc-4ba6-9ec0-924c44ae415b.webm)

**Comment by A-Harby** [comment]
Issue still reproducible on devnet and locally.
Still asking for transaction when changing the same relay.
![image](https://user-images.githubusercontent.com/109473873/221893027-39a699eb-393f-48dc-b019-80d0ad1f6bab.png)

**Comment by zaelgohary** [comment]
The condition had a typo after creating the credentials store.

**Comment by A-Harby** [comment]
Verified.

When choosing the same relay, the message alert pop up.
![image](https://user-images.githubusercontent.com/109473873/222954444-179baee0-b0af-45d0-a66b-23e9d110f05f.png)
