### ISSUE TITLE
Rows per page doesn't work in farm table

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#521]
### Description

`Rows per page:` counts in farm table doesn't work it and it retrieve all the tables in the twin and displays them all regardless the number chosen. 

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/219384281-5c8fda63-8290-4d1d-8237-0b1f7574ff7f.png)
![image](https://user-images.githubusercontent.com/109473873/219384225-6c61165c-1e1d-4793-a901-75c7ac6371b0.png)

**Comment by 0oM4R** [comment]
@A-Harby1  can you give more steps please, is it on portal or what?

**Comment by A-Harby** [comment]
yes portal, this is the farm table in the farm page.
Create more than 5 farm and try to change Rows per page

**Comment by 0oM4R** [comment]
Looks like the `getfarm` is using chain to fetch all the farms, then filter them by twin id! and on every farm, it makes a request to get the `farmPayoutV2AddressByFarmID` <v2adress>.
So I think we need to use gridProxy that supports pagination, and the result already contains the v2address.
this will make the performance much better on a huge number of farms as in the main net.
we may need to keep using the getFarm function as it is used on the doa page and create a new function to improve the farms page in the portal, later on, we can change the Dao page to

**Comment by 0oM4R** [comment]
![image](https://user-images.githubusercontent.com/62248851/225651060-fa39388a-9888-4fbc-bc4e-ccfe93f9dede.png)
while digging in the code i see about 30 requests on just one farm and 10 nodes is that normal ?

**Comment by 0oM4R** [comment]
okay now they are 21 request by adding this line
 ` if (this.page === pageNumber && this.size === pageSize) return;` to https://github.com/threefoldtech/tfgrid_dashboard/blob/17ed34a1f09c909319e605101d31d9daf0eacb26/src/portal/views/Farms.vue#L344

### 
on this farm we have 10 nodes 
so the 21 requests :
- 1 request to gridproxy/node 
- 10 requests to graphql with status code 204,  idk why this happens 
- 10 requests to graphql with a query  in payload and status code 200

**Comment by A-Harby** [comment]
Opening the farm page with twin have more than 10 farms.
Nothing changed and all the farm were retrieved.  
![image](https://user-images.githubusercontent.com/109473873/228590508-81edadba-2a47-403a-9c21-594f05f99685.png)
Also nothing changes when changing row per page
![image](https://user-images.githubusercontent.com/109473873/228590842-834412d2-0550-49e0-9e56-a39eee0ffca7.png)

**Comment by A-Harby** [comment]
@0oM4R Is this not deployed yet?
Because it should be deployed via the [workflow](https://github.com/threefoldtech/tfgrid_dashboard/actions/workflows/pages/pages-build-deployment), or is there a problem with it?

**Comment by 0oM4R** [comment]
so weird, it works locally very fine in production mode, @AhmedHanafy725 is there a problem with the mentioned workflow ?

**Comment by 0oM4R** [comment]
[Screencast from 29 مار, 2023 EET 05:49:34 م.webm](https://user-images.githubusercontent.com/62248851/228595392-e777e2d9-c302-45e0-9c09-afb2c226fa9a.webm)

**Comment by A-Harby** [comment]
> so weird, it works locally very fine in production mode, @AhmedHanafy725 is there a problem with the mentioned workflow ?

I think there is an problem with it because other issues are also having the same problem deployed but not fixed.

**Comment by A-Harby** [comment]
Verified,
Raw per page is now working fine and table farms changes depend on the number selected.
![image](https://user-images.githubusercontent.com/109473873/230777620-3877bdf5-a4b6-4d7a-8ed0-01eee0477ca8.png)
![image](https://user-images.githubusercontent.com/109473873/230777623-2e4d46f7-7083-4d86-af31-fe913cdd2aa3.png)
