### ISSUE TITLE
Set public key to null on edit twin

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtecharchive/tfgrid_dashboard#522]
### Description

pk is set as an empty string instead of null

### Steps to reproduce

Edit twin from twin details

### Logs/Alerts

![image](https://user-images.githubusercontent.com/40770501/220302363-ffb2988e-0a7c-41d8-9252-28508bd883a7.png)

**Comment by A-Harby** [comment]
Verified on devnet, v1.4.0-rc2.
![image](https://user-images.githubusercontent.com/109473873/221407678-be5f0ad3-ef14-44d1-ade6-01d94fa669fd.png)
