### ISSUE TITLE
Dashboard (dao) on mainnet broken

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtecharchive/tfgrid_dashboard#524]
After upgrading to 3.8

![image](https://user-images.githubusercontent.com/17138347/220357087-ba978add-5601-499d-8d3a-192ed73f0aff.png)

**Comment by DylanVerstraete** [comment]
```
Error: Unable to decode storage dao.proposalOf: entry 0:: createType(Call):: Call:: Decoded input doesn't match input, received 0x0001604d61696e6e657420757067726164652070726f706f73616c (27 bytes), created 0x0001604d61696e6e6574 (10 bytes)

```

**Comment by DylanVerstraete** [comment]
@Omarabdul3ziz any idea what is causing this? Need help debugging?

**Comment by Omarabdul3ziz** [comment]
Noticed we have the same problem on dev also. I run the dashboard locally on the four networks and the issue appears on dev/main, qa and test are good. 

i tried to test the failed query `dao.proposalOf` on polkadot ui. and that what i found on:
Testnet
![image](https://user-images.githubusercontent.com/32527347/220451252-0e9848d3-a019-4387-a3ce-6c57cc820463.png)

Mainnet
![image](https://user-images.githubusercontent.com/32527347/220452288-51c89132-c4c3-4a7a-9693-3407f60ca265.png)

i could get one of proposals content but the other one gives `<unknown>` . and that is the case also on some of the proposals on dev net.

so, could it be something in the proposal format itself?

**Comment by DylanVerstraete** [comment]
Can't we safely get all proposals (wrap in try-catch maybe) and only show the ones that we can parse? Will look into the issue deeper but the suggestion can implemented to have a working dashboard again

**Comment by DylanVerstraete** [comment]
I created a followup issue here: https://github.com/threefoldtech/tfchain/issues/614

**Comment by Omarabdul3ziz** [comment]
suggested workaround applied on the mentioned pr

**Comment by A-Harby** [comment]
Verified on Mainnet, v1.3.1.
![image](https://user-images.githubusercontent.com/109473873/221407578-fd86f2f6-c2c5-40d3-b5ea-22f415f9281c.png)
