### ISSUE TITLE
Dashboard shows the total balance but labeled it as free which is misleading

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtecharchive/tfgrid_dashboard#526]
### Description
My workload contract went on a grace period while my account shows that I have free 100+ TFT. we discover that all of them were locked.

The dashboard show the **total** balance but labeled it as **free** which is misleading.
free (transferable) should be the total - locked.

So to enhance this experience for the end user I suggest displaying the transferable amount instead of the total, so the user can fund his account when this value got lower.

### Steps to reproduce

NA

### Logs/Alerts
**Our dashboard**
![Screenshot from 2023-02-22 13-50-43](https://user-images.githubusercontent.com/42457449/220615598-db5839b6-8939-4580-85bd-e5d2a55c3987.png)

**Polkadot dashboard**
![Screenshot from 2023-02-22 14-02-50](https://user-images.githubusercontent.com/42457449/220615624-8c286fc3-65fb-4a9d-9543-ae3cb11c0d8a.png)

**Comment by A-Harby** [comment]
Rounding up decimals to nearest value isn't a good thing when dealing with TFT since most of transaction (contracts, rents) are done in decimals.
![image](https://user-images.githubusercontent.com/109473873/229821635-13af4458-96e4-4aee-a3d9-4b0c2b66e73c.png)

**Comment by Mahmoud-Emad** [comment]
@A-Harby 
Indeed, I'll return it back.

**Comment by Mahmoud-Emad** [comment]
@A-Harby 
Should be removed in https://github.com/threefoldtech/tfgrid_dashboard/pull/615

**Comment by mohamedamer453** [comment]
Verified on devnet.

A more detailed view was added in the `Balance Summary` when you click on your balance. now it shows three different fields the `Total` which is also displayed in the balance field before expanding the balance summary. `Transferable` The amount of tft that are not locked right now and can be used/transferred. `Reserved(Locked)` the amount of tfts locked/used by your contracts/deployments.

![image](https://user-images.githubusercontent.com/101194226/230903340-968f9f4d-0392-4776-a0a1-6aa91b987416.png)



> @A-Harby Should be removed in #615

and the balance was un-rounded.
