### ISSUE TITLE
Timeout in loading dedicate nodes table page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#527]
### Description

Mainnet, v1.2.1. 
Dedicate node pages take too long to load, but the problem here is that they may never finish loading and don't show any nodes.
(That also doesn't happen frequently, although it occurs)

### Steps to reproduce

1. Open any account.
2. Navigate to Dedicate page.
3. If it loads, Navigate to the next page (keep doing until you see it loading for long time)

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/220659014-3747f40d-6577-4365-b5d8-90ca39552d63.png)

**Comment by 0oM4R** [comment]
I notice that too many requests happened on loading the nodes.
![image](https://user-images.githubusercontent.com/62248851/223733460-4915da97-3370-4062-b552-9cbbd20c9053.png)
and the request takes long time to load, so I think we can enhance the logic of this section, I will discuss it tmw with Emad,
for now I can handle the axios error by return a message error on the  public IP field
![image](https://user-images.githubusercontent.com/62248851/223734124-5630315c-ea37-43f6-95a4-f2fcf45ce463.png)

**Comment by A-Harby** [comment]
Verified on Devnet, v1.4.0-rc6.
Tried with devnet and locally with main config (more farms and nodes), Repeated requests with remove, and error didn't reprodiuced. 
![image](https://user-images.githubusercontent.com/109473873/225654642-9274716c-b85c-4618-9695-2053287667b0.png)
