### ISSUE TITLE
UI changes - Shades of blue need to be the same 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtecharchive/tfgrid_dashboard#53]
Looks a bit off with the two shades in the title and the account 
![Screenshot 2022-06-17 at 10 51 32](https://user-images.githubusercontent.com/31733464/174263633-d032a26b-f91c-439e-991e-470e6a31ba56.png)

**Comment by ehab-hassan** [comment]
@sabrinasadik we used three color here blue and dark blue and black just solid color for now until we get guide color book
to apply for all apps
also using same blue at all page ll make it so poor
