### ISSUE TITLE
Simulator don't accept any decimal numbers 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#530]
### Description

The decimal number, which is necessary to do any calculations, is not accepted by any simulator number inputs.

### Logs/Alerts

Can't type the dot in any of the inputs (which is the default value in some of them).
![image](https://user-images.githubusercontent.com/109473873/220929542-014e7827-554f-4691-95f1-a287ac970570.png)
![image](https://user-images.githubusercontent.com/109473873/220929609-627d68ba-8052-49b1-8e0e-4b13bc9c2e1e.png)

**Comment by khaledyoussef24** [comment]
verified on devnet
creenshot from 2023-04-11 10-23-17](https://user-images.githubusercontent.com/110984055/231100828-8d3e9fc5-c261-411f-b1ef-0567f49f1825.png)
![Screenshot from 2023-04-11 10-23-08](https://user-images.githubusercontent.com/110984055/231100837-61d88bc1-53a6-4985-8450-7c547f869963.png)
