### ISSUE TITLE
Call to gridproxy for node details is performed twice

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtecharchive/tfgrid_dashboard#534]
### Description

Opening detailed view of a node performs the same call to gridproxy twice

### Steps to reproduce

- go to dashboard.grid.tf
- open the nodes view
- open debug tools in the browser, check network requests

**Comment by Omarabdul3ziz** [comment]
There is another issue for this https://github.com/threefoldtech/tfgrid_dashboard/issues/536. it should be fixed in this PR https://github.com/threefoldtech/tfgrid_dashboard/pull/537
