### ISSUE TITLE
redundant calls in node page in explorer

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtecharchive/tfgrid_dashboard#536]
![image](https://user-images.githubusercontent.com/32527347/222098849-d0d946ef-0059-4922-b07b-3a453440d621.png)

**Comment by A-Harby** [comment]
Verified.
Node only called once.
![image](https://user-images.githubusercontent.com/109473873/223128835-cc3f2b1a-86a4-4f5a-bbb2-c0da5c10a7fc.png)
