### ISSUE TITLE
TF Resource Pricing Bug

### ISSUE THREAD

**Issue by mik-tf** [threefoldtecharchive/tfgrid_dashboard#539]
# Bug: Resource Pricing Calculator

The Resource Pricing Calculator does not show the correct price when changing MRU.

The best way to explain is to show this video made by Teis on the TF telegram channel:
https://t.me/threefold/39887

Or to look at the screenshots here:

![Screen Shot 2023-03-02 at 8 39 12 PM](https://user-images.githubusercontent.com/77026219/222609805-5e74d0c9-2b5b-42bd-9c4d-33a6d8c22b3b.png)

![Screen Shot 2023-03-02 at 8 39 30 PM](https://user-images.githubusercontent.com/77026219/222609833-635161dd-7931-4944-8839-ea34147eafd2.png)

It costs less having 9 MRU than 1.

Note: If this has already been reported, I will delete this issue.

**Comment by mik-tf** [comment]
@xmonader 
If you can have a look.
Thanks!

**Comment by A-Harby** [comment]
Verified on Devnet, v1.4.0-rc5.
Values are calculated correctly and even when changes occurs to the inputs.
![image](https://user-images.githubusercontent.com/109473873/225027147-af35972e-d9d5-4729-a4d7-b7891a16e318.png)
![image](https://user-images.githubusercontent.com/109473873/225027220-db1cf52a-103f-4009-af3d-adc8243bf5d2.png)

**Comment by mik-tf** [comment]
Looks good on my end when I re-enter the whole parameters.

But when you put 1 CRU 1 MRU 15 SRU 0 MRU, then you change just the MRU to 9, it doesn't change to the proper value.

This is with dashboard.grid.tf

![dash1](https://user-images.githubusercontent.com/77026219/225104507-8ad5b1f1-def2-4ed5-8f92-097b13be14d6.png)

![dash2](https://user-images.githubusercontent.com/77026219/225104551-b5131de7-f110-4b28-8d90-48c04855780e.png)

With dashboard.test.grid.tf sometimes it works, sometimes not:

Here it doesn't work properly:

![dash3](https://user-images.githubusercontent.com/77026219/225105373-4fa37780-8844-4722-8789-e9298bb7f8af.png)

![dash4](https://user-images.githubusercontent.com/77026219/225105402-fe1b6041-b1ee-41b9-ae82-396e8bd53ab8.png)

**Comment by mik-tf** [comment]
It looks like, to have the proper numbers, the user needs to re-enter all the parameters at once.
If you just change one parameter, it doesn't always show the correct numbers.

@A-Harby 

let me know if you have the same results on your end.
Thanks!

**Comment by A-Harby** [comment]
@Mik-TF can I know on which network and version are you?

**Comment by A-Harby** [comment]
> This is with dashboard.grid.tf
> 
> With dashboard.test.grid.tf

Okay so this was fixed in Dev network only and haven't been released yet on the test or main network.

**Comment by mik-tf** [comment]
@A-Harby  OK! That makes sense.

Thanks.
