### ISSUE TITLE
Explorer: Status Column improvement

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#542]
### Description

The `up` & `down` labels in the status column should be capitalized.

![image](https://user-images.githubusercontent.com/101194226/223110350-95b9204b-3d19-4c34-b9ae-956141047698.png)

### Steps to reproduce

- Navigate to dashboard.dev.grid.tf/explorer/nodes

**Comment by A-Harby** [comment]
Verified 
![image](https://user-images.githubusercontent.com/109473873/230777549-01f8d379-34ad-40e9-8d8b-033b76daf253.png)
