### ISSUE TITLE
Update twin with public key if it doesn't have it

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtecharchive/tfgrid_dashboard#545]
the idea is to encrypt the messages that will go over RMB. so the dashboard should offer to update the twin with a valid public key while updating it with the relay as well.

should be similar to https://github.com/threefoldtech/rmb-sdk-ts/issues/30

**Comment by xmonader** [comment]
blocked on https://github.com/threefoldtech/rmb-sdk-ts/pull/20

**Comment by AhmedHanafy725** [comment]
this won't be possible to be done on the dashboard as it requires the mnemonics to generate the public key. so we will keep it null and when the mnemonics got used in any rmb client, it will be updated with the public key automatically
