### ISSUE TITLE
show number of deployments/number of workloads on node details 

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tfgrid_dashboard#546]
https://github.com/threefoldtech/zos/issues/1877

zos.statistics.get been extended with more information on the number of workloads and number of deployments active on a node

**Comment by A-Harby** [comment]
Where should it be displayed cause I can't find any info about it in the node page
![image](https://user-images.githubusercontent.com/109473873/227231575-f3972a82-187d-4c5b-96b4-d6a823e01602.png)

**Comment by alichaddad** [comment]
It should be displayed under `NodeDetails` but seems it wasn't deployed yet.

**Comment by mohamedamer453** [comment]
Verified on devnet.

Number of workloads and deployments is now displayed under the Node Details in the explorer.

![image](https://user-images.githubusercontent.com/101194226/230877377-1e9e3404-5454-4ced-88ca-a79321e46df2.png)
