### ISSUE TITLE
UI changes - Menu indentation

### ISSUE THREAD

**Issue by renauter** [threefoldtecharchive/tfgrid_dashboard#55]
Left menu should respect some indentation rule
Example of what should be indented:

![Screenshot from 2022-06-17 12-23-34](https://user-images.githubusercontent.com/73958772/174350555-d9a8894a-5e5a-4317-b646-34e2ccd59f4d.png)

**Comment by samaradel** [comment]
fixed
![image](https://user-images.githubusercontent.com/11662805/174477479-47ba2325-c361-493a-a1bc-8297764a0961.png)
