### ISSUE TITLE
Gateway should re-verify inputs if IP is changed

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#552]
### Description

Gateway validation doesn't re-verify itself after IP is been added or changed, in adding IP to the farm.

### Logs/Alerts

[Untitled_ Mar 9, 2023 2_55 PM.webm](https://user-images.githubusercontent.com/109473873/224030099-05fc4859-5417-4422-a3d8-3ff92b623ceb.webm)

**Comment by 0oM4R** [comment]
the rule only prop only applied on input, so the user has to re-enter the gateway, we can overcome this by making the gateway field disabled until the user enters a valid id

**Comment by A-Harby** [comment]
Also to be taken in consideration, there are cases in which a user can enter an IP to enable a gateway input, enter the gateway, and then change their IP. In this case, the gateway must be re-verified to the new IP, which is the same problem.

**Comment by 0oM4R** [comment]
I set a watcher on the ip field to handle this scenario

**Comment by A-Harby** [comment]
Verified on Devnet,
Gateway is now displayed until the IP is typed and validate correctly and even after that if gateway is changed, its validated again  
![image](https://user-images.githubusercontent.com/109473873/230777270-c414727a-2955-48d3-9404-cf8d8f29e31f.png)
