### ISSUE TITLE
Feature request: Improve the look of the Dao Proposal Cards

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#553]
### Description

Currently the look and feel of the Proposal card in the Dao page is not very pleasing and the details are a bit vague.

### Suggestion

- Add titles next to each field:
    - Proposal Hash
    - Proposal Name
    - Forum Link
    - Expiration Date

   ![image](https://user-images.githubusercontent.com/101194226/224090520-ca0261f2-f127-4972-a9d9-49d5a721fd8e.png)

    
- Make the font and size of the titles distinct from the data.

   ![image](https://user-images.githubusercontent.com/101194226/224090637-f3aa0198-de1c-4384-b18f-c852a5cfae6e.png)

- Add equal and symmetrical spaces between the data.

   ![image](https://user-images.githubusercontent.com/101194226/224090817-33be9c1a-3dc7-47ce-b554-0377c956e1ab.png)

- Make the outline of the cards more visible so it doesn't look like all of the cards are blended together.

   ![image](https://user-images.githubusercontent.com/101194226/224090936-c595cb50-386c-4888-8170-a53f63dfbe91.png)

- Make the Voting bar a bit smaller and it should be the last item in the card.

- Make the progress bar more rounded.

   ![image](https://user-images.githubusercontent.com/101194226/224091507-002270bd-5386-4ccd-84bf-e3b256223186.png)

- The colors of the progress bar should be an indicator to the vote, currently it's blue and white. if it was something like red and green it would be much easier for the user to understand but UI wise I don't know if it will match the colors of the dashboard or not (These are not the proposed colors but something in that direction for clarification)

   ![image](https://user-images.githubusercontent.com/101194226/224091231-0daede35-a4ec-4f11-b7af-907a6d06f484.png)

**Comment by 0oM4R** [comment]
>The colors of the progress bar should be an indicator to the vote, currently it's blue and white. if it was something like red and green it would be much easier for the user to understand but UI wise I don't know if it will match the colors of the dashboard or not (These are not the proposed colors but something in that direction for clarification)

@mohamedamer453 
I think it is the color of the progress bar is the same for the buttons

**Comment by mohamedamer453** [comment]
> @mohamedamer453 I think it is the color of the progress bar is the same for the buttons

Indeed it's the same color but as seen above when the voting is done or the proposal is completed it's hard to differentiate between the votes since the buttons disappear and there's no other indication.

That's why i proposed for it to be red/green or some other color that would be a clear indicator without thinking about it or looking for further info.

**Comment by 0oM4R** [comment]
> > @mohamedamer453 I think it is the color of the progress bar is the same for the buttons
> 
> Indeed it's the same color but as seen above when the voting is done or the proposal is completed it's hard to differentiate between the votes since the buttons disappear and there's no other indication.
> 
> That's why i proposed for it to be red/green or some other color that would be a clear indicator without thinking about it or looking for further info.

@ehab-hassan can we go with red/green? if no can you please suggest colors for the buttons and progress bar?

**Comment by ehab-hassan** [comment]
@0oM4R for now it's nice!!! I preferer blue and gray

**Comment by mohamedamer453** [comment]
Verified on devnet.

All of the mentioned comments were addressed and improved as mentioned above.

- Titles were added next to each value with a clear and distinct font from the value itself. and the vote ending date was moved.

   ![image](https://user-images.githubusercontent.com/101194226/230869660-be622414-9ebf-4672-8a08-c9420d07532e.png)

- Spaces between every element are now uniform and symmetrical.

   ![image](https://user-images.githubusercontent.com/101194226/230869970-95babe50-af8c-4f76-8946-09db2c3160c7.png)

- A clear outline was added to separate each proposal.

   ![image](https://user-images.githubusercontent.com/101194226/230870127-30be10d2-6a9e-4135-bf19-09a418106bb5.png)

- Voting bar is now a bit smaller and more rounded.

   ![image](https://user-images.githubusercontent.com/101194226/230870556-49c76a7e-95a7-4104-97d3-644577fbdb5b.png)

- As mentioned above the colors were agreed on to say the same.

   > @0oM4R for now it's nice!!! I preferer blue and gray
