### ISSUE TITLE
TestLodge: TC799 – Testnet/qanet/mainnet - Delete Twin

### ISSUE THREAD

**Issue by TullysInc** [threefoldtecharchive/tfgrid_dashboard#555]
Delete button is not available in testnet and qanet:

![QA Grid_twin delete](https://user-images.githubusercontent.com/105203696/224114759-7148dd1e-61de-4f5b-8905-c7f310a6c0f0.jpg)
![Test Grid_twin delete](https://user-images.githubusercontent.com/105203696/224114767-87f12d97-63c9-44d2-b400-f75d1f35f77d.jpg)

When initially cross verified with mainnet the button was available, but it isn't there now:

![mainnet_twin delete](https://user-images.githubusercontent.com/105203696/224116788-f93fd8f4-49f3-4ee4-b572-d76e73df1c09.jpg)
![mainnet_twin delete_2](https://user-images.githubusercontent.com/105203696/224116796-142f92cc-7b69-4d11-8a3d-4a53795d7817.jpg)

**Comment by ramezsaeed** [comment]
This will be also removed from Mainnet when 3.9 deployed
