### ISSUE TITLE
TestLodge: TC839 – Testnet/qanet/mainnet – Explorer – Filter Nodes by Farming Policy

### ISSUE THREAD

**Issue by TullysInc** [threefoldtecharchive/tfgrid_dashboard#556]
Farming Policy filter is not available across all networks.

![Tesnet_Explorer_Nodes_Farming Policy filter](https://user-images.githubusercontent.com/105203696/224118561-4af727a9-9734-4ab6-8170-106e25a9ac43.jpg)

**Comment by khaledyoussef24** [comment]
farming policy is removed from the dashboard
it exists in the gridproxy only now
![image](https://user-images.githubusercontent.com/110984055/227772757-f8c33268-3cff-4ebf-8928-7baac65a80e6.png)
test case is removed
