### ISSUE TITLE
TestLodge: TC841 – Testnet/qanet/mainnet – Explorer – Filter Nodes by Certification Type

### ISSUE THREAD

**Issue by TullysInc** [threefoldtecharchive/tfgrid_dashboard#557]
Certification Type filter is not available across all networks.

![Tesnet_Explorer_Nodes_Certification Type Filter](https://user-images.githubusercontent.com/105203696/224121596-f48bb2b6-c817-46f9-83d6-e560a78b5693.jpg)

**Comment by ramezsaeed** [comment]
certified node only found on mainnet

**Comment by khaledyoussef24** [comment]
test case renamed from Filter Nodes by Certification Type to Filter Farms by Certification Type
because Certification Type filtering is only found in Farms

![image](https://user-images.githubusercontent.com/110984055/227772325-6cb10ca6-969c-4375-8c2f-aab27a009958.png)
