### ISSUE TITLE
TestLodge: TC849 – Testnet – Explorer – Verify Farm Info from grid_proxy

### ISSUE THREAD

**Issue by TullysInc** [threefoldtecharchive/tfgrid_dashboard#558]
Some details (Pricing Policy, Certification Type, Public Ips) available in grid_proxy are not shown in the Explorer. Please see image for comparison.

![Farm ID 8_info mismatch Explorer](https://user-images.githubusercontent.com/105203696/224125457-208e086e-c727-442d-baa2-8d44f8dca816.jpg)

**Comment by ramezsaeed** [comment]
That's Expected by design.
