### ISSUE TITLE
Hide the publicConfig section if it's empty, and fix the node resources data

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtecharchive/tfgrid_dashboard#560]
The below section should be hidden if the public config is empty.

![image](https://user-images.githubusercontent.com/57001890/224540817-1bbc8a06-524e-4564-b777-7ae8985cd0d0.png)

The node resources are wrong, should add the right data that came from the grid proxy.

![image](https://user-images.githubusercontent.com/57001890/224540825-2d9c0a1a-618c-4d81-a420-ba1c2177cfbd.png)

**Comment by A-Harby** [comment]
Is it fixed but not released yet?
![image](https://user-images.githubusercontent.com/109473873/225041506-69a58ed6-905f-4d70-851c-7cd26d8827e6.png)

**Comment by A-Harby** [comment]
Verified on Devnet, v1.4.0-rc6.
Empty public IP config have been removed from the node details if its empty and node data are retrieved correctly from the grid proxy.
![image](https://user-images.githubusercontent.com/109473873/225047161-7e8e8382-f711-4650-b254-26be397c40a7.png)
