### ISSUE TITLE
Repeated requests on Dedicated node page

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtecharchive/tfgrid_dashboard#561]
### Description

after the improvements made on #559 some repeated requests still happened 3 times on mounting the page and 2 times on updating the table

### Steps to reproduce

1. Open any account.
2. Navigate to Dedicate page

### Logs/Alerts

![Screenshot from 2023-03-12 13-07-00](https://user-images.githubusercontent.com/62248851/224540962-3c099fab-4a2f-42fc-8b40-4097596d4efc.png)

**Comment by A-Harby** [comment]
Verified Devnet, v1.4.0-rc8.
Tried reloading the dedicate node and request was always sent once.
![image](https://user-images.githubusercontent.com/109473873/227226911-8c27a479-f13f-46fa-922b-9048f50fc7c3.png)
