### ISSUE TITLE
Change the default value of Stellar network to `test` instead of `main`. 

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtecharchive/tfgrid_dashboard#571]
`dev` and `qa` as i understand are working against stellar `testnet`, you have to pass it also as it's required if you are going to work against `testnet`, also the env var is `STELLAR_NETWORK`

it makes sense to set the default value to `test` instead of `main` because the `TFCHAIN_NETWORK` default value is dev

this issue maybe related to this one also https://github.com/threefoldtech/tfgrid_dashboard/issues/569

**Comment by A-Harby** [comment]
Verified https://github.com/threefoldtech/tfgrid_dashboard/issues/569#issuecomment-1471684088
