### ISSUE TITLE
UI light mode fix

### ISSUE THREAD

**Issue by renauter** [threefoldtecharchive/tfgrid_dashboard#58]
"Your Farms" frame should be light (same way as other account sections) 

![Screenshot from 2022-06-20 08-04-55](https://user-images.githubusercontent.com/73958772/174588381-f70f26ad-3779-42ca-b5e8-b32c5e54e898.png)

**Comment by mohamedamer453** [comment]
Verified.

The color of the table now matches the chosen theme

### Light

![image](https://user-images.githubusercontent.com/101194226/181286248-a2b04cc7-cd6a-487b-976b-1a003e64ddd0.png)


Dark

![image](https://user-images.githubusercontent.com/101194226/181286340-9ce3d9c4-189b-44a8-9b9e-4def98d1dac6.png)
