### ISSUE TITLE
After creating a twin I get sent back to home screen

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtecharchive/tfgrid_dashboard#583]
On mainnet dashboard I created a twin, transaction was completed but the UI sent me back to the screen where I could select an account

**Comment by khaledyoussef24** [comment]
fixed and verified on devnet[Screencast from 03-26-2023 01:41:48 PM.webm](https://user-images.githubusercontent.com/110984055/227773350-2d3e0790-a68a-46ef-b944-dae9e8bd4c7c.webm)
