### ISSUE TITLE
Portal pages wont open after navigate to any of the Calculator tabs.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#587]
### Description

Portal pages wont open after navigate to any of the Calculator tabs. 

### Steps to reproduce

1. navigate to a twin 
2. Expand Calculators
3. Choose Simulator

### Logs/Alerts

[Untitled_ Mar 23, 2023 2_40 PM.webm](https://user-images.githubusercontent.com/109473873/227207340-adbe863b-cec6-4c4a-b50e-c7fda13acea0.webm)

Link shown when bug occure
https://dashboard.dev.grid.tf/calculator/simulator/account-swap

**Comment by khaledyoussef24** [comment]
tested and verified on devnet and working fine
[Screencast from 04-10-2023 11:48:43 AM.webm](https://user-images.githubusercontent.com/110984055/230878269-9f7aa107-12fc-4f9b-adbe-686d803f3cd5.webm)
