### ISSUE TITLE
DAO Vote: Can't select farm

### ISSUE THREAD

**Issue by mik-tf** [threefoldtecharchive/tfgrid_dashboard#591]
# DAO Vote: Can't select farm

As of now, we can't select farms when voting for the DAO Foldit proposition.

![dao_1](https://user-images.githubusercontent.com/77026219/227313720-5bdb4ac3-19da-49e8-a278-1e3f6fd029c2.png)

**Comment by mik-tf** [comment]
Also detail but we could write this sentence better:

![Screen Shot 2023-03-23 at 8 55 02 PM](https://user-images.githubusercontent.com/77026219/227396973-2485eec2-d513-43e1-8d76-cce4cd846bff.png)

**Comment by DylanVerstraete** [comment]
Fixed in https://github.com/threefoldtech/tfgrid_dashboard/commit/433f07e14ea647eb4f10a5af9a8d8efc37e4521d and deployed on mainnet
