### ISSUE TITLE
unnecessary requests on update  farm page

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtecharchive/tfgrid_dashboard#593]
### Description

we need to update the portal farm page code, https://github.com/threefoldtech/tfgrid_dashboard/blob/17ed34a1f09c909319e605101d31d9daf0eacb26/src/portal/views/Farms.vue#L300
inside the update we are getting farms, this request is made every 3 sec
https://github.com/threefoldtech/tfgrid_dashboard/blob/17ed34a1f09c909319e605101d31d9daf0eacb26/src/portal/views/Farms.vue#L302
### Steps to reproduce
you can add a log before this line and open the portal/farms page you will see the log message in the console every 3 sec.

### Logs/Alerts

![image](https://user-images.githubusercontent.com/62248851/227768787-78e6e266-1201-4386-a4eb-52340f50a112.png)

**Comment by A-Harby** [comment]
Verified from code the updated function is removed and log don't show the request every 3 seconds
