### ISSUE TITLE
can not create a twin on mainnet

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtecharchive/tfgrid_dashboard#595]
### Description

can not create a twin on mainnet after creating a polkadot account and error shows say 'account balance is too low'
 
### Steps to reproduce

1. go to [dashboard.grid.tf](dashboard)
2. choose your account
3. click on accept and agree with ThreeFold Grid](https://library.threefold.me/info/legal/#/threefold__threefold_grid) USER and/or FARMER TERMS AND CONDITIONS
4. the account balance is too low message will be prompt 

![Screenshot from 2023-03-26 13-02-54](https://user-images.githubusercontent.com/110984055/227773752-7f7497a9-7a24-4d54-a40c-2b9001d8a010.png)

**Comment by AhmedHanafy725** [comment]
suspecting the issue in the activation service or in the dashboard itself:
1- the activation service has no tokens
2- there is a bug on the dashboard (it calls the accept T&C before activating the account)

so can you please try to create an account on mainnet with the ts client version 1.5.0? and check if you will get the same error.

**Comment by A-Harby** [comment]
Getting the same error on Testnet but not on dev or qanet.

**Comment by mohamedamer453** [comment]
> suspecting the issue in the activation service or in the dashboard itself: 1- the activation service has no tokens 2- there is a bug on the dashboard (it calls the accept T&C before activating the account)
> 
> so can you please try to create an account on mainnet with the ts client version 1.5.0? and check if you will get the same error.

Working fine on `devnet`, but got the mentioned error both on `testnet v2.0.0-rc12` & `mainnet v1.5.0`

![image](https://user-images.githubusercontent.com/101194226/227777380-5df9ceb9-8a66-44a2-be3f-1915ca1fe1ff.png)

**Comment by AhmedHanafy725** [comment]
okay seems the activation service has an issue

**Comment by khaledyoussef24** [comment]
### verified on mainnet
[Screencast from 03-28-2023 11:25:29 AM.webm](https://user-images.githubusercontent.com/110984055/228193585-c00da5c2-ec23-4bc6-989a-aa2fd7507b68.webm)
[Screencast from 03-28-2023 11:26:49 AM.webm](https://user-images.githubusercontent.com/110984055/228193630-e8c7d301-cfba-46e1-b0d7-d967863df93c.webm)
twin created successfully
