### ISSUE TITLE
Stellar network is set to the testnet not mainnet.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#596]
### Description

Stellar network on the dashboard testnet v1.4.0-rc8 is set to the stellar testnet not their mainnet.

Accepting testnet stellar address
![image](https://user-images.githubusercontent.com/109473873/227778350-4bf472eb-1fdb-40a4-8b8a-8e3db4d6cb51.png)
But not the mainnet stellar address.
![image](https://user-images.githubusercontent.com/109473873/227778398-c27b9822-72cc-4150-a73d-3dd191c93c72.png)

**Comment by hossnys** [comment]
this should be fixed now by this https://github.com/threefoldtech/tf_operations/issues/1539

**Comment by A-Harby** [comment]
Verified
![image](https://user-images.githubusercontent.com/109473873/227975407-7e6b48bb-1398-4acd-bbb2-40d8078fd978.png)
