### ISSUE TITLE
TFChain transfers addressbook 

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtecharchive/tfgrid_dashboard#61]
When transfering TFT between accounts on TF Chain it can be very useful to have an "addressbook". For example a transfer between one of my accounts should be as easy as selecting another account of mine as destination. 

Transfer -> fill in address or select one of my accounts

**Comment by amiraabouhadid** [comment]
This is already included in the current release, it automatically fills in addresses of all accounts connected:
![Screenshot from 2022-06-20 15-57-44](https://user-images.githubusercontent.com/56790126/174617985-71eccf8f-5b6f-4665-9a4d-43e00b1dee72.png)

**Comment by DylanVerstraete** [comment]
Great! Sorry I didn't know!
