### ISSUE TITLE
Update Dao Proposal Votes Progress Bar

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtecharchive/tfgrid_dashboard#62]
Need a better visualization of the voting progress that takes into account the following: 
- User's weights based on farms, nodes, and node specs
- Shows the threshold needed

**Comment by DylanVerstraete** [comment]
Voting progress can still be shown in a progress bar. A threshold is set on each proposal, every time a farmer votes this progress bar can be updated until the threshold is met (100%)

The outcome of a proposal should be shown in another way. For example if 5 farmers vote YES and 5 farmers vote NO the outcome of that proposal (yes or no) will rely on the weight of the farmer (stake in the network). The weight is calculated as following for every node in the user's farm: `node CU*2 + node SU`

Maybe the weight of all the yes / no votes can be shown under the amount of votes in the yes/no boxes.

other visualization options are:

- histogram
- pie chart
- text (outcome at this moment is : yes/no)
