### ISSUE TITLE
Dao pop up shown after change the profile

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtecharchive/tfgrid_dashboard#628]
[Screencast from 10 أبر, 2023 EET 03:36:28 م.webm](https://user-images.githubusercontent.com/62248851/230922107-e9866ddc-96c2-45be-a2c9-6bdb4efd861c.webm)

### Description

Dao pop up shown after change the profile, and if the second profile has no farms, will get the old notification to vote!

### Steps to reproduce

- log in with account has a farm
- log out before the pop up appears
- log in again

**Comment by mohamedamer453** [comment]
Verified on devnet.

The issue was fixed and now the pop up doesn't appear with the old notification after changing profiles.

[Screencast from 12-04-23 09:55:32.webm](https://user-images.githubusercontent.com/101194226/231391094-26dd6dad-868c-4ba0-8616-ae6d6cf6ab85.webm)
