### ISSUE TITLE
Public key missing from new twin on testnet

### ISSUE THREAD

**Issue by scottyeager** [threefoldtecharchive/tfgrid_dashboard#630]
I've created a new twin on testnet using the dashboard, with id 919. It does not have a public key filled in, thus cannot participate in RMB communication. Seen here, along with another example provided by another user:

![image](https://user-images.githubusercontent.com/17682591/230985417-589573e4-3d81-4e68-8785-33cf83fe4448.png)

We'll need a way to correct this on any twins created without a key so far, as well as fixing it for twins created in the future.

**Comment by muhamadazmy** [comment]
This is not an issue, because the `twin` on tfchain (substrate) also has also **no** public key. the public key is optional and is only needed if the twin wants to use **end to end** encryption hence not all twins has to have a `pk`

Also note that those twins are NOT associated with nodes. those twins are probably used by clients (and not nodes) that don't want e2e (or don't support it)

**Comment by scottyeager** [comment]
Thanks for weighing in, @muhamadazmy. I had assumed that the key would always be set at the time of twin creation, or in the case of existing twins, when setting the relay.

In this case, I used my other twin for testing `farmerbot`, so the `rmb-peer` had set the public key. Only twins with a previously set public key are working in the testnet playground, so it seems the real issue is that the playground should be checking and setting the key if needed. I'll follow up there.

**Comment by AhmedHanafy725** [comment]
the newly created twins from the dashboard yes don't have the publicKey set as we don't have the mnemonics. https://github.com/threefoldtech/tfgrid_dashboard/issues/545#issuecomment-1468172697
but it will be updated once it's used in the clients (`go rmb client`, `ts rmb client`, or `rmb-peer`). the playground is using the `ts rmb client`, so once the mnemonic is set there, it will be automatically updated with the public key

I just tried it on testnet to make sure and it worked 
![image](https://user-images.githubusercontent.com/41957921/231273975-780805ab-c030-4602-bfd7-5152b1ba7c7b.png)

**Comment by scottyeager** [comment]
Hi @AhmedHanafy725,

We have several reports, including my own experience, that the playground is not setting the public key (https://github.com/threefoldtech/tfgrid-sdk-ts/issues/73). I'll keep collecting examples and update the issue on the weblet repo.
