### ISSUE TITLE
Integrate playground into the dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tfgrid_dashboard#76]

**Comment by MohamedElmdary** [comment]
### PR
https://github.com/threefoldtech/tfgrid_dashboard/pull/174

**Comment by khaledyoussef24** [comment]
verified

![Screenshot from 2022-09-18 18-15-32](https://user-images.githubusercontent.com/110984055/190917179-286bd0ad-65ef-4239-8fd0-c2a655e4cce2.png)

**Comment by A-Harby** [comment]
[TC1199 - Playground, Zero-OS Hub and Bootstrap Integrated in dashboard](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348399#case_3740971)
