### ISSUE TITLE
The add balance icon in qanet portal doesn't add balance and redirects to getTFT

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#82]
### Description

![image](https://user-images.githubusercontent.com/101194226/177763755-11da43e7-8b9f-4014-83ce-f86c39a40429.png)

The add balance icon on QAnet should add 100 tokens when you click on it (Like devnet) but now it redirects the user to https://gettft.com/auth/login?next_url=/gettft/shop/#/buy which is supposed to happen only on testnet and mainnet.

**Comment by AhmedHanafy725** [comment]
once it's deployed on qanet, it can be verified

**Comment by mohamedamer453** [comment]
Verified on qanet.

The add balance icon on qanet dashboard now functions correctly and adds 100tft to your account once you click on on it.

![TF DASHBOARD (21)](https://user-images.githubusercontent.com/101194226/187620868-9501d1e8-37ce-4928-b5eb-c3a75a096ca3.gif)
