### ISSUE TITLE
Can't delete farms with Public IPs

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#86]
Farms with added public IPs can't be deleted

### Deleting a farm with a Public IP

the farm is not deleted and the error message doesn't mention anything about deleting the public ip first.

![tfgrid_dashboard (4)](https://user-images.githubusercontent.com/101194226/177774536-aa7b8fd6-c902-4ddb-b1f7-0344bc35adef.gif)

### Deleting the IP first then deleting the farm

![tfgrid_dashboard (5)](https://user-images.githubusercontent.com/101194226/177775025-a50eb9ee-065f-42f4-83d1-113fd2785f32.gif)

**Comment by DylanVerstraete** [comment]
Can we please not let the user delete a farm. It's not a safe operation.

**Comment by mohamedamer453** [comment]
The `Delete Farm` options is still available on testnet 

![image](https://user-images.githubusercontent.com/101194226/182024479-6bd559ce-f977-46aa-8488-12208ad5c0d1.png)

**Comment by mohamedamer453** [comment]
Verified.

The Delete action was removed from the farms table.

![image](https://user-images.githubusercontent.com/101194226/182033875-e3fb5d1d-8965-4993-8b69-070531e2892f.png)
