### ISSUE TITLE
UI: Add Icons for (Statistics, Nodes, Farms) when the sidebar is minimized 

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#88]
Currently when you expand the explorer from the sidebar and minimize it the expanded options will appear in the sidebar but without any icons.

![tfgrid_dashboard (6)](https://user-images.githubusercontent.com/101194226/177785081-27dcc4b9-6c83-4b26-92d6-fc91853d8add.gif)

So, icons for the (Statistics, Nodes, Farms) should be added in the minimized sidebar 
or remove the option of selecting them when the sidebar is minimized.

**Comment by rawdaGastan** [comment]
I think this issue is solved. I tried it and the option is removed

**Comment by mohamedamer453** [comment]
Verified.

The invisible icons/buttons were removed and they don't appear when the sidebar is minimized.

![TF DASHBOARD (14)](https://user-images.githubusercontent.com/101194226/183287980-abf1c922-e26e-4d8c-b194-7448557d70c7.gif)
