### ISSUE TITLE
Withdraw TFT: Input validation 

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#90]
Currently there is no validation for either the `Stellar Target Wallet Address` or `Amount` fields in the Withdraw TFT menu.

![image](https://user-images.githubusercontent.com/101194226/177795011-af2fd3f2-337c-4a66-950c-997934d49e15.png)

### Stellar Target Wallet Address

- Empty Field Validation
- Address format validation
- Min/Max address length (if there' a defined address length)

### Amount

- Empty Field Validation.
- Accepts Numeric Values Only (except for `.` if decimal values are allowed)
- Insufficient Balance Validation.

*** Appropriate validation messages should be added for all of the mentioned validations. and the `Submit` button should be disabled.

**Comment by A-Harby** [comment]
The button is disabled when there is an empty field, and address validation works.

However, for negative numbers, the button should be disabled.
![image](https://user-images.githubusercontent.com/109473873/181276391-a597dfc0-585a-4e76-b977-7d4055eac849.png)

Secondly, the value is set to 0 by default, and after entering a valid address and attempting to submit, the button is disabled and an alert occurs (which is correct).
![image](https://user-images.githubusercontent.com/109473873/181277132-060014cc-d6bd-4b08-9d29-7515b9803e31.png)

But, after increasing the value and decreasing it down to 0, you will be able to submit.
![image](https://user-images.githubusercontent.com/109473873/181277751-4c486a9c-76b9-43d1-8ea8-e9dbce60077e.png)

**Comment by mohamedamer453** [comment]
Verified.

- Negative values are not accepted anymore.

   ![image](https://user-images.githubusercontent.com/101194226/182034830-6f987615-a073-4020-bb7c-2fff5a20aa80.png)

- After increasing the value and decreasing it back to 0 the submit button was still disabled.

   ![image](https://user-images.githubusercontent.com/101194226/182034804-4ed489b4-38ae-494a-9266-370ff39bb1e4.png)
