### ISSUE TITLE
Transfer TFT: Input validation

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#91]
The validation for the Transfer TFT page is not working correctly.

### Recipient 

- The `invalid Address` validation message is triggered even before the user types anything in the field.

   ![image](https://user-images.githubusercontent.com/101194226/177798278-428a3c07-8442-47f4-b80a-05ca84b96f16.png)

- There is no Empty Field validation or a specific validation message for it. the only validation message available is `invalid address`

-  There's an unclear message that appears when you try to submit with an invalid address

   ![image](https://user-images.githubusercontent.com/101194226/177799080-6ca10b57-8ade-43b3-a83b-8fbb5104670b.png)

- When you enter a valid address and then remove it the validation message appears but the validation doesn't work and you can actually send TFTs to an empty address and the TFTs will be deducted from your account.

   ![tfgrid_dashboard (8)](https://user-images.githubusercontent.com/101194226/177801960-c6265e3c-5d9b-45fc-b86d-497ba3735885.gif)

- The Submit button is not disabled in any of the mentioned cases.

### Amount

- Empty field validation is not working and you can complete a transaction with the amount field left empty.

   ![tfgrid_dashboard (9)](https://user-images.githubusercontent.com/101194226/177803293-1f8e16e4-942a-453d-bf8c-91922ceefd59.gif)

- The field should accept numeric values only however the user can enter other values like `+`, `-`, `e`

   ![image](https://user-images.githubusercontent.com/101194226/177803747-5821b1eb-590d-4ad1-a691-b7b8792fbc8b.png)

   ![image](https://user-images.githubusercontent.com/101194226/177803836-e5985486-3949-4cfc-a283-4a9deabc85fb.png)

   ![image](https://user-images.githubusercontent.com/101194226/177803985-9c46cbbb-129d-4d47-abb3-98c407f50e70.png)

- Insufficient balance validation is available but it only shows the message and it's not working

   ![tfgrid_dashboard (10)](https://user-images.githubusercontent.com/101194226/177803448-fcb3e94f-463e-48d9-9e44-0496d03136a5.gif)

- The Submit button is not disabled in any of the mentioned cases.

**Comment by A-Harby** [comment]
Recipient validation works for wrong address and empty field.
Amount (TFT) validation works for Amount cannot exceed balance and 0 amount,
But
1. Balance Value isn't updated after successful transfer is done.
![DASHBOARD](https://user-images.githubusercontent.com/109473873/181292823-62ae80ff-9785-4e07-9e64-1201ff1184bf.gif)

2. After increasing the value and decreasing it down to 0, you will be able to submit.
![image](https://user-images.githubusercontent.com/109473873/181286592-1e2706d5-8565-4e60-8c8b-4400a9b4c84f.png)
And keep loading when u submit.
![image](https://user-images.githubusercontent.com/109473873/181290210-9da8e433-95fc-427c-aa37-5da96b216c22.png)

3. For negative values, the button should be disabled.
![image](https://user-images.githubusercontent.com/109473873/181286789-3fb57137-1630-4d3b-8788-db4f1dbd52ac.png)
When submitting
![image](https://user-images.githubusercontent.com/109473873/181290479-a0e50184-7398-4475-9c6e-d6d7fc05320e.png)

**Comment by mohamedamer453** [comment]
Verified.

- The balance is updated after the transaction is done.

   ![TF DASHBOARD (8)](https://user-images.githubusercontent.com/101194226/182034632-dbcf7c0f-b94f-45bb-8153-cb12c09895c3.gif)

- After increasing the value and decreasing it again to zero the submit button was still disabled.

   ![image](https://user-images.githubusercontent.com/101194226/182034618-ffcc5160-76da-444e-a82d-e2a1f62f0e7c.png)

- Negative values are not accepted anymore

   ![image](https://user-images.githubusercontent.com/101194226/182034666-c966568e-f842-44d6-babc-f145691e5166.png)
