### ISSUE TITLE
Stellar Payout Address: Input Validation 

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#93]
Currently There is no validation added for the Stellar Payout Address field and it currently accepts anything.

![image](https://user-images.githubusercontent.com/101194226/177809656-f3117ef4-393d-46a5-9b56-7fe5761d7d57.png)

Validations that should be added to this field:

- Empty Field Validation
- Address format validation
- Min/Max address length (if there' a defined address length)
- Appropriate validation messages should be added for all of the mentioned validations. and the Submit button should be disabled.

**Comment by mohamedamer453** [comment]
Verified.

- Empty field validation was added.

   ![image](https://user-images.githubusercontent.com/101194226/181277201-00be8914-fb0b-471c-b408-875300852148.png)

- Address Format Validation was added and currently it accepts valid addresses only and disables the submit button when a validation is triggered.

   ![image](https://user-images.githubusercontent.com/101194226/181277748-e6ed04a8-d619-4784-aa9f-7bf5fa1dddcb.png)

- Appropriate validation messages were added and the submit button was disabled in all the mentioned cases.

**Comment by A-Harby** [comment]
The button is disabled when there is an empty field, and address validation works.

However, for negative numbers, the button should be disabled.
![image](https://user-images.githubusercontent.com/109473873/181276391-a597dfc0-585a-4e76-b977-7d4055eac849.png)

Secondly, the value is set to 0 by default, and after entering a valid address and attempting to submit, the button is disabled and an alert occurs (which is correct).
![image](https://user-images.githubusercontent.com/109473873/181277132-060014cc-d6bd-4b08-9d29-7515b9803e31.png)

But, after increasing the value and decreasing it down to 0, you will be able to submit.
![image](https://user-images.githubusercontent.com/109473873/181277751-4c486a9c-76b9-43d1-8ea8-e9dbce60077e.png)
