### ISSUE TITLE
dashboard title

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tfgrid_dashboard#94]
right now it says tfgrid_dashboard 
![image](https://user-images.githubusercontent.com/64129/177811781-f35b952a-0a52-45c3-91ce-0bcf6d551489.png)

I suggest we make it TF Dashboard

**Comment by mohamedamer453** [comment]
The title was changed but not as the one suggested in the issue, i think it would look better as mentioned `TF Dashboard`

![image](https://user-images.githubusercontent.com/101194226/181267398-63650418-4361-4544-8a1e-dd65068bd7c8.png)

**Comment by amiraabouhadid** [comment]
also done :D

**Comment by mohamedamer453** [comment]
Verified.

The title was changed to `TF DASHBOARD`

![image](https://user-images.githubusercontent.com/101194226/181509264-774b1b30-cb44-4fd6-8894-f71edadf7073.png)
