### ISSUE TITLE
Portal menu items order

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tfgrid_dashboard#95]
![image](https://user-images.githubusercontent.com/64129/177812191-4b069499-dc12-499a-ba6b-65e43e8a92a4.png)

I suggest in the sidebar 
- farms
- nodes
- dao 

instead of 
- farms
- dao
- nodes

**Comment by mohamedamer453** [comment]
Verified 

the order of the menu items was changed and the `Account - `  prefix was removed from all titles.

![image](https://user-images.githubusercontent.com/101194226/181264791-10cf9523-94f1-41e9-be11-f171871fec11.png)
