### ISSUE TITLE
Farms: Certification Type Filter is not working

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#97]
The Certification type filter in the Farms table is not working and doesn't filter any farms with the 2 available options `DIY` and `Certified`

![tfgrid_dashboard (13)](https://user-images.githubusercontent.com/101194226/177817923-1955ed24-7731-40d5-8971-aa0ca6543d91.gif)

**Comment by rawdaGastan** [comment]
@mohamedamer453 Farms don't have a certification that's why they all disappear after choosing a certification filter

**Comment by mohamedamer453** [comment]
Verified.

the certification types were updated and now it returns the nodes when the filter is applied.

![image](https://user-images.githubusercontent.com/101194226/181590478-07291d9b-8adb-4dc6-8cdc-4e86702828d3.png)

![image](https://user-images.githubusercontent.com/101194226/181590525-86bf1e77-fe36-48a7-b562-6930f9e57e9c.png)
